### PR TITLE
Update example and live demo in README.md

### LINKED ISSUE #386: Illustrate the example code in live demos and docs
When looking through the live demos, it is not immediately visible what item templates do. Users have to open the combo-boxes to see it.

This could be resolved by adding screenshots or keeping the combo-boxes open.

Asciidoc should also have screenshots next to the code examples.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #386 

Images which were replaced by similar are optimized, e.g. `vaadin-combo-box-item-template-material.png`: 110KB -> 46KB

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/400)

### CODE REVIEW

**Comment by platosha** [comment]
Let us put the images right next to the code examples. Putting them close together makes a better meaningful connection between them. I think, we usually put screenshots below the examples in asciidoc guides, for ex.: https://github.com/vaadin/vaadin-upload/blob/master/docs/vaadin-upload-custom.adoc

Also, please, specify explicit size for the images, otherwise they look awfully huge. Use the `width` alone, it works the best way:
- the default scale is correct,
- it is easy to override with `max-width` for narrow page layouts,
- when width is overriden and height is unspecified, the height remains automatically calculated with respect to the image apect ratio.

It would be also nice to have titles or at least alternative texts for the images.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-KcbfDsjctsDWHcqMeJu:b-1tnrrj)*

**Comment by limonte** [comment]
Done, thanks for nice suggestions!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-KcbmeuQ-QvTXKWIDylU:bxk4sde)*

**Comment by Saulis** [comment]
Tried running this readme in the webcomponents.org preview mode but couldn't get it working

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcvYW6KV83tMUvtOlLh:-KcvYW6L6Zcti964JoD7:bbagc8v) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L44)):*
> ```Markdown
> 
> <script>
>   var comboBox = document.querySelector('vaadin-combo-box');
> ```

I'd prefer using `<iron-ajax>` here to fetch the data to avoid script and querySelector.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-KcvYmvM-iunFLwXyb8x:b-qkigre)*

**Comment by limonte** [comment]
> Tried running this readme in the webcomponents.org preview mode but couldn't get it working

Works fine: https://www.webcomponents.org/preview/vaadin/vaadin-combo-box/ec5d14ca675540baa9bfaefd118450f619f36418

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcvYW6KV83tMUvtOlLh:-KcvmR1Aig38GSnTEI3z:b-ys6n8h) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L44)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I'd prefer using `<iron-ajax>` here to fetch the data to avoid script and querySelector.
</blockquote></details>

This was my first try, but unfortunately I can't get it work in webcomponents.org and Tomi suggested this solution

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-KcvmP7gClYCQ-5FetQ5:b-qnsp6g)*

**Comment by limonte** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcvYW6KV83tMUvtOlLh:-Kcw42SJNXXQ7wC--xc3:bjlzmnf) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L44)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This was my first try, but unfortunately I can't get it work in webcomponents.org and Tomi suggested this solution
</blockquote></details>

Done: https://www.webcomponents.org/preview/vaadin/vaadin-combo-box/57d1abc179e1938db25678bfd0cef7e397fe2cca

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400)*

**Comment by tomivirkki** [comment]
*[README.md, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcwFjR3EiXdnxnQwaMt:-KcwFjR3EiXdnxnQwaMu:bw3pvwj) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L27)):*
> ```Markdown
> <style is="custom-style">
>   paper-icon-item {
>     margin: -13px -16px;
> ```

These hacks with negative magic numbers in our public demos are so hacky...should we still reconsider the default padding @platosha ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcwFjR3EiXdnxnQwaMt:-KcwIwt1rteJMdP3uqVO:b-rgk8dd) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L27)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These hacks with negative magic numbers in our public demos are so hacky...should we still reconsider the default padding @platosha ?
</blockquote></details>

Indeed. This is not directly related to this PR, though.

Exposing a mixin should help, as requested in #242 and #246.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-KcwKj3-Bkm2YA6m4Tdj:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[README.md, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-KcwFjR3EiXdnxnQwaMt:-Kcwe3IxuPfwSsC8zP2L:bihbk0g) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ec5d14ca675540baa9bfaefd118450f619f36418/README.md#L27)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Indeed. This is not directly related to this PR, though.

Exposing a mixin should help, as requested in #242 and #246.
</blockquote></details>

In theory yes, but since the items are outside the `vaadin-combo-box`'s scope, you can't target them with a mixin (unless you use it globally).

True, not related to this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400)*

**Comment by Saulis** [comment]
:lgtm: :shipit: after rebase and passing build

---

Reviewed 7 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/400#-:-Kd5yA_UoqX9tJRp1X5b:bidq6l2)*

**Pull request merged**
