### PR TITLE
fixes #170 - placeholder attribute needing to be exposed

### LINKED ISSUE #170: placeholder attribute not exposed
The `placeholder` attribute for the input is not exposed.

### PR DESCRIPTION
**Pull request by adamschnaare**
Simple inclusion of the placeholder attribute.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/171)

### CODE REVIEW

**Comment by adamschnaare** [comment]
I keep trying to sign this CLA agreement...and it keeps sending me right back here saying it isn't signed.

**Comment by Saulis** [comment]
I believe the commit you've pushed is either missing a author email or an email that isn't linked to your Github account - commit needs to be linked in order for the CLA assistant to recognise it

**Comment by jermsv1** [comment]
Hey Yall,

I'm looking at how i would also expose focusout / focus from to paper-input from vaadin combox. I can do them for booleans , but not sure how to do this?

-jeremy

**Comment by Saulis** [comment]
I'm closing the PR for now, the plan is to implement #198 to provide a way for customising the input with a placeholder attribute.

Feel free to reopen or comment if necessary.

**Comment by Saulis** [comment]
@jermsv1 if #198 doesn't work for you, please file a ticket or join our [Gitter chat](https://gitter.im/vaadin/vaadin-core-elements?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) so we can discuss your use cases.

**Pull request closed without merging**
