### PR TITLE
Let the combobox dropdown stay open when clear (x) button is pressed.

### LINKED ISSUE #523: Overlay should not close when clearing the field using the clear button
If the overlay was open when the user clears the field using the clear button, the overlay should not close.

Edit: I think we should actually open the overlay when the user clears the field using the button, if it was not open before (contrary to what I previously wrote).

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #523

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/563)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[test/keyboard.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KypbCB69vuSbCxA0fG5:-KypbCB7ZxbgJ2BMhoxO:b2otp50) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/30db24442c0a04a756e43795e0e0c7e5cb0b5daa/test/keyboard.html#L180)):*
> ```HTML
>       });
> 
>       // it('should clear the selection with enter when input is cleared', () => {
> ```

Why is this test removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
The requirement for the fix invalidated it and, the behaviour is the same with or without this fix. In that vein, the test scenario became a bottleneck.

**Comment by manolo** [comment]
> The requirement for the fix invalidated it and, the behaviour is the same with or without this fix. In that vein, the test scenario became a bottleneck.

@vicsstar are you answering @tomivirkki  question, if so, you should answer in reviewable not in github, so as we can follow the conversation

Anyways, if the test does not make sense anymore you need to remove it, and add a new one testing the fix. The test should fail if your fix is rolled back to the previous code.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-:-KytRqB2WQV46LFS0ouM:bfe8e9m)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 504 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KytdYNo7qijoTSTEjhR:-KytdYNo7qijoTSTEjhS:b-n7e1wm) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/69bed2a831e29e44b4dc370383f21ed079eab765/vaadin-combo-box-mixin.html#L504)):*
> ```HTML
>         this._inputElementValue = this._getItemLabel(this.selectedItem);
>       } else if (this._inputElementValue === '' || this._inputElementValue === undefined) {
>         this._clear();
> ```

Currently, when combobox is opened, I can clear text field and press enter to remove selection. You removed this behavior and the corresponding test.

So with your fix, when clearing text field and pressing enter, the previously selected value restores. This looks unrelated to the issue (which was about clear using button), isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
@manolo thanks for the tip.

There was no need to write a new test because the behaviour I sought to test already had an exact alternating test in the tests directory. So I just negated it. If my changes were rolled back as you said, my changes will fail as there was already a negating test.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-:-KytjIMi9rnKieqdPrpW:b8egy5a)*

**Comment by tomivirkki** [comment]
@vicsstar Please reply to the comment directly. There's a text field below it where you can post your reply.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-:-KytkR9SSrRFWwjb7Lzi:be1l0uw)*

**Comment by vicsstar** [comment]
*[test/keyboard.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KypbCB69vuSbCxA0fG5:-KytmlgewmFEcTZeBC33:b-4bhe5s) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/30db24442c0a04a756e43795e0e0c7e5cb0b5daa/test/keyboard.html#L180)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this test removed?
</blockquote></details>

The requirement for the fix invalidated it and, the behaviour is the same with or without this fix. In that vein, the test scenario became a bottleneck.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box-mixin.html, line 504 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KytdYNo7qijoTSTEjhR:-Kyu1aU2hwMkDZu6jCm-:bvy47cb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/69bed2a831e29e44b4dc370383f21ed079eab765/vaadin-combo-box-mixin.html#L504)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Currently, when combobox is opened, I can clear text field and press enter to remove selection. You removed this behavior and the corresponding test.

So with your fix, when clearing text field and pressing enter, the previously selected value restores. This looks unrelated to the issue (which was about clear using button), isn't it?
</blockquote></details>

Noted. Thanks @web-padawan 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box-mixin.html, line 504 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KytdYNo7qijoTSTEjhR:-Kyu1jJuEZJU1ucHmbdE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/69bed2a831e29e44b4dc370383f21ed079eab765/vaadin-combo-box-mixin.html#L504)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Noted. Thanks @web-padawan 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[test/keyboard.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KypbCB69vuSbCxA0fG5:-Kyu1ssdBt5h959x81eL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/30db24442c0a04a756e43795e0e0c7e5cb0b5daa/test/keyboard.html#L180)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

The requirement for the fix invalidated it and, the behaviour is the same with or without this fix. In that vein, the test scenario became a bottleneck.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 104 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyu2LmMCD7UbKL2o1f6:-Kyu2LmMCD7UbKL2o1f7:b-uvzlx6) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5dc19cf16a166207f4d3e90aec78dfbb117b54ab/vaadin-combo-box-mixin.html#L104)):*
> ```HTML
>          * A read-only property indicating whether this combo box has a value
>          * selected or not. It can be used for example in styling of the component.
>          * @private
> ```

This shouldn't have been removed. Please rebase to the current `master`.
You could also use soft reset and submit one single commit to keep your PR cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box-mixin.html, line 104 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyu2LmMCD7UbKL2o1f6:-KyuDyiX5YuMt-lRjv2N:bxpdptu) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5dc19cf16a166207f4d3e90aec78dfbb117b54ab/vaadin-combo-box-mixin.html#L104)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

This shouldn't have been removed. Please rebase to the current `master`.
You could also use soft reset and submit one single commit to keep your PR cleaner.
</blockquote></details>

Don't know how that change was made; focused on the issue at hand, that change was entirely unrelated and too specific that I have no knowledge of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box-mixin.html, line 104 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyu2LmMCD7UbKL2o1f6:-KyuFP_D3DHWJ-GvZxwK:b-2la0sv) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5dc19cf16a166207f4d3e90aec78dfbb117b54ab/vaadin-combo-box-mixin.html#L104)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Don't know how that change was made; focused on the issue at hand, that change was entirely unrelated and too specific that I have no knowledge of it.
</blockquote></details>

Visual Studio Code was the culprit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 205 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyuk8CBO3GBSwrEhcGX:-Kyuk8CBO3GBSwrEhcGY:b-47gz19) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e17f661b585b3959a29b733430ae48119f2062ec/vaadin-combo-box.html#L205)):*
> ```HTML
>              * Set to true to mark the input as required.
>              */
>             required: {
> ```

I'm sure these aren't supposed to be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box.html, line 205 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyuk8CBO3GBSwrEhcGX:-KyulQu79gwZDLav4Uqh:b3awy8l) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e17f661b585b3959a29b733430ae48119f2062ec/vaadin-combo-box.html#L205)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm sure these aren't supposed to be here?
</blockquote></details>

Not sure what's happening here. vaadin-combo-box-mixin.html, test/selecting-items.html and test/keyboard.html should be the only files affected by my changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by web-padawan** [comment]
Review status: 1 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box.html, line 205 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyuk8CBO3GBSwrEhcGX:-Kyuo8H3Cswjm3gVLtHU:b-vbd542) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e17f661b585b3959a29b733430ae48119f2062ec/vaadin-combo-box.html#L205)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Not sure what's happening here. vaadin-combo-box-mixin.html, test/selecting-items.html and test/keyboard.html should be the only files affected by my changes.
</blockquote></details>

The reason is that you have not properly rebased: `This branch is 2 commits ahead, 5 commits behind master.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by web-padawan** [comment]
Reviewed 2 of 11 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 504 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-KytdYNo7qijoTSTEjhR:-KyurXGIVjEYt3Y-GdhQ:b-8fx2u7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/69bed2a831e29e44b4dc370383f21ed079eab765/vaadin-combo-box-mixin.html#L504)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Comment by vicsstar** [comment]
*[vaadin-combo-box.html, line 205 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563#-Kyuk8CBO3GBSwrEhcGX:-KyuzK_Leqylr5EBvcs2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e17f661b585b3959a29b733430ae48119f2062ec/vaadin-combo-box.html#L205)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

The reason is that you have not properly rebased: `This branch is 2 commits ahead, 5 commits behind master.`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/563)*

**Pull request merged**
