### PR TITLE
Make combo-box 'modal' by adding iron-overlay-backdrop

### LINKED ISSUE #343: Make overlay modal
When the combo box overlay is open, the user expects that they can close it by clicking/tapping outside the overlay area. At the same time, they do not expect that click/tap to activate any controls under the pointer (like a button for example) – they just want to close the overlay.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #343

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/373)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KaaM3Zpw_742vgO7zHc:b4wvo8r) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
> ```JSON
>     "iron-input": "polymerelements/iron-input#^1.0.5",
>     "iron-list": "polymerelements/iron-list#^1.0.0",
>     "iron-overlay-behavior": "PolymerElements/iron-overlay-behavior#^1.0.0",
> ```

Could we just use a plain `div` as the backdrop instead? Or does the `iron-overlay-backdrop` have some features we benefit from? Would really like to avoid adding `iron-overlay-behavior` as a dependency here.

---

*[vaadin-combo-box.html, line 200 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaLu4CD4Xtz2aj7I35:-KaaLu4CD4Xtz2aj7I36:b-8j3ror) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/vaadin-combo-box.html#L200)):*
> ```HTML
>     </paper-input-container>
> 
>     <iron-overlay-backdrop id="backdrop" opened$=[[opened]]></iron-overlay-backdrop>
> ```

The backdrop element must be part of the overlay so that it wouldn't suffer from the same stacking context issues we're trying to avoid with the external overlay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KagbrLxvgtP4-Lws_Mc:b-uzm6hy) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Could we just use a plain `div` as the backdrop instead? Or does the `iron-overlay-backdrop` have some features we benefit from? Would really like to avoid adding `iron-overlay-behavior` as a dependency here.
</blockquote></details>

It seems to have more features than just a styled <div>. Reading sources the user can customise it via mixins, add annimation etc. Based on DRY principle, I would not implement anything right now, and I would do when we develop the vaadin-overlay sometime.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by tomivirkki** [comment]
*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KagdzXeZs4mBQY13Vw5:b-bzr7vb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It seems to have more features than just a styled <div>. Reading sources the user can customise it via mixins, add annimation etc. Based on DRY principle, I would not implement anything right now, and I would do when we develop the vaadin-overlay sometime.
</blockquote></details>

We don't need those features for anything so we wouldn't need to implement them either. The backdrop is always invisible in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KagiyoDkY3Y53ldQIyX:b-q3qkyw) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We don't need those features for anything so we wouldn't need to implement them either. The backdrop is always invisible in this case.
</blockquote></details>

Is backdrop a feature that we might want for vaadin-overlay ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by tomivirkki** [comment]
*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KagjlL6KU3YSb7HQdlY:bu1g7r) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is backdrop a feature that we might want for vaadin-overlay ?
</blockquote></details>

Yep, but even there we can just have our own `div` element for the purpose unless `iron-overla-backdrop` brings in some real value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bower.json, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373#-KaaM3Zpw_742vgO7zHb:-KakR-leozH1x-UVKV01:b-814g0e) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/938c0b32d12d0df2bf0d555abb13f627610d8488/bower.json#L28)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yep, but even there we can just have our own `div` element for the purpose unless `iron-overla-backdrop` brings in some real value.
</blockquote></details>

So, since the future vaadin-overlay would probably be split from this repo go ahead with it, please make the implementation simple and easily reusable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/373)*

**Comment by limonte** [comment]
Closed in favor of https://github.com/vaadin/vaadin-combo-box/pull/379/commits

**Pull request closed without merging**
