### PR TITLE
Switch from JSHint + JSCS to ESLint

### PR DESCRIPTION
**Pull request by limonte**
Related to: https://github.com/vaadin/vaadin-split-layout/pull/31

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/354)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[demo/common.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-KXynFURJgKrjGFtaAj2:-KXymzfTiU82wWZarqE8:b-ae0eo3) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55e0e687277a25137ae261ead319eb2019dabe03/demo/common.html#L61)):*
> ```HTML
>   
>   <script>
>     /* exported elements, elementsJson */
> ```

out of curiosity, is this comment needed? the annotation is a bit confusing to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354)*

**Comment by limonte** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[demo/common.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-KXynFURJgKrjGFtaAj2:-KXynhGOour1BigSZ9__:b-zfvflq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55e0e687277a25137ae261ead319eb2019dabe03/demo/common.html#L61)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

out of curiosity, is this comment needed? the annotation is a bit confusing to me.
</blockquote></details>

yes, without it ESLint will throw '<var> is defined but never used.'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354)*

**Comment by limonte** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[demo/common.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-KXynFURJgKrjGFtaAj2:-KXyntkDR6-p5q5W0yoq:b-f8czk0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55e0e687277a25137ae261ead319eb2019dabe03/demo/common.html#L61)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

yes, without it ESLint will throw '<var> is defined but never used.'
</blockquote></details>

C'mon Reviewable, you don't need to have so stupid comment parser. 

"var is defined but never used"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-:-KXyw2TDQvDlzs2-FWkn:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-:-KXywyBlHYBwUPNLAvOe:bnfp4nl)*

**Comment by samiheikki** [comment]
@limonte can you rebase?

**Comment by limonte** [comment]
rebased :+1:

---

Review status: 10 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354#-:-KXzvWpfSxv0TzvPvEOT:by4bb6n)*

**Comment by limonte** [comment]
I think that failing build is not related to this PR

**Comment by Saulis** [comment]
Reviewed 9 of 13 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/354)*

**Pull request merged**
