### PR TITLE
Overlay attached callback is invoked when it becomes visible after be…

### LINKED ISSUE #201: Dropdown isn't aligned properly when the focus is in the input field
Steps to reproduce:
1. Asynchronously request the data
2. Put the cursor into the input field
3. When data arrives, initialize `items` property, invoke `open()` method to open the dropdown.

Result - the dropdown is not rendered next to the input field, items in the list are not visible.

Here is a JSFiddle to reproduce: https://jsfiddle.net/2ttsyzd2/2/
Here is a short video demoing the issue: https://www.dropbox.com/s/sf8atgdyymfq48a/issue.mp4?dl=0

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixed #201

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/206)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEfamGqvMB9FWDyPnDe:937072249) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
I'd prefer to call `this.$.overlay_setPosition()` instead of `attachedCallback` here. Would it work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEfbZK599qWduwjrXfF:-2122160590) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
I recall it wasn't enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEfetj_JwdwKb7yyDQJ:-317736384) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
It's not. The iron-list shows up but empty. Apparently explicit call to attachedCallback "accidentally" fixes that issue also so let's keep it like this.

Tried to add a test case for this also but the issue doesn't reproduce in test environment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEjgzOdw1iK0iqX93YD:1111856602) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
I would like us to find the exact fix on that issue. `attachedCallback` call might trigger `attached` callbacks second time in the element tree, that could produce unwanted side-effects. I'll try to find a more specific workaround for iron-list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by platosha** [comment]
Aside from the attachedCallback thing discussion, I believe I found another issue with this PR. Please try these 3 steps to reproduce:
```javascript
combobox.items = [];
setTimeout(function() { combobox.open(); }, 100);
setTimeout(function() { combobox.items = [1, 2, 3]; }, 200);
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-:-KEl2mL4QThQUNuYuaX0:-1945461164)*

**Comment by tomivirkki** [comment]
:thumbsup: Fixed in the latest commit

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-:-KEl9eqi_wVRUvW-91c_:691005253)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEos6Ijk5tS4naagjAZ:1190744455) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
Would `this.$.overlay.notifyResize()` work?

I think what causes this issue is that we update the sizes while `iron-resize` is not dispatched, so `iron-list` does not update its internals for the new size. We can likely spy for `iron-resize` in tests to track future regressions of this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 564 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-KEfamGpPt6R1Rue4xAJ:-KEp12UrZZHdjPTC-OAc:-1636673154) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5e8c91b92f6be37584c7e7f790008788234ce3ae/vaadin-combo-box.html#L564)):*
Nice :thumbsup: This simplifies the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/206#-:-KEp4geruG1glWpvSd0f:1417088721)*

**Pull request merged**
