### PR TITLE
Adding online demo for the webcomponents.org site

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/322)

### CODE REVIEW

**Comment by Saulis** [comment]
We might have a small problem here: https://beta.webcomponents.org/preview/vaadin/vaadin-combo-box/4d2cfbed58a75a736085dda41b7aca16742cc24e?editing

Looks like the `<custom-element-demo>` encapsulates the overlay element...

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KU1ZVjaTGGJXVeRhsQJ:b-shf7ly)*

**Comment by platosha** [comment]
Oh, it’s inside an iframe. Let’s maybe add a <div> spacer with some height below the combo box to reserve space for the overlay?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KU1l-wt5jPx6Hl6gd1y:b-i62m1y)*

**Comment by manolo** [comment]
Added the spacer, preview availabe at : https://beta.webcomponents.org/preview/vaadin/vaadin-combo-box/cdba3f03a80f3de81c453cf6a663d5e740200f64 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KUvq1_3EIvC0LiYmCZi:b-de3rxr)*

**Comment by platosha** [comment]
Oh,

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 9 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-KUvyWJLTVWOZSd0Odu0:-KUvyWJLTVWOZSd0Odu1:bfl7zxq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/cdba3f03a80f3de81c453cf6a663d5e740200f64/README.md#L9)):*
Oh, just noticed [in the publish doc](https://beta.webcomponents.org/publish)

> Make sure your demo is responsive. Height is automatically determined, but if you need to explicitly define a minimum height you can set `height="400"` on `<custom-element-demo>`

Let us try, maybe?

BTW, I think we should not set explicit `width` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KUvyUz7gCEQEm9kj-ud:b2nhlim)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 9 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-KUvyWJLTVWOZSd0Odu0:-KUwXhBsjTDfp_XexZ15:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/cdba3f03a80f3de81c453cf6a663d5e740200f64/README.md#L9)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Oh, just noticed [in the publish doc](https://beta.webcomponents.org/publish)
> 
> > Make sure your demo is responsive. Height is automatically determined, but if you need to explicitly define a minimum height you can set `height="400"` on `<custom-element-demo>`
> 
> Let us try, maybe?
> 
> BTW, I think we should not set explicit `width` here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322)*

**Comment by platosha** [comment]
Needs rebase.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[README.md, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-KV-wzNzNyypWAM3Ormc:-KV-wzNzNyypWAM3Ormd:b-2bc1r5) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bf0735892e4a8751137ba492199f16ca1578b053/README.md#L13)):*
> ```Markdown
>     <script src="../webcomponentsjs/webcomponents-lite.js"></script>
>     <link rel="import" href="vaadin-combo-box.html">
>     <div>
> ```

Do we still need this `div` wrapper here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KV-x90AsBlnYgZhdwGg:bmsek6a)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-KV-wzNzNyypWAM3Ormc:-KV3iOmARwfoXjwiYckO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bf0735892e4a8751137ba492199f16ca1578b053/README.md#L13)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Do we still need this `div` wrapper here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/322#-:-KV46-W2Y9gXqoJWhiI5:bnfp4nl)*

**Pull request merged**
