### PR TITLE
Overlay should open when the input is cleared with a single stroke

### LINKED ISSUE #25: Overlay should open when the input is cleared with a single stroke
Given combo-box has a value of `bar`, and the overlay is closed, 

When the user selects `bar` and hits backspace to clear the input,

Then the overlay should open and all items should be displayed.

- Currently the overlay doesn't open.

### PR DESCRIPTION
**Pull request by cwayfinder**
Fixes #25 

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/29)

### CODE REVIEW

**Comment by tehapo** [comment]
Fixes #25

**Comment by tomivirkki** [comment]
The problem with this change occurs while opening the dropdown on desktop mode with native shadow dom enabled. Without the check for empty value open() gets called on init and some proportions are miscalculated. The result is the iron-list items overflowing from the right edge.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[test/filtering.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29#-K1c2zOGaG969Cjzrl0M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/2ed88447093befb6177b74c63b3848cee85c4383/test/filtering.html#L66)):</sup>
Could be called "should open the popup when input field is cleared"

- First we need to have a value selected `comboBox.value = 'foo'`
- Then make sure the comboBox is closed
- Next, `setInputValue('')` and assert that comboBox is open.


---

<sup>**[vaadin-combo-box.html, line 151 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29#-K1c3IfuB6iE2nIy1zQX)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/2ed88447093befb6177b74c63b3848cee85c4383/vaadin-combo-box.html#L151)):</sup>
There was a reason why we added the `this.$.input.bindValue !== ''` check here, but can't remember it 100%. Maybe @tomivirkki ?
I think it was at some point preventing the popup from opening immediately after being created? Anyways, all tests seem to pass so I guess it's OK to remove it now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by cwayfinder** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[test/filtering.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29#-K1c2zOGaG969Cjzrl0M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/2ed88447093befb6177b74c63b3848cee85c4383/test/filtering.html#L66)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by tomivirkki** [comment]
It still has the same issue with overflowing content https://www.dropbox.com/s/fbya3xtgggq874j/Screenshot%202015-10-27%2019.37.15.png?dl=0 Also, if you open the dropdown the first time after selecting an item, it has a height of a single row.
It's hard to reproduce in a test so unfortunately there's no test case for it.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by Saulis** [comment]
Hmm, I'm not getting either of these problems @tomivirkki ? 

I rebased the patch and did some small refactorings.


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by Saulis** [comment]
Rebased on origin/master


---

Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/29)

**Pull request merged**
