### PR TITLE
Enabled selecting an item from a static list (fixes #10)

### LINKED ISSUE #10: Enable selecting items from a static list
- Decided to use iron-selector temporarily for now.
- Return value is a string from the items array
- Selecting item will close popup
- Value can be selected like: `combobox.value = 'foobar'`
- Behavior for selecting an undefined value is undefined at this time.

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/13)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[test/index.html, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zlbs7QUelsEAHPjGu)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/test/index.html#L21)):</sup>
Add `selecting-items.html?dom=shadow`


---

<sup>**[test/selecting-items.html, line 36 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zkeX3pl7_8qvs8h8R)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/test/selecting-items.html#L36)):</sup>
I think this approach is OK, but just out of interest: was there a specific reason to use `input.bindValue` and `selector.selected` instead of for example first calling `open()` and then `click()` on the items? 

Just thinking how much we need to re-write tests after swapping the internals to a grid?


---

<sup>**[vaadin-combo-box.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmFM0R5BGpy6ELYP0)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L70)):</sup>
This isn't hooked to anything yet right? Is it here just for the demo?


---

<sup>**[vaadin-combo-box.html, line 85 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmL8aAvSUD5kpaXkj)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L85)):</sup>
Extra `,`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[vaadin-combo-box.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmFM0R5BGpy6ELYP0)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L70)):</sup>
I guess this should be bound to the `iron-selector` ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[test/index.html, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zlbs7QUelsEAHPjGu)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/test/index.html#L21)):</sup>
No point in testing this feature with shadow DOM as it doesn't affect data binding.


---

<sup>**[test/selecting-items.html, line 36 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zkeX3pl7_8qvs8h8R)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/test/selecting-items.html#L36)):</sup>
Opening the vaadin-combo-box (with open() and by clicking) is tested in toggling-dropdown.html. Selecting an item by clicking is tested in iron-selector component tests. We should focus on testing just the features that we've added (data bindings between different elements). To test the bindings in this case we don't even need to open the dropdown.


---

<sup>**[vaadin-combo-box.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmFM0R5BGpy6ELYP0)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L70)):</sup>
Well, the ticket had a task saying "Return value is a string from the items array" so I added the property even though it's still read-only. Also, the value property can have a value other than one in the items array but validating that isn't in the scope of the ticket ("Behavior for selecting an undefined value is undefined at this time.").


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Comment by tomivirkki** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 85 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmL8aAvSUD5kpaXkj)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L85)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13#-K0zmFM0R5BGpy6ELYP0)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/659d35751c54b9992491419a2efb42ef4015e265/vaadin-combo-box.html#L70)):</sup>
Removed the unused property


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/13)

**Pull request merged**
