### PR TITLE
Make `change` event to fire only on close and clear

### LINKED ISSUE #385: change event fired without user interaction
According to MDN documents

`The change event is fired for <input>, <select>, and <textarea> elements when a change to the element's value is committed by the user. Unlike the input event, the change event is not necessarily fired for each change to an element's value.`

The vaadin-combo-box implementation isn't following this contract as has been advertised. 

### Expected outcome
The event should only fire when value changes as result of a user gesture 

### Actual outcome
The event is fired when value changes programattically

### PR DESCRIPTION
**Pull request by platosha**
Fixes #385

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/416)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 412 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-KfCYukzq4tYcqgvMeGq:-KfCYukzq4tYcqgvMeGr:b23vsux) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/500e2056c602c829eba73bfca22ddf03d43e4784/vaadin-combo-box-behavior.html#L412)):*
> ```HTML
>       }
> 
>       this._dispatchChange();
> ```

Not sure how the code should be, but at first view I feel like dispatchChange only should be fired from methods that actually know whether the value was changed, calling always in _onClosed makes not sense to me. Just for thinking

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 412 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-KfCYukzq4tYcqgvMeGq:-KfH0fUsbk7GTajPSXrR:b-g14i5k) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/500e2056c602c829eba73bfca22ddf03d43e4784/vaadin-combo-box-behavior.html#L412)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Not sure how the code should be, but at first view I feel like dispatchChange only should be fired from methods that actually know whether the value was changed, calling always in _onClosed makes not sense to me. Just for thinking
</blockquote></details>

Maybe misnamed, but `_dispatchChange()` contains additional change detection. In case of cancelling the dropdown with <kbd>Esc</kbd>, the value does not change, `_dispatchChange()` detects that and does not dispatch.

Calling on close here helps to detect user action in more safe way then dispatching on `_valueChanged`, for example.

Renamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-behavior.html, line 527 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-Kff4-VS-A6-jrKxZ1Pn:-Kff4-VS-A6-jrKxZ1Po:bbr0l8u) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08ddceceee8b45677302152d1ee25d2ff6d3763a/vaadin-combo-box-behavior.html#L527)):*
> ```HTML
>       }
>       // In the next _detectAndDispatchChange() call, the change detection should pass
>       this._lastCommittedValue = undefined;
> ```

Closing after the value is changed programmatically will always fire `change`. For example the following test won't pass:
```
it('should not fire after value changed programmatically', function() {
  combobox.value = 'foo';

  var spy = sinon.spy();
  combobox.addEventListener('change', spy);

  combobox.open();
  combobox.close();

  expect(spy.callCount).to.equal(0);
});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 527 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-Kff4-VS-A6-jrKxZ1Pn:-Kff5PBCJUHk4vVcQ2XW:bz8vota) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08ddceceee8b45677302152d1ee25d2ff6d3763a/vaadin-combo-box-behavior.html#L527)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Closing after the value is changed programmatically will always fire `change`. For example the following test won't pass:
```
it('should not fire after value changed programmatically', function() {
  combobox.value = 'foo';

  var spy = sinon.spy();
  combobox.addEventListener('change', spy);

  combobox.open();
  combobox.close();

  expect(spy.callCount).to.equal(0);
});
```
</blockquote></details>

Intentional. We can not easily detect if the value change was done programmatically or by user.

Within this PR, when the dropdown closes, the value is assumed as committed by user, even if the value itself actually was set programmatically. I. e., the assumption is that close means user commits the value.

This will, obviously, dispatches false change if **close** is done programmatically. I suggest that we just accept this as a limitation for now, as non-user-introduced closing programmatically combined together with critical reliance on proper `change` is an edge case of edge cases. Let us assume that dropdown is always closed by user. A proper detection of whether closing is done indeed by user or programmatically would be complex once again, on par with user change detection itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 527 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-Kff4-VS-A6-jrKxZ1Pn:-KffJxU15cR4WbakiMuL:b3o586n) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08ddceceee8b45677302152d1ee25d2ff6d3763a/vaadin-combo-box-behavior.html#L527)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Intentional. We can not easily detect if the value change was done programmatically or by user.

Within this PR, when the dropdown closes, the value is assumed as committed by user, even if the value itself actually was set programmatically. I. e., the assumption is that close means user commits the value.

This will, obviously, dispatches false change if **close** is done programmatically. I suggest that we just accept this as a limitation for now, as non-user-introduced closing programmatically combined together with critical reliance on proper `change` is an edge case of edge cases. Let us assume that dropdown is always closed by user. A proper detection of whether closing is done indeed by user or programmatically would be complex once again, on par with user change detection itself.
</blockquote></details>

Changed as discussed. Now it considers only changes after opening, and does not dispatch if dropdown was cancelled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416#-:-KffMcTBaO9Wxbbo7uY1:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/416)*

**Pull request merged**
