### PR TITLE
Add focus and blur methods, focused property

### LINKED ISSUE #349: Make it possible to programmatically focus the vaadin-combo-box
It would be nice if you could add a `focus` function to the `vaadin-combo-box` to focus it programmatically.
For now im using `comboBoxElement.$.input.focus()` but it doesn't feels right to access the inner Element and with a `focus` function it would behave like a "normal" HTMLElement.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #349

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/398)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-KcayAodFqhCcwK9sawy:bnfp4nl)*

**Comment by manolo** [comment]
I miss the tabindex property that should have any form control. But after experimenting with it, I don't found a 100% working solution. So let's leave this for a separated PR because other elements also have the same problem.

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-KcazGtw5Gc7sMYtIVab:b-8xtz9e)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box.html, line 407 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-Kcb-KK_kkm3nuGDjptL:-Kcb-KK_kkm3nuGDjptM:b-faglkn) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/87ecbe6384943a96907eddca7ade9546ca975624/vaadin-combo-box.html#L407)):*
> ```HTML
>     },
> 
>     _onInputFocus: function() {
> ```

This isn't used

---

*[test/vaadin-combo-box-properties.html, line 209 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-Kcb-RBi0hErlH_poZkv:-Kcb-RBi0hErlH_poZkw:bth7csu) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/87ecbe6384943a96907eddca7ade9546ca975624/test/vaadin-combo-box-properties.html#L209)):*
> ```HTML
> 
>         it('should focus the input with focus method', function() {
>           var inputFocusCalled = false;
> ```

Unneeded variable. `sinon.stub` returns an object whose `called` property can be asserted. These could also be moved to `beforeEach` since they're used in 2 tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398)*

**Comment by Saulis** [comment]
I too think this should work with tabbing. Here's a prototype proposal that enables tabbing both in Shadow and Shady: https://jsfiddle.net/Saulis/8mj7xzfa/

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-Kcb6HPuacB7tLcZEidu:bydyu52)*

**Comment by manolo** [comment]
Smart solution @saulis, I added it to my tabindex conclusions here: 
https://github.com/vaadin/vaadin-button/blob/proto/native-button/tabindex-research.md

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-Kcq3ShU2PyaS_eVk5EU:b-sygk81)*

**Comment by platosha** [comment]
@saulis is it ok to add this in a separate PR?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 407 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-Kcb-KK_kkm3nuGDjptL:-KcrmN_ze1CokxOSjBOM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/87ecbe6384943a96907eddca7ade9546ca975624/vaadin-combo-box.html#L407)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This isn't used
</blockquote></details>

Done.

---

*[test/vaadin-combo-box-properties.html, line 209 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-Kcb-RBi0hErlH_poZkv:-KcrmRZTICltewWyOUZE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/87ecbe6384943a96907eddca7ade9546ca975624/test/vaadin-combo-box-properties.html#L209)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Unneeded variable. `sinon.stub` returns an object whose `called` property can be asserted. These could also be moved to `beforeEach` since they're used in 2 tests
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-KcrmUHJnJUsYcGpWTui:b-1igefn)*

**Comment by Saulis** [comment]
Yes I'm OK with that, I can add a separate ticket for it.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-KcvZ1xlhKn13j-PxwHA:b7835f4)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/398#-:-KcvguhqbPzqxOM9l4ZI:bnfp4nl)*

**Pull request merged**
