### PR TITLE
dropdown auto-align and auto-resize

### LINKED ISSUE #21: Use overlay sizing/alignment from <iron-dropdown>
See `<iron-dropdown>` demo:
https://elements.polymer-project.org/elements/iron-dropdown?view=demo:demo/index.html&active=iron-dropdown
https://github.com/PolymerElements/iron-dropdown/tree/master/demo

- `<vaadin-adaptive-overlay>` needs to figure out whether to align the overlay below or above the input depending on the viewport position.
- should automatically resize like in the iron-dropdown demo

### PR DESCRIPTION
**Pull request by manolo**
Fixes #21

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/37)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[vaadin-adaptive-overlay.html, line 129 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JY79CZDWa86kTyAQ)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L129)):</sup>
Leave out the condition and handle full-screen width the same way as height: add a css rule with 100vw


---

<sup>**[vaadin-adaptive-overlay.html, line 130 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JmCL32VbL7--tEaj)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L130)):</sup>
this.$.dropdown.sizingTarget.style.maxWidth = ... would be cleaner as the sizingTarget is a subject to change


---

<sup>**[vaadin-adaptive-overlay.html, line 133 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JQ4lcHH9SX3bHNqt)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L133)):</sup>
Works for me without this hack also


---

<sup>**[vaadin-adaptive-overlay.html, line 148 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26K33hcowHivkJITVU)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L148)):</sup>
We shouldn't add new listeners to window on every attach. Instead, add these on open and clean up on close


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[demo/index.html, line 118 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26Moy91J2Ovk0ZDFAK)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L118)):</sup>
Don't use generated values in css selectors. #demo_4 is an id generated by code-example / toc and a subject to change


---

<sup>**[demo/index.html, line 119 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26NQri7PuihRDkaASQ)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L119)):</sup>
indentation is a bit off


---

<sup>**[demo/index.html, line 122 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26N3OtilHTPq6rShfe)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L122)):</sup>
This selector doesn't work with shadow dom


---

<sup>**[demo/index.html, line 130 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26MZUGoSnPa6YiKZRM)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L130)):</sup>
This div variable isn't defined in "show full source" mode.


---

<sup>**[vaadin-adaptive-overlay.html, line 97 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26Ns6jLrbsgCUNkPcx)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L97)):</sup>
Lots of typos here


---

<sup>**[vaadin-adaptive-overlay.html, line 116 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26P1uG-D4wVPWTXm6d)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L116)):</sup>
This is no longer needed, works with the default value


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[vaadin-adaptive-overlay.html, line 137 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26PXJX48ise1w1MaUF)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L137)):</sup>
Missing semicolon at the end of this line.


---

<sup>**[vaadin-adaptive-overlay.html, line 181 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26PhqDKILe1Db1C-3k)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L181)):</sup>
Missing semicolon at the end of this line.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-adaptive-overlay.html, line 208 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26QS8wouq1U1V4smbk)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L208)):</sup>
"element.style.top = undefined" doesn't do anything. At least on Chrome the value remains the same even after assigning it to undefined.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 118 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26X1KaxElHQUwfTAEy)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-combo-box.html#L118)):</sup>
= this; works just as well. Best solution would however be to default the value in overlay to the domHost/host component so we wouldn't need to assign it explicitly


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by Saulis** [comment]
Reviewed 1 of 3 files at r4, 1 of 8 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[test/overlay-position.html, line 71 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26nlupd0bRpRx1oa7B)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L71)):</sup>
Left here by accident?


---

<sup>**[test/overlay-position.html, line 79 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26oDjkpbuFOFZnoO7t)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L79)):</sup>
`common.js` in master has a function called `asyncDone` which wraps the `Polymer.Base.async` call with a try-catch so that the assertion error is reported correctly.


---

<sup>**[test/overlay-position.html, line 90 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26olt0BMJdAWvvbzBS)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L90)):</sup>
Since all tests in this suite have similar setup steps, if would extract functions like `openOverlayTop` and `openOverlayBottom` which would reduce duplicate code.


---

<sup>**[test/overlay-position.html, line 136 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26myp4DbTqGA1hGoWr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L136)):</sup>
120 seconds? I'm pretty sure we want the test timeout faster than that? Isn't 10 seconds enough time to pass the test?


---

<sup>**[test/overlay-position.html, line 177 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26pEhjrouJToq84BDr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L177)):</sup>
Remove `console.log` 


---

<sup>**[vaadin-adaptive-overlay.html, line 195 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26paFUt5w_Os4PEyQB)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L195)):</sup>
Prefix function name with `_` ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[demo/index.html, line 118 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26Moy91J2Ovk0ZDFAK)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L118)):</sup>
Done.


---

<sup>**[demo/index.html, line 119 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26NQri7PuihRDkaASQ)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L119)):</sup>
Done.


---

<sup>**[demo/index.html, line 122 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26N3OtilHTPq6rShfe)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L122)):</sup>
Done.


---

<sup>**[demo/index.html, line 130 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26MZUGoSnPa6YiKZRM)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/demo/index.html#L130)):</sup>
Done.


---

<sup>**[test/overlay-position.html, line 79 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26oDjkpbuFOFZnoO7t)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L79)):</sup>
Done.


---

<sup>**[test/overlay-position.html, line 90 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26olt0BMJdAWvvbzBS)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L90)):</sup>
Done.


---

<sup>**[test/overlay-position.html, line 136 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26myp4DbTqGA1hGoWr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L136)):</sup>
left by mistake


---

<sup>**[test/overlay-position.html, line 177 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26pEhjrouJToq84BDr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L177)):</sup>
Done.


---

<sup>**[vaadin-adaptive-overlay.html, line 97 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26Ns6jLrbsgCUNkPcx)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L97)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 116 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26P1uG-D4wVPWTXm6d)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L116)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 130 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JmCL32VbL7--tEaj)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L130)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 133 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JQ4lcHH9SX3bHNqt)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L133)):</sup>
No it does not. When switching from bottom/top top/bottom resizing the window without this hack iron leave the old value for the other . Try with the last example and observe the border of the popup when resizing the window and the popup position switches


---

<sup>**[vaadin-adaptive-overlay.html, line 148 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26K33hcowHivkJITVU)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L148)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 208 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26QS8wouq1U1V4smbk)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L208)):</sup>
Done.


---

<sup>**[vaadin-adaptive-overlay.html, line 181 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26PhqDKILe1Db1C-3k)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L181)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 195 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26paFUt5w_Os4PEyQB)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L195)):</sup>
done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[test/overlay-position.html, line 71 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26nlupd0bRpRx1oa7B)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/test/overlay-position.html#L71)):</sup>
Done.


---

<sup>**[vaadin-adaptive-overlay.html, line 129 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JY79CZDWa86kTyAQ)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L129)):</sup>
Done.


---

<sup>**[vaadin-adaptive-overlay.html, line 137 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26PXJX48ise1w1MaUF)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L137)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
Review status: 2 of 8 files reviewed at latest revision, 23 unresolved discussions.

---

<sup>**[vaadin-adaptive-overlay.html, line 133 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26JQ4lcHH9SX3bHNqt)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L133)):</sup>
Ah, I see. The code for resetting top/bottom of the values is still in the wrong place here however. This function (_sizeDimension) only should update the dimensions of the sizingTarget, and even the if-block is meant for updating the width dimension.

More natural place for resetting the top and bottom values would be in _updateOverlayAlignment or even better, declaratively in CSS:

#dropdown[vertical-align='top'] {
  bottom: auto !important;
}
#dropdown[vertical-align='bottom'] {
  top: auto !important;
}


---

<sup>**[vaadin-adaptive-overlay.html, line 148 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26K33hcowHivkJITVU)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5de41fe35c6cdffdd68d8627b53a4df29cfdc809/vaadin-adaptive-overlay.html#L148)):</sup>
Doesn't clean up properly. Still getting calls to _updateOverlayAlignment on every single scroll event for every combo box even if the dropdowns are closed


---

<sup>**[vaadin-adaptive-overlay.html, line 33 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2BMsGrbugGkNMjfxAW)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/497d8750ecfd150c3e93a515b207dfbf0597d5a6/vaadin-adaptive-overlay.html#L33)):</sup>
Horizontal align isn't used anywhere


---

<sup>**[vaadin-adaptive-overlay.html, line 35 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2BMeuy7F_d0Rsk6jhz)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/497d8750ecfd150c3e93a515b207dfbf0597d5a6/vaadin-adaptive-overlay.html#L35)):</sup>
Unused id


---

<sup>**[vaadin-adaptive-overlay.html, line 213 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2BWUcigrQERuG3-XGH)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/497d8750ecfd150c3e93a515b207dfbf0597d5a6/vaadin-adaptive-overlay.html#L213)):</sup>
Is there really need for resetting the dropdown fit if it isn't even open? This shouldn't even work if the window scroll listener is cleaned up properly. Better option would be to reset fit on dropdown open.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by Saulis** [comment]
Reviewed 6 of 6 files at r11.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

<sup>**[vaadin-adaptive-overlay.html, line 162 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2C5tpE76jeBOQRXnZi)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/497d8750ecfd150c3e93a515b207dfbf0597d5a6/vaadin-adaptive-overlay.html#L162)):</sup>
`close` isn't called implicitly by the overlay, for example when clicking outside the overlay.

Could be better to place the listeners to `_opened` and `_closed` ?

Maybe it would also be beneficial to create tests that assert if the listeners are added and removed correctly?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Reviewed 1 of 3 files at r4, 1 of 8 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

<sup>**[vaadin-adaptive-overlay.html, line 181 \[r10\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K26PhqDKILe1Db1C-3k)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7351170eb698e35e24a5446a09efabc101ed41a2/vaadin-adaptive-overlay.html#L181)):</sup>
This semicolon is still missing. I was talking about the line 184 which ends the Polymer.Base.async call.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Reviewed 3 of 3 files at r8, 1 of 4 files at r9, 5 of 5 files at r12.
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

<sup>**[demo/index.html, line 95 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhaWVEJyXpVBjdIj9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L95)):</sup>
Typo – "it's" should be "its".


---

<sup>**[demo/index.html, line 96 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhfLtMX-Vk8zguCO7)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L96)):</sup>
Typo – "it's" should be "its".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

<sup>**[demo/index.html, line 95 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhaWVEJyXpVBjdIj9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L95)):</sup>
Ok, fixing. Note that this PR isn't in review yet.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

<sup>**[demo/index.html, line 95 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhaWVEJyXpVBjdIj9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L95)):</sup>
Oh, right. Sorry.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
Review status: 4 of 8 files reviewed at latest revision, 22 unresolved discussions.

---

<sup>**[demo/index.html, line 95 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhaWVEJyXpVBjdIj9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L95)):</sup>
done.


---

<sup>**[demo/index.html, line 96 \[r12\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2MhfLtMX-Vk8zguCO7)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/011e4f09e7ce4b9aa78b5bf95662dd2cea12240d/demo/index.html#L96)):</sup>
done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Reviewed 3 of 4 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

<sup>**[test/common.js, line 34 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftkMHpXWMAWFuDJlr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/test/common.js#L34)):</sup>
Missing semicolon.


---

<sup>**[test/common.js, line 36 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftm4ho_dFqQeJvzFY)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/test/common.js#L36)):</sup>
Missing semicolon.


---

<sup>**[vaadin-adaptive-overlay.html, line 139 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftrSU87C-G57G6fr9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/vaadin-adaptive-overlay.html#L139)):</sup>
Is this async needed? Seems to work also without it for me.


---

<sup>**[vaadin-adaptive-overlay.html, line 199 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2fX5uGPjugAZceVZrP)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/vaadin-adaptive-overlay.html#L199)):</sup>
Even if the free space is below the threshold, we should still check if there is more space below than above the component. Current code might lead to a weird situation where the dropdown is positioned on the side with less space available.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Also noticed a resizing issue with Firefox and iron-fit-behavior. Created an issue in their repository: https://github.com/PolymerElements/iron-fit-behavior/issues/26

**Comment by tomivirkki** [comment]
Review status: 6 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

<sup>**[test/common.js, line 34 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftkMHpXWMAWFuDJlr)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/test/common.js#L34)):</sup>
done


---

<sup>**[test/common.js, line 36 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftm4ho_dFqQeJvzFY)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/test/common.js#L36)):</sup>
done


---

<sup>**[vaadin-adaptive-overlay.html, line 139 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftrSU87C-G57G6fr9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/vaadin-adaptive-overlay.html#L139)):</sup>
I recall the tests failing without it but seems to be okay now. done


---

<sup>**[vaadin-adaptive-overlay.html, line 199 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2fX5uGPjugAZceVZrP)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/vaadin-adaptive-overlay.html#L199)):</sup>
done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tomivirkki** [comment]
Review status: 6 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

<sup>**[vaadin-adaptive-overlay.html, line 139 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37#-K2ftrSU87C-G57G6fr9)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/b4cba3b185b8bbc111863adc099787be56cde031/vaadin-adaptive-overlay.html#L139)):</sup>
Didn't work ok after all. Reverted the change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Comment by tehapo** [comment]
Reviewed 1 of 2 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/37)

**Pull request merged**
