### PR TITLE
Rewrite README.md and add LICENSE.md

### PR DESCRIPTION
**Pull request by tehapo**
Connects to vaadin/components-team-tasks#40

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/76)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-esxRXvhpsXZk4Thy:-K5-esxRXvhpsXZk4Thz:-1874429370) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L35)):*
You need to install `polyserve` globally to make it work as a command, don’t you? Like: `$ npm install -g polyserve`.

---

*[README.md, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-fQNe-4QxMndQXLZZ:-K5-fQNe-4QxMndQXLZ_:96630480) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L45)):*
You need to install `web-component-tester` globally to run `wct`, don't you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-esxRXvhpsXZk4Thy:-K5-vJEeX7WrBtDuMU4X:1346069318) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L35)):*
Comparing with `vaadin-grid` README, there's a prerequisite step for running `npm install -g bower gulp web-component-tester polyserve`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-esxRXvhpsXZk4Thy:-K5-wm3-8cf-sk3D4FMm:1275015777) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L35)):*
`npm install` runs `node_modules/.bin/bower install --allow-root`, as mentioned in package.json file. It uses locally installed bower, so no need to install list `bower` in a global install step here.

I see no reason for global `gulp` there as well. Both `polyserve` and `wct` do work without global `gulp`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by tehapo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-esxRXvhpsXZk4Thy:-K50ayIVpo4MrCusc_bM:1922496962) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L35)):*
You're right. Added `polyserve` installation to the instructions. No mandatory need to install `bower` or `gulp` as mentioned by @platosha.

---

*[README.md, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K5-fQNe-4QxMndQXLZZ:-K50bNpIrapqa1m3Gc3V:1241925918) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31ca326d347e60e38d6d55f6c76e25284d83bf8f/README.md#L45)):*
True. Added installation of `web-component-tester` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by platosha** [comment]
LGTM now

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-:-K50bi-clriZ7BzgYH7D:-1731633681)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 36 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K50bx13wU-JEWfy3Xes:-K50bx13wU-JEWfy3Xet:-714125220) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0138a426d7118f59484f8d25a8b9ae396bf3b020/README.md#L36)):*
Oh, btw, since we have more than one line here, it would make some sense to split this command on two lines as well. At least we don’n need to run `npm install` every time when we start `polyserve`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by tehapo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 36 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-K50bx13wU-JEWfy3Xes:-K50dGqetKhtOyRQmswK:357820584) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0138a426d7118f59484f8d25a8b9ae396bf3b020/README.md#L36)):*
Good idea. Separated this whole thing into two sections (dependencies, running the server).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Comment by tehapo** [comment]
Let's wait for any proofread corrections before merging this into master.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-:-K50vqHxK6haDWyYvHHX:1455525899)*

**Comment by Saulis** [comment]
One more thing, should we add some badges for e.g. latest bower version, supported browsers?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-:-K54TBd_BQMriceqj3x_:-2058732291)*

**Comment by tehapo** [comment]
Added a Bower badge and list of browsers we're currently running the tests on.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76#-:-K552GEff5tUnkhjAJMZ:699201495)*

**Comment by manolo** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/76)*

**Pull request merged**
