### PR TITLE
Restore focus-ring if firstly was focused with Tab

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to https://github.com/vaadin/components-team-tasks/issues/306

Restore `focus-ring` if component was firstly focused with <kbd>Tab</kbd>

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/599)

### CODE REVIEW

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-:-L2ZRnbFQdBhJyK4Yyyn:bnfp4nl)*

**Comment by vicsstar** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-combo-box-mixin.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-L2z0R7mFUPLBOOVN0oW:-L2z0R7mFUPLBOOVN0oX:b1ke15z) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3446ce20539cfa8dc256a2418ac1648be3ce0a6e/src/vaadin-combo-box-mixin.html#L256)):*
> ```HTML
>         }
>       } else if (this._openedWithFocusRing) {
>         this.focusElement.setAttribute('focus-ring', '');
> ```

What if the combo-box should loose focus when closing?

Steps to reproduce:

1. Focus a combo-box from keyboard, so that the focus ring appears
2. Open the combo-box
3. Close the combo-box by clicking outside the overlay
4. Bam, heres an issue: `focus-ring` is displayed and makes you think the combo-box is focused, while actually the document is focused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-:-L3laNNFRIhUk5WceXc3:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-:-L3m1ElN0tH_dsYvacYk:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-combo-box-mixin.html, line 256 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-L2z0R7mFUPLBOOVN0oW:-L3m9ZtTYFwvtj65WmrT:bb6ywmx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3446ce20539cfa8dc256a2418ac1648be3ce0a6e/src/vaadin-combo-box-mixin.html#L256)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

What if the combo-box should loose focus when closing?

Steps to reproduce:

1. Focus a combo-box from keyboard, so that the focus ring appears
2. Open the combo-box
3. Close the combo-box by clicking outside the overlay
4. Bam, heres an issue: `focus-ring` is displayed and makes you think the combo-box is focused, while actually the document is focused.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/599#-:-L3m9crN4oGvo3LEJAQJ:bnfp4nl)*

**Pull request merged**
