### PR TITLE
Fix selection of items in scrolling and long tap gestures

### PR DESCRIPTION
**Pull request by manolo**
Connected to #227 
Connected to #226

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/365)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-overlay.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-SqobsVKKd06wZbTV:-K_-SqobsVKKd06wZbTW:b-a45ght) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/vaadin-combo-box-overlay.html#L75)):*
> ```HTML
>     <vaadin-spinner active="[[loading]]"></vaadin-spinner>
>     <div id="scroller" scroller="[[_getScroller()]]"
>          on-tap="_stopPropagation"
> ```

+5 whitespace indent is weird, would prefer +4 here.

---

*[demo/common.html, line 185 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-UX4qe4VHGzLLi4DQ:-K_-UX4qe4VHGzLLi4DR:bhplb7f) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/demo/common.html#L185)):*
> ```HTML
> 
>     /* exported `elements` for demos */
>     var elements = [];
> ```

We can shorten this even more:

```javascript
var elements = elementsJson.map(function(e) {
  return e.name;
});
```

---

*[test/selecting-items.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-VKhn4aMwGPEOB66W:-K_-VKhoQCUrZD3SFxka:b-8mdw1j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L75)):*
> ```HTML
>       combobox.$.overlay.addEventListener('selection-changed', spy);
> 
>       combobox.$.overlay._onTouchStart();
> ```

Calling the event listener directly from the test leaves the event-to-listener binding untested. Instead, we should dispatch a touchstart event here.

---

*[test/selecting-items.html, line 92 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-Vo3c1N4k9RKLijYn:-K_-Vo3c1N4k9RKLijYo:bkhztae) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L92)):*
> ```HTML
>       combobox.$.overlay.addEventListener('selection-changed', spy);
> 
>       combobox.$.overlay._onTouchStart();
> ```

Once again, dispatch a touchstart event here.

---

*[test/selecting-items.html, line 114 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-WbWRPsxALo5_nEjg:-K_-WbWRPsxALo5_nEjh:bv6hk01) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L114)):*
> ```HTML
>       // open the combo box, and move the scroll
>       combobox.opened = true;
>       combobox.$.overlay.$.selector.scrollToIndex(20);
> ```

BTW We should probably dispatch some touchstart + touchmove + touchend events instead.

Since we’re fixing some touch interaction issue, it would be really nice to have the exact issue condition tested, not just any scroll, right?

---

*[test/selecting-items.html, line 134 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-XXUXe5pkSa-P4rFk:-K_-XXUXe5pkSa-P4rFl:b9w0cr2) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L134)):*
> ```HTML
> 
>       combobox.opened = true;
>       combobox.$.overlay.$.selector.scrollToIndex(20);
> ```

BTW Maybe touchstart + touchmove + touchend events instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by platosha** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-overlay.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-SqobsVKKd06wZbTV:-K_0pQndQNxtj85acWhn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/vaadin-combo-box-overlay.html#L75)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

+5 whitespace indent is weird, would prefer +4 here.
</blockquote></details>

Done.

---

*[demo/common.html, line 185 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-UX4qe4VHGzLLi4DQ:-K_0okmeKd5EZTb8Qxjb:b-t0d33s) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/demo/common.html#L185)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We can shorten this even more:

```javascript
var elements = elementsJson.map(function(e) {
  return e.name;
});
```
</blockquote></details>

sure, map is perfect for this.

---

*[test/selecting-items.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-VKhn4aMwGPEOB66W:-K_0pT1SG6Qt3oT6SnEJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L75)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Calling the event listener directly from the test leaves the event-to-listener binding untested. Instead, we should dispatch a touchstart event here.
</blockquote></details>

Done.

---

*[test/selecting-items.html, line 92 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-Vo3c1N4k9RKLijYn:-K_0pTiC-xB284SCtlS4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L92)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Once again, dispatch a touchstart event here.
</blockquote></details>

Done.

---

*[test/selecting-items.html, line 114 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-WbWRPsxALo5_nEjg:-K_0pVymNZEKeTkpz94c:bckcl89) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L114)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW We should probably dispatch some touchstart + touchmove + touchend events instead.

Since we’re fixing some touch interaction issue, it would be really nice to have the exact issue condition tested, not just any scroll, right?
</blockquote></details>

It seems that the three events do not move the scroll, apart from we need to add a lot of complexity to the test since we need some code to move the `touch` like we have in `mock-touch-interactions.js`

Since we are doing the fix when the scroll moves, I think scrollToIndex is enough because it test all the code, event the on-scroll annotation.

---

*[test/selecting-items.html, line 134 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_-XXUXe5pkSa-P4rFk:-K_0puhkUUAa3v4VUgYH:bb6xlm0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e41acd65550b217896794f8374e1fe44e4986364/test/selecting-items.html#L134)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Maybe touchstart + touchmove + touchend events instead.
</blockquote></details>

Idem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-:-K_473asNePvHeWt03uU:bnfp4nl)*

**Comment by platosha** [comment]
The build is failing due to missing `MockTouchInteractions`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-:-K_47G3Poo4T_BtbKcjo:bepfxqj)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by limonte** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 62 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_57fBX9ZGbIFogHGmu:-K_57fBX9ZGbIFogHGmv:b-r4cpyv) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L62)):*
> ```HTML
>   <script>
> 
>     /* exported `elementsJson` for demos */
> ```

I don't think this is the right syntax, "for demos" will probably break this statement. Ream more: http://eslint.org/docs/rules/no-unused-vars#exported

---

*[demo/common.html, line 63 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_58-8bePvCrkmVoH4I:-K_58-8bePvCrkmVoH4J:b-clhiv5) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L63)):*
> ```HTML
> 
>     /* exported `elementsJson` for demos */
>     window.elementsJson = [
> ```

No need to use `window.` if you make `exported` comment above right

---

*[demo/common.html, line 185 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_5870fihg7nOJ0caLB:-K_5870fihg7nOJ0caLC:b-fx6x36) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L185)):*
> ```HTML
> 
>     /* exported `elements` for demos */
>     window.elements = elementsJson.map(function(e) {
> ```

the same as previous comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by manolo** [comment]
@platosha now tests fail because the mock touch lib does not work with IE.

I have thought more about the convenience of firing real touch event to just execute the `_onTouchStart` method.
Actually, firing the event, we are not unit testing our code, but Polymer features. Polymer guarantees that the `on-touch-start=[[_onTouchStart]]` annotation works.
Additionally wanting to test polymer stuff, we need to maintain the mock touch utilities in our component.

---

Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 62 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_57fBX9ZGbIFogHGmu:-K_6aW6nAz8LfZZAGSiW:bz15bk8) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L62)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I don't think this is the right syntax, "for demos" will probably break this statement. Ream more: http://eslint.org/docs/rules/no-unused-vars#exported
</blockquote></details>

Well, I didn't realised that exported was there because of the lint rules, just a comment.

I'm not convinced that this is a convenient syntax, but anyway is what they have designed for the linter.

---

*[demo/common.html, line 63 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_58-8bePvCrkmVoH4I:-K_6bNsQqXWbulS1y-GT:b-gia4u1) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L63)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

No need to use `window.` if you make `exported` comment above right
</blockquote></details>

We want the variables in window in order to be used anywhere. I prefer the window syntax to stress that we want the variable in window, and not in the default scope which in this case is window precisely.

---

*[demo/common.html, line 185 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_5870fihg7nOJ0caLB:-K_6brfVIIbP8DrLwXvR:b-e1m9vo) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L185)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

the same as previous comment
</blockquote></details>

As said, I would remove comments and leave window.variable instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-:-K_6c3S_X2QWZAPsEYww:bn02tcm)*

**Comment by limonte** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 63 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_58-8bePvCrkmVoH4I:-K_8VY5MKxMMnogG8g2f:b-ywqs0c) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L63)):*
> We want the variables in window in order to be used anywhere.

I'm pretty sure that variables could be used anywhere without adding them to window scope. But it's up to you, I'm ok with both options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by manolo** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 63 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_58-8bePvCrkmVoH4I:-K_8_J5G7yOBusvRLCYs:b-2mp8v9) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L63)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> We want the variables in window in order to be used anywhere.

I'm pretty sure that variables could be used anywhere without adding them to window scope. But it's up to you, I'm ok with both options.
</blockquote></details>

I'm not following, `window.foo = `  is the same that `var foo = ` if you are in the `<script>` scope, so both are the same. Or am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by manolo** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 185 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_5870fihg7nOJ0caLB:-K_8_ig5CSHzDfPQidDS:b-j27699) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d6c268d17d4240d3af35d7883c65b3ac45f1d6dd/demo/common.html#L185)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

As said, I would remove comments and leave window.variable instead.
</blockquote></details>

Anyways, I left in your way with lint annotations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by limonte** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/index.html, line 14 at r6](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_A0GIpxwQsnK0uOY5_:-K_A0GIqdW6Itgi1mhtw:b-itgl8h) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a2f58ff8c57738e123a15d1b912f1284d4aabcbd/test/index.html#L14)):*
> ```HTML
>   <script>
>     WCT._config.environmentScripts.push('iron-test-helpers/mock-interactions.js');
>     WCT._config.environmentScripts.push('vaadin-combo-box/test/mock-touch-interactions.js');
> ```

    WCT._config.environmentScripts.push(location.href + 'mock-touch-interactions.js');

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by manolo** [comment]
Reviewed 1 of 5 files at r1, 4 of 6 files at r5, 4 of 4 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/index.html, line 14 at r6](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_A0GIpxwQsnK0uOY5_:-K_A23twN2VIH10jPa3s:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a2f58ff8c57738e123a15d1b912f1284d4aabcbd/test/index.html#L14)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

    WCT._config.environmentScripts.push(location.href + 'mock-touch-interactions.js');
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by limonte** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/index.html, line 14 at r6](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-K_A0GIpxwQsnK0uOY5_:-K_A7zdZRAwNGaWTZSMH:b-ub8qe1) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a2f58ff8c57738e123a15d1b912f1284d4aabcbd/test/index.html#L14)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I just tried it myself, it works locally but doesn't work in Travis :(

> 404 GET /components/vaadin-split-layout/test/index.htmlmock-touch-interactions.js
</blockquote></details>

regex, nice :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365#-:-K_AAEEL73zk9mYWUj9f:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/365)*

**Pull request merged**
