### PR TITLE
Ensure dropdown opens before applying new filter

### LINKED ISSUE #522: Can’t clear the value all at once using the keyboard
Steps to reproduce:

- Tab into field
- Press cmd+backspace or cmd+a & backspace (clear the input all at once)
- Tab out (blur the field)
- Previous value is selected again

combo-box-clear

If you clear the field with more input events than one (remove one character before removing the rest all at once), it doesn’t happen:

combo-box-clear2

### PR DESCRIPTION
**Pull request by platosha**
Fixes #522

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/538)

### CODE REVIEW

**Comment by tomivirkki** [comment]
The fix doesn't apply in "Custom Filtering" demo

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/538#-:-KursCJv5QFjmMosPwzB:b-bs9qq6)*

**Comment by platosha** [comment]
@tomivirkki good catch! Fixed.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/538#-:-Kus0morNF8IYWtaexnw:b-xigw23)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/538#-:-Kus2caHPBndVDh5zIYq:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/538#-:-Kus5e1ZVshhedHod4iq:bnfp4nl)*

**Pull request merged**
