### PR TITLE
Fix toggling overlay for combo-box-light

### LINKED ISSUE #380: Toggle button works like "show" button in combo-box-light
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/demo/advanced.html

Linux/Chrome:

recorded

### PR DESCRIPTION
**Pull request by limonte**
Fixes #380

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/387)

### CODE REVIEW

**Comment by manolo** [comment]
Any reason for not having a test demonstrating the issue and the fix ? 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-:-KbuIsOh9MyyNDFhx-F-:bhtf0uk)*

**Comment by limonte** [comment]
My bad, test is added

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-:-Kby3KrLPYCVfpV72MT-:bmrlwu)*

**Comment by tomivirkki** [comment]
*[test/vaadin-combo-box-light.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-Kby4h-s5blzylf_2vDh:-Kby4h-s5blzylf_2vDi:biyuqtz) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/6b28344f0f2fad93a4aca03ac9065bd8aa2ca6ca/test/vaadin-combo-box-light.html#L83)):*
> ```HTML
>       });
> 
>       it('should toggle overlay by tapping toggle element', function() {
> ```

The test should fail without the included changes. This test passes even on top of master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by tomivirkki** [comment]
*[test/vaadin-combo-box-light.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-Kby4h-s5blzylf_2vDh:-Kby5U8ozIV7ne1YJREI:b-hal2i0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/6b28344f0f2fad93a4aca03ac9065bd8aa2ca6ca/test/vaadin-combo-box-light.html#L83)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The test should fail without the included changes. This test passes even on top of master.
</blockquote></details>

You could instead fire a CustomEvent named 'down' for a toggle button and see that it gets cancelled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-combo-box-light.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-Kby4h-s5blzylf_2vDh:-KbyD3UUOe8ekAAJuPry:b-gr07wl) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/6b28344f0f2fad93a4aca03ac9065bd8aa2ca6ca/test/vaadin-combo-box-light.html#L83)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You could instead fire a CustomEvent named 'down' for a toggle button and see that it gets cancelled.
</blockquote></details>

Added another test below which is failing on master and passes with the fix from this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-combo-box-light.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-KbygAPgJkNgMfR92WKz:-KbygAPgJkNgMfR92WL-:b56z8xy) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5736556b4c4a82daba4b08d26f538f03aa94ecdd/test/vaadin-combo-box-light.html#L75)):*
> ```HTML
>     });
> 
>     describe('vaadin-combo-box-light-paper-input', function() {
> ```

Problem with this test is that they pass even removing the `_preventInputBlur` and `_restoreInputBlur` from  `vaadin-combo-box.html` . 

I'm wondering how many tests could be with the same issue since we are repeating code in both components, and sometime testing one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-combo-box-light.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-KbygAPgJkNgMfR92WKz:-KbyjUMk91xGtP2ULwZa:b-tjhotk) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5736556b4c4a82daba4b08d26f538f03aa94ecdd/test/vaadin-combo-box-light.html#L75)):*
> Problem with this test is that they pass even removing the _preventInputBlur and _restoreInputBlur from vaadin-combo-box.html .

These two tests are related to `vaadin-combo-box-light`, not `vaadin-combo-box`.

> I'm wondering how many tests could be with the same issue since we are repeating code in both components, and sometimes testing one.

I have no idea. I did some monkey-clicking on both normal and light combo-box, looks working. But we should definitely keep in mind both elements when writing tests/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-:-KbylgyxYC5eKSOL6lRm:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-combo-box-light.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-KbygAPgJkNgMfR92WKz:-Kc-9SDXiBtuoVCoWC5V:b-had6ss) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5736556b4c4a82daba4b08d26f538f03aa94ecdd/test/vaadin-combo-box-light.html#L75)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> Problem with this test is that they pass even removing the _preventInputBlur and _restoreInputBlur from vaadin-combo-box.html .

These two tests are related to `vaadin-combo-box-light`, not `vaadin-combo-box`.

> I'm wondering how many tests could be with the same issue since we are repeating code in both components, and sometimes testing one.

I have no idea. I did some monkey-clicking on both normal and light combo-box, looks working. But we should definitely keep in mind both elements when writing tests/
</blockquote></details>

But this PR also introduces a couple of lines in normal combo-box. Those are what I meant is not tested.

Obviously these tests demonstrates that the solution works, and must work in normal combo box as well.

Not a blocker, but something that should take in account when testing this component.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/387#-:-Kc-ALJaEFCCrM6RKhXn:bnfp4nl)*

**Pull request merged**
