### PR TITLE
Convert to pure Polymer2 ES6

### PR DESCRIPTION
**Pull request by manolo**
Connected to #449

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/461)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-dropdown.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KlxQDcju0m4eEZRAYfr:-KlxQDcju0m4eEZRAYfs:bt00dm9) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-dropdown.html#L31)):*
> ```HTML
>      * @memberof Vaadin
>      */
>     class DropdownElement extends Polymer.mixinBehaviors(Polymer.IronResizableBehavior, Polymer.Element) {
> ```

Would it make sense if the dropdown extended overlay? It's basically the same thing with some extra features. The additional Element/shadow root in between feels kind of unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by tomivirkki** [comment]
Just pushed a prototype with the structure and responsibilities of `<vaadin-combo-box>`/`<vaadin-overlay>` changed a bit: https://github.com/vaadin/vaadin-combo-box/tree/new-structure

In the prototype `<vaadin-dropdown>` is responsible of the overlay's positioning and sizing (in boundaries set by the `positionTarget` property, viewport and properties provided by the client such as '--vaadin-dropdown-max-height'). IMO sizing of the overlay isn't `<vaadin-combo-box>`'s, but the dropdown's responsibility and since the dropdown is intended to be re-usable, the feature should ship with it.

In the prototype `<vaadin-dropdown>` also extends (instead of wraps) the `<vaadin-overlay>` because it's basically the same thing with some additional features (this is debatable). This also provides clients access to the overlay's APIs directly.

Properties needed by the `<vaadin-dropdown>` (`opened`, `positionTarget`) are also no longer transferred to it trough the `<vaadin-combo-box-overlay>` element, which (while confusingly named) only represents the content for the dropdown.

I think the suggested structure streamlines the use of and decouples the pieces even further. The structure is also more in line with that of [`<vaadin-date-picker>`](https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L82)s. WDYT?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-Kly-ffb_AFMX35f3dZF:b-400hyj)*

**Comment by Saulis** [comment]
Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KlxQDcju0m4eEZRAYfr:-Km0B6-AAFoCt8LrjeSl:bwwnlam) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-dropdown.html#L31)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would it make sense if the dropdown extended overlay? It's basically the same thing with some extra features. The additional Element/shadow root in between feels kind of unnecessary.
</blockquote></details>

Hmm... I'm thinking if `_getOffsetParent` works correctly if this is the element which jumps between body and original position, but since it is called for the `positionTarget` element I think it could work. 

One consideration though: if we ever decide to create an API where the `positionTarget` is set as an child of `vaadin-dropdown` we need to revert back to having a separate component – but that shouldn't be a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by tomivirkki** [comment]
*[vaadin-dropdown.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KlxQDcju0m4eEZRAYfr:-Km0C_9Wy-4_eNiJdhOs:bukgqav) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-dropdown.html#L31)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Hmm... I'm thinking if `_getOffsetParent` works correctly if this is the element which jumps between body and original position, but since it is called for the `positionTarget` element I think it could work. 

One consideration though: if we ever decide to create an API where the `positionTarget` is set as an child of `vaadin-dropdown` we need to revert back to having a separate component – but that shouldn't be a problem.
</blockquote></details>

Not 100% sure about combining these. It might make logically more sense that the dropdown stays in place and only the overlay "teleports".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by Saulis** [comment]
Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KlxQDcju0m4eEZRAYfr:-Km18l-1iFScWcK4IosC:btugor0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-dropdown.html#L31)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not 100% sure about combining these. It might make logically more sense that the dropdown stays in place and only the overlay "teleports".
</blockquote></details>

Agreed :+1+:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by platosha** [comment]
Just saying. Even after changing all the `function` expressions to arrow functions, the ES6 conversion feels still incomplete if we don’t drop all the `var` statements as well. I don’t really get why we do the first step, but not the second here.

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[bower.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1YFg2QqHXiL4eMgSN:-Km1YFg2QqHXiL4eMgSO:b-z9nbjy) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31efd8b4c6987315b4eeac3378173b9a2af534c7/bower.json#L24)):*
> ```JSON
>     "iron-a11y-announcer": "^2.0.0",
>     "iron-flex-layout": "^2.0.0",
>     "iron-form": "2.0-preview",
> ```

Now that i’m looking here, `<iron-form>` is only used in demos and tests. Should be a `devDependency`.

---

*[bower.json, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1Y-PlGGg2Oc9TiSlI:-Km1Y-PlGGg2Oc9TiSlJ:bm01h4d) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31efd8b4c6987315b4eeac3378173b9a2af534c7/bower.json#L25)):*
> ```JSON
>     "iron-flex-layout": "^2.0.0",
>     "iron-form": "2.0-preview",
>     "iron-form-element-behavior": "^2.0.0",
> ```

Dropping iron-form-element-behavior without a replacement? This means we are missing the iron-form compatibility feature, right? Or what is going on?

---

*[index.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1UdztYmA8z7tpyR8J:-Km1UdztYmA8z7tpyR8K:bmgr7f7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/index.html#L15)):*
> ```HTML
> 
> <body>
>   <api-doc-viewer url="documentation.json" element-class-name="Vaadin.ComboBoxElement"></api-doc-viewer>
> ```

Missing API docs for`<vaadin-combo-box-light>` and navigation.

---

*[vaadin-combo-box-light.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1WBMhRCrtdA3nh32b:-Km1WBMhRCrtdA3nh32c:by6ognd) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-light.html#L40)):*
> ```HTML
> 
> <link rel="import" href="../polymer/polymer-element.html">
> <link rel="import" href="../polymer/lib/mixins/gesture-event-listeners.html">
> ```

This is too low for the imports.

Duplicate import of `gesture-event-listeners.html`

---

*[vaadin-combo-box-mixin.html, line 317 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1ZBdpU6WeuLJJCucA:-Km1ZBdpU6WeuLJJCucB:b-e97r82) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L317)):*
> ```HTML
>         this._inputElementValue = '';
>         // 1ms delay needed for OSX VoiceOver to realise input value was reset
>         Polymer.Async.timeOut.after(1).run(() => {
> ```

BTW Too long way of saying `setTimeout(() => { ... }, 1)`.

Thanks to ES6, arrow functions are bound out-of-the-box. No need to bind the callback here, no need to use Polymer’s bound .async tricks then, plain platform APIs can be used from now on.

---

*[vaadin-combo-box-mixin.html, line 362 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1ZYNioVm8LpTwKbo1:-Km1ZYNioVm8LpTwKbo2:b-rnx0e) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L362)):*
> ```HTML
>       // Needed for MS Edge. Otherwise, it does not pop the virtual keyboard up
>       // when tapping the combobox that has non-empty value.
>       Polymer.Async.microTask.run(() => this.open());
> ```

BTW Maybe also `setTimeout`

---

*[vaadin-combo-box-mixin.html, line 419 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1_ZaSdOzjoayom4RN:-Km1_ZaSdOzjoayom4RO:b-rnx0e) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L419)):*
> ```HTML
>       this.$.overlay.updateViewportBoundaries();
>       Polymer.Async.microTask.run(() => this.$.overlay.adjustScrollPosition());
>       Polymer.Async.timeOut.after(1).run(() => this.$.overlay.$.dropdown.notifyResize());
> ```

BTW Maybe also `setTimeout`

---

*[vaadin-combo-box-mixin.html, line 623 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1_tJRfUFznQ2IiqjB:-Km1_tJRfUFznQ2IiqjC:bskywov) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L623)):*
> ```HTML
>         // async needed to reposition correctly after filtering
>         // (especially when aligned on top of input)
>         Polymer.Async.timeOut.after(1).run(() => {
> ```

BTW `setTimeout` should work

---

*[vaadin-combo-box-overlay.html, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1aW6MB7UcOfSEjPHg:-Km1aW6MB7UcOfSEjPHh:bjrrvxx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L41)):*
> ```HTML
>               border-top: 8px solid transparent;
>               border-bottom: 8px solid transparent;
>             }
> ```

Accidental linebreak?

---

*[vaadin-combo-box-overlay.html, line 269 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bO4ULgO9qQM1ZV00:-Km1bO4ULgO9qQM1ZV01:be8g3ku) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L269)):*
> ```HTML
>       _onTouchStart() {
>         this._notTapping = false;
>         Polymer.Async.timeOut.after(300).run(() => this._notTapping = true);
> ```

BTW `setTimeout`?

---

*[vaadin-combo-box-overlay.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bQlMFgnSLH52nCwM:-Km1bQlMFgnSLH52nCwN:be8g3ku) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L275)):*
> ```HTML
>         this._ignoreTaps = true;
>         this._restoreTaps = Polymer.Debouncer.debounce(this._restoreTaps,
>           Polymer.Async.timeOut.after(300), () => this._ignoreTaps = false);
> ```

BTW `setTimeout`?

---

*[vaadin-combo-box.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bkVDqu-nidSOREAb:-Km1bkVDqu-nidSOREAc:bwmjltb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box.html#L19)):*
> ```HTML
> <link rel="import" href="vaadin-combo-box-icons.html">
> 
> <dom-module id="vaadin-combo-box">
> ```

Duplicate `<dom-module>`

---

*[test/filtering.html, line 219 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1cGBBawu25SWLReU7:-Km1cGBBawu25SWLReU8:b-vpeuya) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/test/filtering.html#L219)):*
> ```HTML
>     });
> 
>     describe('external filtering', done => {
> ```

`done` in describe block? Why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-Km1dAeBtogz08NxjuBY:b-8xc5h)*

**Comment by manolo** [comment]
Preparing a commit with var replacements

---

Review status: 25 of 35 files reviewed at latest revision, 15 unresolved discussions.

---

*[bower.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1YFg2QqHXiL4eMgSN:-Km1tX_NXdi6Rd96Jk8k:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31efd8b4c6987315b4eeac3378173b9a2af534c7/bower.json#L24)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Now that i’m looking here, `<iron-form>` is only used in demos and tests. Should be a `devDependency`.
</blockquote></details>

Done.

---

*[bower.json, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1Y-PlGGg2Oc9TiSlI:-Km1sXLPiJ9IeyVC_DNS:b-x3evv7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31efd8b4c6987315b4eeac3378173b9a2af534c7/bower.json#L25)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Dropping iron-form-element-behavior without a replacement? This means we are missing the iron-form compatibility feature, right? Or what is going on?
</blockquote></details>

The iron-form-element only adds a couple of properties in P2 (name required value), I added those properties to the combo-box mixin like we did in date-picker so as we don't depend on a trivial behavior. 

---

*[index.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1UdztYmA8z7tpyR8J:-Km1tgEPlLDJ_FWduSmy:bvevav1) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/index.html#L15)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Missing API docs for`<vaadin-combo-box-light>` and navigation.
</blockquote></details>

does the api-doc-viewer support multi-element navigation? seems that elemen-class-name is not plural

---

*[vaadin-combo-box-light.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1WBMhRCrtdA3nh32b:-Km1uLL8WYDbgJ4kES53:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-light.html#L40)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This is too low for the imports.

Duplicate import of `gesture-event-listeners.html`
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 317 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1ZBdpU6WeuLJJCucA:-Km1uT5Y2lT6384qyYYA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L317)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Too long way of saying `setTimeout(() => { ... }, 1)`.

Thanks to ES6, arrow functions are bound out-of-the-box. No need to bind the callback here, no need to use Polymer’s bound .async tricks then, plain platform APIs can be used from now on.
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 362 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1ZYNioVm8LpTwKbo1:-Km1vA9mjOngzswwbl6R:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L362)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Maybe also `setTimeout`
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 419 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1_ZaSdOzjoayom4RN:-Km1vKHvjw9qgtZmo4nq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L419)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Maybe also `setTimeout`
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 623 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1_tJRfUFznQ2IiqjB:-Km1vKl7Z_TIPdrfAd0M:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-mixin.html#L623)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW `setTimeout` should work
</blockquote></details>

Done.

---

*[vaadin-combo-box-overlay.html, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1aW6MB7UcOfSEjPHg:-Km1vwR7Xaim5oDR2DCC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L41)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Accidental linebreak?
</blockquote></details>

Done.

---

*[vaadin-combo-box-overlay.html, line 269 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bO4ULgO9qQM1ZV00:-Km1wG7VbieNDAazf-rv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L269)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW `setTimeout`?
</blockquote></details>

Done.

---

*[vaadin-combo-box-overlay.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bQlMFgnSLH52nCwM:-Km1wH82eDOzAEgbAGS9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L275)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW `setTimeout`?
</blockquote></details>

Done.

---

*[vaadin-combo-box.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bkVDqu-nidSOREAb:-Km1w06WplbdfJZwQDsT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box.html#L19)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Duplicate `<dom-module>`
</blockquote></details>

Done.

---

*[test/filtering.html, line 219 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1cGBBawu25SWLReU7:-Km1w9n78ushlecL6i9g:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/test/filtering.html#L219)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`done` in describe block? Why?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-Km1sQ3VVNFtLUTSGJoS:b-eb5m2d)*

**Comment by manolo** [comment]
replaced all var occurrences  with the equivalent let/const keyword

---

Review status: 13 of 35 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-Km22eWe4TmUF5Jw9SBc:b9m01f0)*

**Comment by manolo** [comment]
Review status: 11 of 35 files reviewed at latest revision, 8 unresolved discussions.

---

*[index.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1UdztYmA8z7tpyR8J:-Km29VES5cR79pwze-mH:b-jd0jp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/index.html#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

does the api-doc-viewer support multi-element navigation? seems that elemen-class-name is not plural
</blockquote></details>

Ok, added the same approach than in form-layout.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by tomivirkki** [comment]
Reviewed 16 of 36 files at r1, 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1Y-PlGGg2Oc9TiSlI:-Km5lKBXvsNuejh2y2Z4:b32w0x) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/31efd8b4c6987315b4eeac3378173b9a2af534c7/bower.json#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The iron-form-element only adds a couple of properties in P2 (name required value), I added those properties to the combo-box mixin like we did in date-picker so as we don't depend on a trivial behavior. 
</blockquote></details>

OK

---

*[vaadin-combo-box-overlay.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bQlMFgnSLH52nCwM:-Km5oAKZCO8X9nB26sZA:bfhqml6) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L275)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by manolo** [comment]
Review status: 34 of 35 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-combo-box-overlay.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bQlMFgnSLH52nCwM:-Km6QgArt5_zS5y4sjjm:b-d846zh) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L275)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Obviously,  it cannot be done here. We need an async-module (returned in the after call) for the P2 debounce api. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 361 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmAL832NAPYFh3bFBp3:-KmAL833FVypmuMnOX8c:b-6k290m) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/47da50c5b12c7a98d3cddcf5057317ece872dd24/vaadin-combo-box-mixin.html#L361)):*
> ```HTML
>       // Needed for MS Edge. Otherwise, it does not pop the virtual keyboard up
>       // when tapping the combobox that has non-empty value.
>       setTimeout(() => this.open());
> ```

This should be `Polymer.Async.microTask.run(() => this.open());`

---

*[vaadin-combo-box-mixin.html, line 417 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALFL2u5l4Fi3hOZ2d:-KmALFL2u5l4Fi3hOZ2e:b-1qxg3t) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/47da50c5b12c7a98d3cddcf5057317ece872dd24/vaadin-combo-box-mixin.html#L417)):*
> ```HTML
>       // Ensure metrics are up-to-date
>       this.$.overlay.updateViewportBoundaries();
>       setTimeout(() => this.$.overlay.adjustScrollPosition());
> ```

this should be `Polymer.Async.microTask.run(() => this.$.overlay.adjustScrollPosition());`

---

*[vaadin-combo-box-mixin.html, line 623 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALQjYh_daYWBgy_Hb:-KmALQjYh_daYWBgy_Hc:bnqb1x8) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/47da50c5b12c7a98d3cddcf5057317ece872dd24/vaadin-combo-box-mixin.html#L623)):*
> ```HTML
>         // async needed to reposition correctly after filtering
>         // (especially when aligned on top of input)
>         Polymer.Async.timeOut.after(1).run(() => {
> ```

This should be `setTimeout(..., 1)`

---

*[test/aria.html, line 94 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALvnf8oIF1v96Ccsd:-KmALvnf8oIF1v96Ccse:b261e5c) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/47da50c5b12c7a98d3cddcf5057317ece872dd24/test/aria.html#L94)):*
> ```HTML
>       // functions are still partly running.
>       // Delaying the teardown by a micro task seems to help.
>       afterEach(done => setTimeout(done));
> ```

this should be `Polymer.Async.microTask.run(done)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-overlay.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-Km1bQlMFgnSLH52nCwM:-KmBgyIms7uFgOdo5myO:b-2nvh0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/284031aa0dc0569ec89a73c9e823083b8cafe1f8/vaadin-combo-box-overlay.html#L275)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Obviously,  it cannot be done here. We need an async-module (returned in the after call) for the P2 debounce api. 
</blockquote></details>

OK Ah, right. Sorry, my bad here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by platosha** [comment]
Reviewed 1 of 36 files at r1, 21 of 24 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by tomivirkki** [comment]
Ping @manolo (unanswered questions here)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-KmCCAJ1bttsqrSRTks9:b-q7265p)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 361 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmAL832NAPYFh3bFBp3:-KmQPHcNsqmFlHuPaJzR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3b40f82107079225589b0a84f69f55686d70b3c6/vaadin-combo-box-mixin.html#L361)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This should be `Polymer.Async.microTask.run(() => this.open());`
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 417 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALFL2u5l4Fi3hOZ2d:-KmQPI1BERCdka7vCrbR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3b40f82107079225589b0a84f69f55686d70b3c6/vaadin-combo-box-mixin.html#L417)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

this should be `Polymer.Async.microTask.run(() => this.$.overlay.adjustScrollPosition());`
</blockquote></details>

Done.

---

*[vaadin-combo-box-mixin.html, line 623 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALQjYh_daYWBgy_Hb:-KmQPPVCKdhNJOovpJ3z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3b40f82107079225589b0a84f69f55686d70b3c6/vaadin-combo-box-mixin.html#L623)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This should be `setTimeout(..., 1)`
</blockquote></details>

Done.

---

*[test/aria.html, line 94 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-KmALvnf8oIF1v96Ccsd:-KmQPnyBTQqTms7G1UDz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3b40f82107079225589b0a84f69f55686d70b3c6/test/aria.html#L94)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

this should be `Polymer.Async.microTask.run(done)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 12 of 36 files at r1, 19 of 24 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-KmRtHSYGRcn0I73icrc:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 36 files at r1, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/461#-:-KmVN0enXzhM--rhW41h:bnfp4nl)*

**Pull request merged**
