### PR TITLE
webcomponents-lite.js -> webcomponents-lite.min.js

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/348)

### CODE REVIEW

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/348#-:-KXLYLm3IrRvnP03sSOU:bnfp4nl)*

**Comment by samiheikki** [comment]
Wait, there is this also: https://github.com/vaadin/vaadin-combo-box/blob/master/test/index.html#L14

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/348#-:-KXLZCUQaVBHrdZhVEj5:b-cll75f)*

**Comment by limonte** [comment]
`test/index.html#L14` is for `test` environment, not for demo.  Demo env should be optimized, test should be debuggable :) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/348#-:-KXL_cFG7L8xvdNjtug8:bruazpk)*

**Comment by samiheikki** [comment]
Excellent point! :shipit: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/348#-:-KXLaBmQwVaVefkfDq2j:bs8qzlz)*

**Pull request merged**
