### PR TITLE
Style tag needs to live inside the template. Fixes #361

### LINKED ISSUE #361: Leaking input styles
### Description
The `vaadin-combo-box` element styles affect globals scope when using bundling.
All my inputs have padding due to the following lines: 

```
    #input {
      box-sizing: border-box;
      padding-right: 28px;
    }
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #361

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/362)

### CODE REVIEW

**Comment by web-padawan** [comment]
I signed the CLA.

**Comment by limonte** [comment]
You're not actually :) Most probably it's because you've used two accounts: @web-padawan for creating th PR and another one @s-kulikov for the commit.

**Comment by web-padawan** [comment]
Thanks @limonte ! Updated this PR.

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/362#-:-KZQZ13EfYocoDFB3v5T:bnfp4nl)*

**Pull request merged**
