### PR TITLE
Remove hack with handling 'up' event instead of 'click'

### LINKED ISSUE #503: Combo-box is opening while scrolling on mobile
Expected result

The combo box is not opening when the page is scrolling on mobile.

Actual result

The combo box is opening (by tapping it) even when the page is scrolling on mobile.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #503 

- remove hack with handling the `up` event instead of `click`, https://github.com/Polymer/polymer/issues/4670 is fixed
- bump npm deps, replace `yarn` with `npm5`
- fix linter errors
- re-enable latest ipad/iphone tests in SauceLabs
- remove `Polymer.GestureEventListeners` mixin from `Vaadin.ComboBoxMixin`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/507)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-mixin.html, line 203 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507#-KsgobtvdJjHe1LboXSi:-KsgobtvdJjHe1LboXSj:b-y10jpp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c87fe35d6489852dd907077feff775fb6e2e8664/vaadin-combo-box-mixin.html#L203)):*
> ```HTML
>       this.addEventListener('keydown', this._onKeyDown.bind(this));
> 
>       this._addEventListenerToNode(this, 'click', this._onClick.bind(this));
> ```

`_addEventListenerToNode` is for gesture events. Native `addEventListener` should be used for `click`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-mixin.html, line 203 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507#-KsgobtvdJjHe1LboXSi:-Ksgxuo744OmHRuelCn0:b-opfte0) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c87fe35d6489852dd907077feff775fb6e2e8664/vaadin-combo-box-mixin.html#L203)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`_addEventListenerToNode` is for gesture events. Native `addEventListener` should be used for `click`
</blockquote></details>

Done, thx!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507)*

**Comment by limonte** [comment]
One test is failing on iphone/ipad. I'm working on it.

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507#-:-KtMUHi-sZWNQj4OnA8d:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/507#-:-KtMcwkeOhb_tH9bix33:bnfp4nl)*

**Pull request merged**
