### PR TITLE
Adding theme/material

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/vaadin-material-styles#49

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-combo-box-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOgHPqEzgDhZw2J4gW:-LEOgHPqEzgDhZw2J4gX:b-fc7ck9) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/fec72bbbdecc1891619706c91da514b8f16dd85b/theme/material/vaadin-combo-box-styles.html#L1)):*
> ```HTML
> <link rel="import" href="../../../vaadin-combo-box/theme/material/vaadin-combo-box-dropdown.html">
> ```

this is effectively path to this directory. Should also reference the -styles instead. Same thing with the others.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/material/vaadin-combo-box-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOgHPqEzgDhZw2J4gW:-LEOidCE9fTCLANBkcpn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/fec72bbbdecc1891619706c91da514b8f16dd85b/theme/material/vaadin-combo-box-styles.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

this is effectively path to this directory. Should also reference the -styles instead. Same thing with the others.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-combo-box-styles.html, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOnJKU7NkVGJm-S13E:-LEOnJKU7NkVGJm-S13F:bx3ca3a) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50580df6fc9a78ade40b9aa8e973b0f2c07d5abe/theme/material/vaadin-combo-box-styles.html#L3)):*
> ```HTML
> <link rel="import" href="vaadin-combo-box-dropdown-styles.html">
> <link rel="import" href="vaadin-combo-box-item-styles.html">
> <link rel="import" href="../../../vaadin-text-field/theme/material/vaadin-text-field-styles.html">
> ```

https://github.com/vaadin/vaadin-combo-box/blob/p3-preview/theme/lumo/vaadin-combo-box-styles.html#L4

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[theme/material/vaadin-combo-box-styles.html, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOnJKU7NkVGJm-S13E:-LEOoGN_Cmw9LMXMICjM:b-3w0e0t) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50580df6fc9a78ade40b9aa8e973b0f2c07d5abe/theme/material/vaadin-combo-box-styles.html#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

https://github.com/vaadin/vaadin-combo-box/blob/p3-preview/theme/lumo/vaadin-combo-box-styles.html#L4
</blockquote></details>

Thing is that non style suffixed file include `style + src ` src is already imported by the component, I think its an extra hit 
Not important when bundled obviously 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-combo-box-styles.html, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOnJKU7NkVGJm-S13E:-LEOpUcc6UUoqT-DfDgr:bowpc2z) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50580df6fc9a78ade40b9aa8e973b0f2c07d5abe/theme/material/vaadin-combo-box-styles.html#L3)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Thing is that non style suffixed file include `style + src ` src is already imported by the component, I think its an extra hit 
Not important when bundled obviously 
</blockquote></details>

The problem is the import order. The style modules of vaadin-text-field must be imported before its src file (in P3). The file isn't downloaded twice even if there are two imports to the same file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-combo-box-styles.html, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-LEOnJKU7NkVGJm-S13E:-LEOqc9OAiAjqPRTfA1w:bloeod6) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50580df6fc9a78ade40b9aa8e973b0f2c07d5abe/theme/material/vaadin-combo-box-styles.html#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The problem is the import order. The style modules of vaadin-text-field must be imported before its src file (in P3). The file isn't downloaded twice even if there are two imports to the same file.
</blockquote></details>

Maybe this is better actually

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/666#-:-LEOrQHW8zFjc6fvAFSj:bnfp4nl)*

**Pull request merged**
