### PR TITLE
Fix missing overlay when using full Shadow DOM polyfill

### LINKED ISSUE #117: Overlay not visible when using Polyfilled Shadow DOM
When opening and repositioning the overlay, we have checks in place to see that the overlay is placed under `document.body`. e.g. `this.parentElement === document.body`

As it turned out, the Shadow DOM polyfill doesn't automatically wrap the `document`, it has to be wrapped manually: `this.parentElement === wrap(document).body`

See the comments section here: https://github.com/webcomponents/webcomponentsjs/blob/c469b0002fa265416c83d5c8363071705e345a43/src/WebComponents/shadowdom.js#L13

When this issue gets fixed, we should change our test setup so that all our tests are also run by using the polyfilled Shadow DOM.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #117

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/208)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/overlay-position.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-KEji-bLhkA1_ANAuda3:-KEji-bLhkA1_ANAuda4:13451197) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ff40479df40c3c667d5112f95caddfadeac3b741/test/overlay-position.html#L179)):*
We could maybe even assert the call order here? 
`sinon.assert.callOrder(spy1, spy2, ...)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-:-KEji7cijYoGrByyblaJ:1417088721)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-:-KEjns1pOwVf4VM9vqKw:1417088721)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/overlay-position.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-KEji-bLhkA1_ANAuda3:-KEju19nNJTVepXh6mKM:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ff40479df40c3c667d5112f95caddfadeac3b741/test/overlay-position.html#L179)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by tomivirkki** [comment]
*[test/overlay-position.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-KEji-bLhkA1_ANAuda3:-KEjuKbXj01ysBZaoziX:558613160) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ff40479df40c3c667d5112f95caddfadeac3b741/test/overlay-position.html#L179)):*
Now that you're using reset() in between, there's no need to separately check for calledOnce. callOrder covers that already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/overlay-position.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-KEji-bLhkA1_ANAuda3:-KEk41ibILZTthqF9rPT:1152981602) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ff40479df40c3c667d5112f95caddfadeac3b741/test/overlay-position.html#L179)):*
Not exactly. `callOrder` checks that callbacks were called once or more. `calledOnce` checks that each callback was called just once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by tomivirkki** [comment]
*[test/overlay-position.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208#-KEji-bLhkA1_ANAuda3:-KEk4ScYndzfuMt_hpc4:-1129305176) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ff40479df40c3c667d5112f95caddfadeac3b741/test/overlay-position.html#L179)):*
You are right sir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Comment by Saulis** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/208)*

**Pull request merged**
