### PR TITLE
Set hasValue readOnly. Fixes #393

### LINKED ISSUE #393: hasValue property is not read-only
There is a typo in the property variable, it must be `readOnly` instead of `readonly`

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/394)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-combo-box-properties.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394#-KcXFOJkDk19o9GDmNXH:-KcXFOJkDk19o9GDmNXI:b8ghsau) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/075b86323987d8635c7e17f8624cfce58f6bdc46/test/vaadin-combo-box-properties.html#L89)):*
> ```HTML
>       describe('hasValue property', function() {
>         it('should be readOnly', function() {
>           expect(comboBox.hasValue).to.be.false;
> ```

Should we test `<vaadin-combo-box-light>` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-combo-box-properties.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394#-KcXFOJkDk19o9GDmNXH:-KcXFr_D3FUhgAhhFPWr:b-rdfzaw) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/075b86323987d8635c7e17f8624cfce58f6bdc46/test/vaadin-combo-box-properties.html#L89)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should we test `<vaadin-combo-box-light>` as well?
</blockquote></details>

Well, changes are in `ComboBoxBehavior` which is implemented by both. 
Since what we are testing is the implementation, using any element must work to be sure that the code is correct.
I would test in both if the code is repeated, or there was some kind of overriding of the behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394#-:-KcXjVO9m4WqibYnuUzo:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/394#-:-KcXluubGTa1e8IO2qYG:bnfp4nl)*

**Pull request merged**
