### PR TITLE
Adding js doc for selected-item-changed event

### LINKED ISSUE #91: Unify sizing with paper-inputs
Currently `vaadin-combo-box` looks a bit out of place in a form with other paper-inputs as it is sized or aligned differently.

screen shot 2015-12-14 at 8 54 33 am

### PR DESCRIPTION
**Pull request by manolo**
Fixes https://github.com/vaadin/components-team-tasks/issues/91

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/187)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-combo-box.html, line 650 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-KBwepgX7g04qWKLYfGs:-KBwepgX7g04qWKLYfGt:1389206906) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4d3cf715ed1abbcb639cd37e9f35e1a0c5ed9f33/vaadin-combo-box.html#L650)):*
`{Object} detail.value` with a proper description needed 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187)*

**Comment by Saulis** [comment]
`value` seems to be missing `notify: true`, could you add that also in the same PR please?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-:-KBwgKubeZsaKAjMNv3D:-932368692)*

**Comment by manolo** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 650 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-KBwepgX7g04qWKLYfGs:-KC0euQe2R2ZFJOppYsm:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4d3cf715ed1abbcb639cd37e9f35e1a0c5ed9f33/vaadin-combo-box.html#L650)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-:-KC0buio5OQYFPKcI3Ib:676635175)*

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-combo-box.html, line 645 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-KCF5KqC93-S-rp5E5Zx:-KCF5KqDS8FhoK8wFBxf:-1982620134) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3b0aee97db143601c535d66facd1ccefe8bd84b7/vaadin-combo-box.html#L645)):*
This description looks OK to me, but I think we should move it to the `vaadin-combo-box-basic.adoc` under the `Events` chapter and leave just the `Fired when selected item changes` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 182 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187#-KCFc5vRp3Le8462gLn7:-KCFc5vRp3Le8462gLn8:2093823967) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7e2dafa07c7c7f0481672e63dadc3b88cfebed8c/vaadin-combo-box.html#L182)):*
OK, Tomi informed me that IronFormBehavior has `notify: true` already set, and for some reason setting it again to true makes value fire two events.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187)*

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r5.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187)*

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/187)*

**Pull request merged**
