### PR TITLE
Make combo-box modal by setting body pointer-events: none

### LINKED ISSUE #343: Make overlay modal
When the combo box overlay is open, the user expects that they can close it by clicking/tapping outside the overlay area. At the same time, they do not expect that click/tap to activate any controls under the pointer (like a button for example) – they just want to close the overlay.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #343 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/379)

### CODE REVIEW

**Comment by Saulis** [comment]
Compared to `date-picker`, it's more apparent in `<vaadin-combo-box>` `touch-action: none` or something would be needed on the body level also. Unfortunately it's not supported in iOS 😢

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbU3IreYPIqW78-Dxr_:-KbU3IrfUdw10mUBVwWQ:b-qekj7w) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c2bf699d53c12b9c1ed27156cabaa5a37e554c63/vaadin-combo-box-shared-styles.html#L11)):*
> ```HTML
>       }
> 
>       :host([opened]) {
> ```

This style block is in the correct place but it looks like with `vaadin-combo-box-light` the overlay never gets the `opened` attribute. Thus accessing the overlay on -light doesn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbU3IreYPIqW78-Dxr_:-KboHKdOYeHjlLapOryJ:b-xiw2bp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c2bf699d53c12b9c1ed27156cabaa5a37e554c63/vaadin-combo-box-shared-styles.html#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This style block is in the correct place but it looks like with `vaadin-combo-box-light` the overlay never gets the `opened` attribute. Thus accessing the overlay on -light doesn't work.
</blockquote></details>

Nice catch, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbU3IreYPIqW78-Dxr_:-KboJO1kubQeWGWBLY7k:b-lnoifw) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c2bf699d53c12b9c1ed27156cabaa5a37e554c63/vaadin-combo-box-shared-styles.html#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Nice catch, done.
</blockquote></details>

The change @ vaadin-combo-box-overlay.html fixes the issue (my original comment was in the wrong file).

We should keep `:host([opened])` here since we don't want other combo-boxes on the page be accessible while one is opened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-combo-box-shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbU3IreYPIqW78-Dxr_:-KboNdB0WQ-_NmVygShM:b-vw0wpc) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c2bf699d53c12b9c1ed27156cabaa5a37e554c63/vaadin-combo-box-shared-styles.html#L11)):*
> since we don't want other combo-boxes on the page be accessible while one is opened.

There could be only one opened combo-box at the same moment, as far as I understand. How you can open the second one if you have `pointer-events: none` for whole document after opening the first one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-combo-box-shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbU3IreYPIqW78-Dxr_:-KbtvHE3C5fzWmr7hIbO:bt4j5g3) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/c2bf699d53c12b9c1ed27156cabaa5a37e554c63/vaadin-combo-box-shared-styles.html#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> since we don't want other combo-boxes on the page be accessible while one is opened.

There could be only one opened combo-box at the same moment, as far as I understand. How you can open the second one if you have `pointer-events: none` for whole document after opening the first one?
</blockquote></details>

I added `opened` to `combo-box-light`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by tomivirkki** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toggling-dropdown.html, line 86 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kby-08iYm3qOHQgVuD9:-Kby-08iYm3qOHQgVuDA:b-4h4rrn) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/692e99c6cfe46b85457d2c46335ae88cd433381d/test/toggling-dropdown.html#L86)):*
> ```HTML
>         document.body.style.pointerEvents = 'painted';
>         combobox.open();
>         Polymer.Base.async(function() {
> ```

Is there a need for there async blocks? Combo-box overlay should open synchronously

---

*[test/toggling-dropdown.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kby-9lDB6LIOatHF-ir:-Kby-9lDB6LIOatHF-is:b-e3zbcy) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/692e99c6cfe46b85457d2c46335ae88cd433381d/test/toggling-dropdown.html#L90)):*
> ```HTML
>           expect(getComputedStyle(combobox).pointerEvents).to.be.equal('auto');
>           expect(getComputedStyle(combobox.$.overlay).pointerEvents).to.be.equal('auto');
>           tapToggleIcon();
> ```

Call `combobox.close()` instead to align with how it's opened in the beginning of the test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-combo-box-behavior.html, line 150 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbyiMr3Y_sCQXZJ4-3H:-KbyiMr3Y_sCQXZJ4-3I:bx617qa) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L150)):*
> ```HTML
>        * closed.
>        */
>       _documentPointerEvents: String
> ```

IMO, a better name for the variable would avoid to maintain the comment.

To me makes perfect sense `_previousDocumentPointerEvents` of `_savedDocumentPointerEvents`

---

*[vaadin-combo-box-behavior.html, line 410 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kbyil5N6yTk0qjdFgOP:-Kbyil5OSA40p8a72Ezl:bjilaod) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L410)):*
> ```HTML
> 
>       // Restore the initial body pointer-events
>       document.body.style.pointerEvents = this._documentPointerEvents;
> ```

This comment  does not provide any extra info. I guess you can remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 150 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbyiMr3Y_sCQXZJ4-3H:-KbyuFMqdJpZSG29Pxlc:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L150)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

IMO, a better name for the variable would avoid to maintain the comment.

To me makes perfect sense `_previousDocumentPointerEvents` of `_savedDocumentPointerEvents`
</blockquote></details>

Done

---

*[vaadin-combo-box-behavior.html, line 410 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kbyil5N6yTk0qjdFgOP:-KbyuE2aZ4llvsb2fTQN:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L410)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This comment  does not provide any extra info. I guess you can remove it.
</blockquote></details>

Done

---

*[test/toggling-dropdown.html, line 86 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kby-08iYm3qOHQgVuD9:-KbyZKwVoj_tQjl9y21i:b-iry7x8) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/692e99c6cfe46b85457d2c46335ae88cd433381d/test/toggling-dropdown.html#L86)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is there a need for there async blocks? Combo-box overlay should open synchronously
</blockquote></details>

Done, thanks

---

*[test/toggling-dropdown.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-Kby-9lDB6LIOatHF-ir:-KbyZMUFJ4leIe3gmUP8:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/692e99c6cfe46b85457d2c46335ae88cd433381d/test/toggling-dropdown.html#L90)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Call `combobox.close()` instead to align with how it's opened in the beginning of the test
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-:-KbyuxcncVpBp1KmGCt3:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 150 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbyiMr3Y_sCQXZJ4-3H:-Kc-MG-_kgVV4T_YVloS:b-z8qc2i) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L150)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Mind to remove the large comment here, the first sentence is already in the comment below, and the second sentence is redundant since the variable name is clear enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by limonte** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 150 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-KbyiMr3Y_sCQXZJ4-3H:-Kc-QdES9oLmjjqLl6yx:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/073d430f8d3eade21d1c35efc1898f779e8253d8/vaadin-combo-box-behavior.html#L150)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Mind to remove the large comment here, the first sentence is already in the comment below, and the second sentence is redundant since the variable name is clear enough
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/379#-:-Kc-S-L_bQFo0VXl1_0h:bnfp4nl)*

**Pull request merged**
