### PR TITLE
Filtering with "contains"

### LINKED ISSUE #15: Filtering with "contains"
Concepts: 
- Filter value (F)
- Selected value (S)
- Displayed value (D)

Features / Behaviour:
- Typing inside the input field filters items with "contains" type of filtering
- `combobox._filter` is bound to the value that is used for filtering
- `combobox._filter` accepts any string
- `combobox.value` is bound to the selected value
- After the popup is closed, D is always S
- When the popup is opened, D is always S
- When you start typing into the input box, D is changed to F
- If popup is closed when you start typing, it should open (desktop only ofc)
- F is cleared when the popup is closed (either by selecting value or canceling)
- Blurring the input does not clear F nor change D to S

Design questions:
- Tabbing out from focus input - should it cancel selection and close popup?

Possible issues:
- We probably need a second input for the fullscreen approach

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #15

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/19)

### CODE REVIEW

**Comment by Saulis** [comment]
Still pending changes from #17

**Comment by Saulis** [comment]
note to self: add a test testing that `items` is cleared when reopening
```
  setFilter('foo');
  comboBox.close();
  comboBox.open();

  expect(getFilteredItems()).to.eql(['foo', 'bar', 'baz']);
```

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/index.html, line 95 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EJGOpGBiYV9u63r1n)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/demo/index.html#L95)):</sup>
tpyo?


---

<sup>**[vaadin-adaptive-overlay.html, line 19 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EJbc76_bbIullXSSy)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/vaadin-adaptive-overlay.html#L19)):</sup>
ooh, can't do that. Adatptive overlay should be transparent by default and combo-box should show what's beneath if there's too few items in the list to fill the space. (we'll probably enable the dropdown backdrop curtain later)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/index.html, line 95 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EJGOpGBiYV9u63r1n)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/demo/index.html#L95)):</sup>
Si.


---

<sup>**[vaadin-adaptive-overlay.html, line 19 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EJbc76_bbIullXSSy)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/vaadin-adaptive-overlay.html#L19)):</sup>
Si.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 110 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EM8oWV0MSb9vllifV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/vaadin-combo-box.html#L110)):</sup>
This line doesn't seem to be doing what it attempts to: restoring the selection value to the iron-list after filtering has set it null. iron-list.value is null always after filtering.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 110 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EM8oWV0MSb9vllifV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/vaadin-combo-box.html#L110)):</sup>
Oh, seems to have the value but not the attribute. Is there a way to make the attribute re-appear?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 110 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19#-K1EM8oWV0MSb9vllifV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/eb6aa288eb782306cf82d27a093e76018615a9e1/vaadin-combo-box.html#L110)):</sup>
done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by tomivirkki** [comment]
lgtm


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by tomivirkki** [comment]
One more thing: noticed that on my mobile device text input always starts with a capital letter by default. Should probably ignore case in filtering. It's annoying to switch the case before typing every time.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Comment by jounik** [comment]
For the auto-capitalisation, at least iOS offers an option to disable that: http://stackoverflow.com/questions/5171764/how-do-you-turn-off-auto-capitalisation-in-html-form-fields-in-ios

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1, 1 of 5 files at r3, 1 of 4 files at r4, 1 of 2 files at r6, 2 of 3 files at r7, 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/19)

**Pull request merged**
