### PR TITLE
set selectedItem after DOM attaching and before items set (Fixes #580)

### LINKED ISSUE #580: Combobox does not select an item when appended to DOM, but before 'items' are set
### Description
`vaadin-combo-box` does not select an item when appended to DOM, but before `items` are set (Chrome)

### Expected outcome
A combox should always select 'item1', no matter what order the appendChild()/.items/.selectedItem is set

### Actual outcome
In latest Chrome, the first scenario `appendThenSelectedThenItems()` doesn't show selected value, but in FF ESR, it does.

### Live Demo
https://jsfiddle.net/v6mqmcwj/1/

### Steps to reproduce
1. Open the page in a web browser.
2. Click on four buttons
3. Check the added comboboxes

### Browsers Affected
- [X] Chrome
- [ ] Firefox (works)
- [ ] Safari (not tested)
- [ ] Edge (not tested)
- [ ] IE 11 (doesn't show the combobox at all)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/585)

### CODE REVIEW

**Comment by vicsstar** [comment]
> vaadin/vaadin-combo-box:master
Amongst other things, there are structural changes in `master`, please rebase.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/585#-:-L2UIks41dwO7EUrSfyk:b-4muvee)*

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/585#-:-L2VQthgb1Le7N30xBRv:bnfp4nl)*

**Comment by vicsstar** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/585)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/585#-:-L2VTvAREzoPRURaVvdI:bnfp4nl)*

**Pull request merged**
