### PR TITLE
Support for Objects as Items

### LINKED ISSUE #96: Support objects as items
- A way to define the display value
- Filtering should use the display value instead of the raw item value? Custom filtering?
- Should the `value` (sent as a part of a form submission for instance) be the raw item value in the items array?

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #96

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/163)

### CODE REVIEW

**Comment by jounik** [comment]
In future, do not stress over the demos in the repository, as those are not really promoted anywhere. Those are most likely useful for @vaadin-marcus when he creates the marketing site demos, but we can keep the textual content in those to an absolute minimum. [The way they are handled in vaadin-upload](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/demo/) is the way to go IMO.

**Comment by samiheikki** [comment]
Reviewed 7 of 9 files at r1.
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 239 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163#-KB7ogWDdzVAzX5_n0FA:-KB7ogWDdzVAzX5_n0FB:1880591135) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/43c0d6302b4bd834d54324fc1c5cb5e730671954/vaadin-combo-box.html#L239)):*
 AMA manual of style recommends not to separate abbreviations. `i.e.`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Comment by platosha** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 239 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163#-KB7ogWDdzVAzX5_n0FA:-KB81MARXqSfhzWCUWMH:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/43c0d6302b4bd834d54324fc1c5cb5e730671954/vaadin-combo-box.html#L239)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Comment by tomivirkki** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 158 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163#-KBBs68YDc2uK2MwSGQd:-KBBs68YDc2uK2MwSGQe:890151030) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a8779b9100d4eb814d85f2e5f031f21c4f3558b5/vaadin-combo-box-overlay.html#L158)):*
This should rather be non-private since it's only used externally. _getItemLabel and _getItemValue are also used from vaadin-combo-box.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Comment by samiheikki** [comment]
Reviewed 2 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Comment by Saulis** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 158 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163#-KBBs68YDc2uK2MwSGQd:-KBCiZVNWBsVlw1XmErx:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a8779b9100d4eb814d85f2e5f031f21c4f3558b5/vaadin-combo-box-overlay.html#L158)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/163)*

**Pull request merged**
