### PR TITLE
Use demo-navigation helper

### PR DESCRIPTION
**Pull request by manolo**
Connected to #413

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/420)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/common.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420#-KfLbkbtCtmS965ISEE3:-KfLbkbtCtmS965ISEE4:b-9wj3fs) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/12776eb6e495812918de26ba4b45007cebfbcd5a/demo/common.html#L15)):*
> ```HTML
> 
> 
> <li><a href="index.html">Basic Examples</a></li>
> ```

This block seems like mistakenly copy-pasted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/common.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420#-KfLbkbtCtmS965ISEE3:-KfLcG0Ne2g2-ASavKK0:b-bulr5h) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/12776eb6e495812918de26ba4b45007cebfbcd5a/demo/common.html#L15)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This block seems like mistakenly copy-pasted
</blockquote></details>

Ups, used it as reference to fill the menu object. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420#-:-KfLcWm8aq2i4cbSIyzE:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/420)*

**Pull request merged**
