### PR TITLE
Fix focus in MS touchscreen devices, fixes #237

### LINKED ISSUE #237: Focus on element after click
I have issue with focus on the element after click with left button, right button is ok.

I have Chrome Version 50.0.2661.94 m on Windows 10 64b. I tested this issue in incognito window.

nimbus-record-video
First click is left button and second click is right button.

After remove `on-down="_preventDefault"` from `paper-input-container` element is focus ok after click left button.

https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box.html#L148

### PR DESCRIPTION
**Pull request by manolo**
fixes #237

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/249)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> #### Fix focus in MS touchscreen devices, fixes \#237
> 
> fixes #237
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249#-:-KJ_FshIoLtLwHia2jEA:1417088721)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[vaadin-combo-box.html, line 169 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249#-KJ_ORBy_ktSEA-zWMOD:-KJ_ORBy_ktSEA-zWMOE:520535758) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bb50ac3f415d9c6f84196b7b65759042ed4b4657/vaadin-combo-box.html#L169)):*
> ```HTML
>           key-event-target>
>       <div suffix id="clearIcon" on-tap="_clear"
>            on-touchend="_preventDefault" on-down="_preventDefault">
> ```

Can the `on-touchend` be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 169 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249#-KJ_ORBy_ktSEA-zWMOD:-KJe5LjiYoi3tOUGpLWd:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bb50ac3f415d9c6f84196b7b65759042ed4b4657/vaadin-combo-box.html#L169)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Can the `on-touchend` be removed?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/249)*

**Pull request merged**
