### PR TITLE
Fix: prevent selectedItem <-> value observers loop when having multiple items of the same value

### LINKED ISSUE #359: Support object items which have the same string value representation
When using objects, if `item-value-path` isn't mapped to a property of the object, setting `value` won't match any of the items in the `items`, which is OK.

However, setting `selectedItem`, results in `value` being set to `[Object object]` which in turn assigns `selectedItem`  with the first item from `items` (since `[Object object]` will match to all of the items).

The latter behaviour is of course pretty unexpected. Proposing adding a console warning when we detect that `selectedItem` doesn't have the property mapped in `item-value-path` - will save some time debugging.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #359

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/366)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_5MrI9UlSlymQfAdi9:bnfp4nl)*

**Comment by manolo** [comment]
Can this use case be included in a demo?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_9Eq2Hbv6-W_UZmOke:bdd99jn)*

**Comment by platosha** [comment]
@manolo good idea. Added a demo.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_EkHd1zHICgM8ZBRHz:b-736i2b)*

**Comment by limonte** [comment]
the demo is simple and nice, good job :+1: 

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/objects.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_F4ECtVd9TeLdASOd4:-K_F4ECtVd9TeLdASOd5:b-umpyw8) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55a7bfa783b3778e637009b7b68a0e39ded12448/demo/objects.html#L84)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Object Items with Same Value</h3>
> ```

with **the** Same Value**s**

---

*[demo/objects.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_F6RjFja_r9jnnPU6T:-K_F6RjFja_r9jnnPU6U:bk8vlhf) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55a7bfa783b3778e637009b7b68a0e39ded12448/demo/objects.html#L106)):*
> ```HTML
> 
>           countrySynonymsBox.addEventListener('value-changed', function() {
>             document.querySelector('#country-value').innerText = countrySynonymsBox.value
> ```

semicolon :)

---

*[test/selecting-items.html, line 252 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_F6ZFV7CokuWN4dKIO:-K_F6ZFV7CokuWN4dKIP:b-7ohsy7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/55a7bfa783b3778e637009b7b68a0e39ded12448/test/selecting-items.html#L252)):*
> function ()

no space between `function` and `()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_F6mG24QzphCqnbKFk:b94ifjv)*

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_TrmquVPbuD-YAGcG-:-K_Trmqv101GAl6-6dTa:b-3yrfmp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L367)):*
> ```HTML
>       if (this._focusedIndex > -1) {
>         var focusedItem = this.$.overlay._items[this._focusedIndex];
>         if (this.selectedItem !== focusedItem) {
> ```

Is this check only for optimization? Doesn't break any tests if I remove it.

---

*[vaadin-combo-box-behavior.html, line 468 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_Trv15LUZIL_w1IJr0:-K_Trv15LUZIL_w1IJr1:b-3yrfmp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L468)):*
> ```HTML
>       } else {
>         var value = this._getItemValue(selectedItem);
>         if (this.value !== value) {
> ```

Is this check only for optimization? Doesn't break any tests if I remove it.

---

*[vaadin-combo-box-behavior.html, line 582 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_TrvzsEP4RlOCmyeRL:-K_TrvzsEP4RlOCmyeRM:b-3yrfmp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L582)):*
> ```HTML
> 
>     _overlaySelectedItemChanged: function(event, detail) {
>       if (this.selectedItem !== detail.item) {
> ```

Is this check only for optimization? Doesn't break any tests if I remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366)*

**Comment by platosha** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_TrmquVPbuD-YAGcG-:-K_UdnZEkOhgFeE_Sts-:b-tvq6eh) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L367)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is this check only for optimization? Doesn't break any tests if I remove it.
</blockquote></details>

Yes and no. With Polymer v1, the built in dirty-check should bypass the observer. In v2 it will be no more. I favour an explicit check over relying on Polymer.

---

*[vaadin-combo-box-behavior.html, line 468 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_Trv15LUZIL_w1IJr0:-K_Ucq8QZSxiytHcOdlN:brhumzt) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L468)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is this check only for optimization? Doesn't break any tests if I remove it.
</blockquote></details>

Same here.

---

*[vaadin-combo-box-behavior.html, line 582 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-K_TrvzsEP4RlOCmyeRL:-K_UegxtlaE-R6F5kz-9:brhumzt) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ace2ca2193e9342251079e2c5fdb7e56536c214/vaadin-combo-box-behavior.html#L582)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is this check only for optimization? Doesn't break any tests if I remove it.
</blockquote></details>

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_Y6qut6Z1alr5zV1jQ:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366)*

**Comment by Saulis** [comment]
:lgtm: 

---

Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/366#-:-K_cpLta4gYsDHI8_kwp:bg7igkv)*

**Pull request merged**
