### PR TITLE
Hide the overlay when there are no items. 

### LINKED ISSUE #568: When there are no items hide the actual overlay instead of internal wrapper
When there are no items we are hiding the  vaadin-combo-box-dropdown-wrapper instead of the vaadin-combo-box-overlay.  That is wrong because the wrapper is not teleported and actually it already has a display none.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #568

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/569)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569#-:-Kz8NAX60B4yDMXtcoLE:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-mixin.html, line 471 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569#-Kz8PjToY80VKzEe2KnB:-Kz8PjTpusmwmJLRX0mt:b-nzqnxg) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/990e58cc7397015447976568575d8fc0582b6c3c/vaadin-combo-box-mixin.html#L471)):*
> ```HTML
>       Polymer.flush && Polymer.flush();
> 
>       this.$.overlay.hidden = !this._hasItems(this.$.overlay._items) && !this.loading;
> ```

`_hasItems` is no longer used so it can be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-mixin.html, line 471 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569#-Kz8PjToY80VKzEe2KnB:-Kz8YpTlDriYIl4uM42u:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/990e58cc7397015447976568575d8fc0582b6c3c/vaadin-combo-box-mixin.html#L471)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`_hasItems` is no longer used so it can be removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/569)*

**Pull request merged**
