### PR TITLE
Add `has-items` attribute for styling. Hide overlay when no items.

### LINKED ISSUE #162: Improvement: dropdown="false" atribute
I need a dropdown="false" atribute for not open dropdown list and hide the dropdown icon.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #162

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/550)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFKVw_15W3_giQgHj5:-KwFKVw_15W3_giQgHj6:b-j2qcln) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box-mixin.html#L58)):*
> ```HTML
>         items: {
>           type: Array,
>           value: null
> ```

Would this work if we didn't change the default value in this public property? Even though not a big one, it's still API change.

---

*[vaadin-combo-box.html, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFL6yRqUjtAlfUnH-b:-KwFL6yRqUjtAlfUnH-c:b-e7fjm7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box.html#L50)):*
> ```HTML
>       }
> 
>       [part="toggle-button"][hidden] {
> ```

Not needed since the default display value isn't overridden.

---

*[test/toggling-dropdown.html, line 278 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFLastnOXVam9336b7:-KwFLastnOXVam9336b8:b-5bw5tt) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/test/toggling-dropdown.html#L278)):*
> ```HTML
>       });
> 
>       it('toggleIcon should not be hidden when there are no items', () => {
> ```

"...should be hidden..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550)*

**Comment by tomivirkki** [comment]
The referenced issues is also quite old. `<vaadin-combo-box>` 3.0.0 uses Vaadin themable mixin, meaning that you can build this functionality on top of `<vaadin-combo-box>` without us having to make any changes to the core implementation.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwFRiU2J1oj6B6QeGnf:br8p92n)*

**Comment by manolo** [comment]
I don't see a way to do this without providing some attribute like `no-items` or `empty-items` 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFKVw_15W3_giQgHj5:-KwFRw2S4O1AS0z5_pKb:b63oeap) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box-mixin.html#L58)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would this work if we didn't change the default value in this public property? Even though not a big one, it's still API change.
</blockquote></details>

undefined does not fires the first time the computed `hidden$="items.length"`  even if we  have something like `hidden$="_method(items.*)"` so we need to set an initial value like `null` or `[]`, but I don't like providing here an empty array.

---

*[vaadin-combo-box.html, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFL6yRqUjtAlfUnH-b:-KwFSRLfcoA0pl23Lil7:b-6kwig3) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box.html#L50)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not needed since the default display value isn't overridden.
</blockquote></details>

It's not needed, I left here by mistake

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwFScAgdzRXWiZprYJD:blcwlj9)*

**Comment by tomivirkki** [comment]
What we could consider instead is providing `has-items` state attribute. That would give the theme implementation more leverage to hide/opacify.. the toggle button as desired.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwFStdwskIsJkF4Qof4:bxf07t6)*

**Comment by tomivirkki** [comment]
...or `no-items` as you wrote above

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwFSw6ePI_hwjX3JhRR:b43cqj7)*

**Comment by tomivirkki** [comment]
Maybe `has-items` would still be nicer since default values are typically falsy (the attribute doesn’t exist) and it would be in line with the current `has-value` attribute.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwFTXNuwlL3jr0LWE6K:b-6kwkz4)*

**Comment by manolo** [comment]
implemented with `has-items` aligned with `has-value`

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFKVw_15W3_giQgHj5:-KwG8aealukbcC6V4utZ:b-btemd4) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box-mixin.html#L58)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

undefined does not fires the first time the computed `hidden$="items.length"`  even if we  have something like `hidden$="_method(items.*)"` so we need to set an initial value like `null` or `[]`, but I don't like providing here an empty array.
</blockquote></details>

Not needed anymore. Removed.

---

*[vaadin-combo-box.html, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFL6yRqUjtAlfUnH-b:-KwG8sxu07BMPQQHLLiP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/vaadin-combo-box.html#L50)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It's not needed, I left here by mistake
</blockquote></details>

Done.

---

*[test/toggling-dropdown.html, line 278 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwFLastnOXVam9336b7:-KwG8mvkX75xQ-_rAtas:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/f503c130957d6df129815a9ca0628db3076a5e66/test/toggling-dropdown.html#L278)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"...should be hidden..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwG8uamFmaZ5HSL_2qC:b-bax08)*

**Comment by limonte** [comment]
should we also hide the overlay based on `has-items` to prevent this

recorded

?

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJLmxQ0Koxc3g5z4qn:-KwJLmxQ0Koxc3g5z4qo:bu2knf6) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-mixin.html#L114)):*
> It can be used for example in styling of the component

The property? I think the attribute is primarily intended for styling and that's already documented. Remove this sentence.

---

*[vaadin-combo-box-styles.html, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJMDPIs2YN0CY31f4F:-KwJMDPIs2YN0CY31f4G:b7nl4xx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-styles.html#L26)):*
> ```HTML
>       }
> 
>       :host(:not([has-items])) [part="toggle-button"] {
> ```

Let's not add any breaking changes to the default theme. We only need the attribute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJLmxQ0Koxc3g5z4qn:-KwJa2p2PMIF-oPSE2Hj:b-tn75t2) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-mixin.html#L114)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

> It can be used for example in styling of the component

The property? I think the attribute is primarily intended for styling and that's already documented. Remove this sentence.
</blockquote></details>

It is aligned with the hasValue attribute, that the reason. Do I remove also from there ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-mixin.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJLmxQ0Koxc3g5z4qn:-KwJaPqVKh8SxyLKxcPY:bv74kc5) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-mixin.html#L114)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It is aligned with the hasValue attribute, that the reason. Do I remove also from there ? 
</blockquote></details>

:+1: Should be removed imo. Kind of strange to have this in the property description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550)*

**Comment by manolo** [comment]
@limonte  It should be already handled in https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-mixin.html#L480 otherwise it seems a bug

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwJapy_wFWdBSfGLKFJ:b-b7wug2)*

**Comment by limonte** [comment]
Tested with combo-box 3.0 stable + valo-theme 2.0-alpha3. The issue is there, I'll report it.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwJgNnRWyNhQ9NDlts3:b9r20za)*

**Comment by jouni** [comment]
> should we also hide the overlay if `has-items` is `false` to prevent this

@limonte, the overlay should not be shown when the `filteredItems` is empty. Or does `has-items` reflect just that?

**Comment by manolo** [comment]
@limonte fixed the problem with the overlay being shown. Code is wrong since we upgraded the element to use vaadin-overlay, because the path to set hidden need to be in the teleported fragment.

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-mixin.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJLmxQ0Koxc3g5z4qn:-KwLPq2HH7hdZLanSRrs:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-mixin.html#L114)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

:+1: Should be removed imo. Kind of strange to have this in the property description.
</blockquote></details>

Done.

---

*[vaadin-combo-box-styles.html, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwJMDPIs2YN0CY31f4F:-KwLPrpMeHPlk01ZuuPB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d478f10f6104725b346e5c4f3da53b374658c680/vaadin-combo-box-styles.html#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Let's not add any breaking changes to the default theme. We only need the attribute.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwLPW6vmBT8ad9hpBLV:bty250i)*

**Comment by tomivirkki** [comment]
Analysis isn't updated in this PR

---

Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-dropdown-wrapper.html, line 16 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwOz1II4VqVBN5CLwWp:-KwOz1II4VqVBN5CLwWq:b-nsqjjl) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/801e5eac6dfc7e081021d58220e9b2b0a772b735/vaadin-combo-box-dropdown-wrapper.html#L16)):*
> ```HTML
> <dom-module id="vaadin-combo-box-dropdown-wrapper">
>   <template>
>     <vaadin-combo-box-dropdown id="dropdown" opened="{{opened}}" hidden="[[_hidden(_items.*, loading)]]" position-target="[[positionTarget]]" vertical-offset="[[verticalOffset]]"
> ```

This doesn't work with "Custom filtering" example. Should mind `filteredItems`

---

*[vaadin-combo-box-dropdown-wrapper.html, line 392 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwOyxptz7ONfGJ3adJj:-KwOyxptz7ONfGJ3adJk:b-2ts5g4) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/801e5eac6dfc7e081021d58220e9b2b0a772b735/vaadin-combo-box-dropdown-wrapper.html#L392)):*
> ```HTML
> 
>       _hidden() {
>         return !this.loading && (!this._items || !this._items.length);
> ```

Declare all dependencies: https://www.polymer-project.org/2.0/docs/devguide/observers#dependencies

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-KwOyh82mCsBGNbk-nm9:b3up1ss)*

**Comment by manolo** [comment]
Done

---

Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-dropdown-wrapper.html, line 16 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwOz1II4VqVBN5CLwWp:-Kwi1dw4GBGWNZfjdzFl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/801e5eac6dfc7e081021d58220e9b2b0a772b735/vaadin-combo-box-dropdown-wrapper.html#L16)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This doesn't work with "Custom filtering" example. Should mind `filteredItems`
</blockquote></details>

Done.

---

*[vaadin-combo-box-dropdown-wrapper.html, line 392 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-KwOyxptz7ONfGJ3adJj:-Kwi1k8DuASWK_cRvE6w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/801e5eac6dfc7e081021d58220e9b2b0a772b735/vaadin-combo-box-dropdown-wrapper.html#L392)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Declare all dependencies: https://www.polymer-project.org/2.0/docs/devguide/observers#dependencies
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/550#-:-Kw_3Ym-SODyRRtOrcJr:bb6un1j)*

**Comment by tomivirkki** [comment]
Talked about this with the team and concluded that this is no longer needed as propagating `theme` attribute with themable mixin can be used to achieve the same outcome. Closing.

**Pull request closed without merging**
