### PR TITLE
Adding basic ARIA support. Fix #34

### LINKED ISSUE #34: Basic accessibility support (ARIA roles)
- See how the Framework combobox works
- See also Polymer `<paper-dropdown-menu>`
- http://www.w3.org/TR/wai-aria/roles#combobox
- http://www.w3.org/TR/wai-aria/roles#listitem
- Tests should assert that correct attributes are in correctomundo places
- Ask help from the Framework team & UX team
- Figure out how to verify we have all the needed attributes?
- Chrome has an Accessibility Developer Tools extension

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/60)

Feature:
 - WAI-ARIA support

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/aria.html, line 69 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BiJTlq0ypeok2Db_:-K47BiJTlq0ypeok2Dba:-705540952) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L69)):*
"openned" typo

---

*[test/aria.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BczPfMQOeWCEfkM7:-K47BczPfMQOeWCEfkM8:-299406815) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L75)):*
I guess we should open the popup before closing it?

---

*[test/aria.html, line 86 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BzmK_M3_oICbOw7d:-K47BzmK_M3_oICbOw7e:448776630) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L86)):*
Why are we choosing the selectedItem through the selector?

---

*[test/aria.html, line 95 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47CB6stigC2dow92cK:-K47CB6stigC2dow92cL:644454471) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L95)):*
Can we get rid of the timeout somehow? 200ms might be enough locally, but not remotely.

---

*[vaadin-combo-box.html, line 420 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479SPJCAC-4CW5tlFl:-K479SPJCAC-4CW5tlFm:561313931) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L420)):*
Where does this `it` come from?

---

*[vaadin-combo-box.html, line 423 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479xpc6WZ36ujY0GOj:-K479xpc6WZ36ujY0GOk:1500265645) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L423)):*
If this attribute is always added for the items, should it be added in the template already?

---

*[vaadin-combo-box.html, line 424 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47A91TFfQEMYRdMOs2:-K47A91TFfQEMYRdMOs3:720883744) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L424)):*
Could this attribute be bound `aria-selected$=[[_isItemFocused(_focusedIndex,index)]]`  ?

---

*[vaadin-combo-box.html, line 426 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47B71ExKegq9Y1wgex:-K47B71ExKegq9Y1wgey:1522418438) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L426)):*
Could these two attributes be bound to the `focusedIndex` property using data binding? Either directly or by prepending the `it` if it's necessary?

---

*[vaadin-combo-box.html, line 435 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479aY1pP6jLr_ZaqOV:-K479aY239qsDPoHej-q:-384935896) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L435)):*
Could this attribute be bound using Polymer data binding? `aria-expanded$=[[opened]]` or something?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/aria.html, line 69 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BiJTlq0ypeok2Db_:-K47aVUVQlORwJs3UH07:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L69)):*
Done.

---

*[test/aria.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BczPfMQOeWCEfkM7:-K47WMes5ZkQCoW8uee-:-1592724117) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L75)):*
Yep, when refactoring I forgot the open which was in a before

---

*[test/aria.html, line 86 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47BzmK_M3_oICbOw7d:-K47WfCQsdtJ_H4IqAfI:1143630300) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L86)):*
For some reason just arrow-down does not changes the focused status, could be because of the mock-iterations

---

*[test/aria.html, line 95 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47CB6stigC2dow92cK:-K47ZczCcZVEKj4GGvXR:69901231) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/test/aria.html#L95)):*
when we set the arial attributes we have to do in asynchronous in order to let Polymer set the item id before we use the dom selector, so we have to wait for that, we could adjust the timeouts probably.

---

*[vaadin-combo-box.html, line 420 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479SPJCAC-4CW5tlFl:-K47_GIo5TMOkt7ehQkw:-1658959957) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L420)):*
That is the prefix in the template `id$="it[[index]]"` html ids have to start with a letter and cannot be numers,  I remember some issues with certain browsers long time ago.

---

*[vaadin-combo-box.html, line 423 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479xpc6WZ36ujY0GOj:-K47__DDNQ89S8N7TfFa:1409920839) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L423)):*
The problem is that iron-list renders more hidden elements than the actual list of items, we cannot mark then as option roles, otherwise aria count those as valid items

---

*[vaadin-combo-box.html, line 424 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47A91TFfQEMYRdMOs2:-K47_sVMdT9imiEOJWX0:858561259) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L424)):*
nope, it has to be the string 'true' or 'false' I commented it in the issue

---

*[vaadin-combo-box.html, line 426 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K47B71ExKegq9Y1wgex:-K47a63W_QLzNHKTzJwi:1616856735) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L426)):*
probably yes, but I'd rather to have all the aria logic condensed in one place.

---

*[vaadin-combo-box.html, line 435 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479aY1pP6jLr_ZaqOV:-K47aGNnUPnhW8Ezo5YJ:734887335) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L435)):*
Nope, polymer always consider boolean attribute values as adding/removing the attribute instead of setting the string value to 'true' 'false'

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box.html, line 420 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479SPJCAC-4CW5tlFl:-K47gmFj2SU9PqvUnu0J:2014475671) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L420)):*
Yeah, but where does "it" come from? short form "item" ? I think it could something more understandable that "it"

---

*[vaadin-combo-box.html, line 423 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479xpc6WZ36ujY0GOj:-K47h4JYbciSMKJF5xkK:800486111) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L423)):*
Does it actually matter if aria counts those as valid items? Why wouldn't they be valid items if they aren't visible? They are for blind people after all :smile: 

---

*[vaadin-combo-box.html, line 435 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479aY1pP6jLr_ZaqOV:-K47hlS_JbqZIneTT4J1:719040069) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L435)):*
I think that would still be a better option. Modified the patch here: https://github.com/vaadin/vaadin-combo-box/compare/aria2 please have a look

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-combo-box.html, line 423 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479xpc6WZ36ujY0GOj:-K47pHxGixbcirWF-TGx:2008279453) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L423)):*
Ah now I see, it actually renders the elements but doesn't compute the bound attributes, hmm...

---

*[vaadin-combo-box.html, line 435 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479aY1pP6jLr_ZaqOV:-K47pNJ3FgoXnUn1k_gl:-866294811) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L435)):*
Pushed a new commit to this branch instead.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-combo-box.html, line 420 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K479SPJCAC-4CW5tlFl:-K47pbIoGkgXXG80ivK5:886604899) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/80458e4e0bc8006d2c9ee848231c715c1f38d56b/vaadin-combo-box.html#L420)):*
it comes from item, actually I wanted just a letter but took 2, and also had a version taking random prefix to avoid repeated id's in the document, but using polymer selectors is not a problem, 'it' could be confusing though

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-combo-box.html, line 328 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60#-K48g7JtvDZ6pPJZq-Xd:-K48g7JtvDZ6pPJZq-Xe:1032506174) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ee69d6bda50ce962bf31fc525568cc0e38e079bb/vaadin-combo-box.html#L328)):*
Yes, that is the option I evaluated first, but I thought that so much methods in the private api could confuse the user when looking for api methods, so I ended with a couple of methods instead. 
Anyway it makes very sense to use method per property.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Comment by Saulis** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/60)*

**Pull request merged**
