### PR TITLE
Always close the dropdown on intentional blur

### LINKED ISSUE #164: iOS software keyboard "Done" button should close the dropdown
Based on the discussion in https://github.com/vaadin/components-team-tasks/issues/81#issuecomment-186244590

Summary:
- Feels like the intuitive thing to do, to prevent the user from needing to do two actions in order to dismiss the interaction
- Both Angular Material Autosuggest and Kendo UI ComboBox/AutoSuggest components work this way

### PR DESCRIPTION
**Pull request by platosha**
Fixes #164

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/218)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Seems that the clear button doesn't clear the value properly. It still closes the dropdown but the old value remains.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218#-:-KFJpiik1KX62DQ5kZLt:1712798920)*

**Comment by jounik** [comment]
@tomivirkki, don’t we have unit tests for the clear button? Why didn’t they catch that?

**Comment by tomivirkki** [comment]
Might be that the tests ignore the visibility of the button. It can be programmatically clicked even though it's not actually visible for the user.

**Comment by tomivirkki** [comment]
...and in this particular bug, the dropdown closes (on mousedown) before the clear actually gets to fire the required click event.

**Comment by platosha** [comment]
Fixed the clear button issue. Accidentally that simplified the code even more. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218#-:-KFK4FZJ3dl9XwNYtBGg:-1013584799)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218#-:-KFNTRelQ_Fdcz_s3PTa:1417088721)*

**Comment by platosha** [comment]
Rebased on master.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218#-:-KFNZp-u1st629Dp0NWf:735937904)*

**Comment by platosha** [comment]
Added changes suggested by @tomivirkki. Tapping the label when input is focused doesn't cause the flicker.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218#-:-KFNq5Rg2_xNW4-d1r8h:-787401876)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/218)*

**Pull request merged**
