### PR TITLE
Feature/scrolling blur

### LINKED ISSUE #22: Enable scrolling
- Enable scrolling (duh)
- Hide soft keyboard on touch devices when scrolling (also on iPad which doesn't use fullscreen) (by blurring the input field) 
- We assume that the soft keyboard is always hidden if the are no input fields (nor text areas) focused
- See #2

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #22

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/31)

### CODE REVIEW

**Comment by cwayfinder** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-combo-box.html, line 195 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31#-K1dMhVhyEDqk5eU2-47)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/375fd05efee314f1e89a50e6749ac7960d4cfe69/vaadin-combo-box.html#L195)):</sup>
Have you tried the `focusTarget` property of the `iron-dropdown` element? You can use it to specify the element that will be focused when the dropdown opens.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 195 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31#-K1dMhVhyEDqk5eU2-47)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/375fd05efee314f1e89a50e6749ac7960d4cfe69/vaadin-combo-box.html#L195)):</sup>
Yeah, we tried it. Couldn't get it working on IE. Although the tests are now skipped for non-fullscreen devices so it could be reconsidered


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 195 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31#-K1dMhVhyEDqk5eU2-47)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/375fd05efee314f1e89a50e6749ac7960d4cfe69/vaadin-combo-box.html#L195)):</sup>
done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Comment by Saulis** [comment]
Reviewed 5 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[vaadin-combo-box.html, line 256 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31#-K1h1TOTSwH-s_sByJOo)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d91e141179ec4fecd6d559065f2e568420c2c361/vaadin-combo-box.html#L256)):</sup>
What is this `blur()` for? If I remove it, no tests break?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 256 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31#-K1h1TOTSwH-s_sByJOo)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/d91e141179ec4fecd6d559065f2e568420c2c361/vaadin-combo-box.html#L256)):</sup>
Seems to be missing a test case indeed. Remove the line and close the fullscreen dropdown with the down icon on the right -> at least iOS keyboard stays visible


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Comment by Saulis** [comment]
OK, I'll do a test for that.

**Comment by tomivirkki** [comment]
Could be included in #24


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/31)

**Pull request merged**
