### PR TITLE
Allow custom inputs, make focusing case-insensitive when filtering

### LINKED ISSUE #51: Allow custom input values
We need to decide if we want to and can support this (allow the user to type any value to the input which is not in the actual options list).

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #51

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/121)

### CODE REVIEW

**Comment by platosha** [comment]
LGTM overall :thumbsup: 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/filtering.html, line 73 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9S5hi8gw20a4HP2qXA:-K9S5hi9fjIr38aPeYoN:-436741272) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/fe28b6011bd0d2d43752496ba1c90994dad2e2ec/test/filtering.html#L73)):*
Feels wrong when reading the test title like this: “<The input value> should set the combobox value when closing”. The same with the following test title.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-:-K9S8BcJXnxZNoLGXkHn:561777502)*

**Comment by platosha** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/keyboard.html, line 172 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9S99ppgN4LZBhUTSEr:-K9S99ppgN4LZBhUTSEs:352089384) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/88d69e856b7144bd17d0d07eee28df6916213838/test/keyboard.html#L172)):*
It's simplier to use `.to.be.true` here, isn't it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by platosha** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by Saulis** [comment]
@jounik found one bug I need to fix still, will upload new revision tomorrow.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-:-K9SDz_2D6v0li54SWQ6:1431615115)*

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 265 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WxKgYa1FI3dYGM1h1:-K9WxKgYa1FI3dYGM1h2:-893964336) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L265)):*
What is this used for? All the tests seem to pass even without it

---

*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9WzO_jrHl40-gl2wyc:1456923342) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
This is some strange logic. It allows you to select a custom value on close even if an item is focused (that's how I assumed it to work) but _only_ if there's more items than one visible

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 265 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WxKgYa1FI3dYGM1h1:-K9X23zqPAqqp2QlBEkA:75687436) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L265)):*
Ah.. it's for clearing the `value` after hitting enter when the input field is empty. 

The reason why the test passes is actually that the new implementation sets `` as a new value when closing the overlay when the input is cleared so this logic can actually be removed :+1: Excellent catch my friend!

---

*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9X2fwW611d9g-yly1_:-1054346717) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
Well yes - in other words it will only select the focused item when closing the overlay when there is exactly one match. Otherwise, a custom value is set.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9X4sXlW5kbz-62usRb:1001599132) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
The special case for one match feels a bit random..imo the custom input value should always be applied on close regardless of how many items happen to remain in the filtered list at that time. Is the behaviour for this specified somewhere?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by jounik** [comment]
*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9X5RDZOKJZ3G3pfKhK:916297060) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
We discussed this with Sauli when I tested out the implementation. This felt quite natural to me at least, that if the list has a value "Bar", and you type "bar" in the field, and we do case-insensitive matching of the filtering and highlight the one and only value in the list.

But I guess it might be better to avoid making any highlights and automatic selections if it’s not an exact match (case-sensitive), and force the user to explicitly highlight and select the item.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9XY8SJct0TpoNiDKI9:562469525) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
Yeah the logic makes sense when you type in the whole word (auto-selecting the value with the correct case).
But if you type a value ('Niger') and there happens to be an item in the list beginning with the same string ('Nigeria'), then it might get weird if it's auto-selected for you.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by jounik** [comment]
We talked about it some more Sauli and Tuomas, and Sauli will make one more roumd of adjustments.

And yes, typing "nigeri" and blurring the field should not auto-select Nigeria. But typing "nigeria” and blurring, should that be auto-selected to Nigeria, that’s debatable. But we talked that it is probably on the safe side for us to never auto-select anything.

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box.html, line 349 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9WzO_jrHl40-gl2wyb:-K9bIj4adW5jzST1jeJV:1906498747) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bffbc2de4190d0b3dccba7433fde3b09e37e9f0/vaadin-combo-box.html#L349)):*
Added a feature which prefills the input field when navigating using keyboard. Now the cooperation between keyboard navigation and custom inputs seem to work more logically.

---

*[vaadin-combo-box.html, line 120 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9bJTlAgzDnWcdhYNN0:-K9bJTlAgzDnWcdhYNN1:474224001) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/vaadin-combo-box.html#L120)):*
This is now triggered only when there's actually something typed.

---

*[vaadin-combo-box.html, line 201 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9bJHLc7UHUA6UJgzo-:-K9bJHLc7UHUA6UJgzo0:-751015671) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/vaadin-combo-box.html#L201)):*
Added a separate observer here to prevent it from triggering when `_filter` is set to `undefined`

---

*[vaadin-combo-box.html, line 355 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9bJ4ePAOx06vEDUu_b:-K9bJ4ePAOx06vEDUu_c:1648064111) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/vaadin-combo-box.html#L355)):*
Had to add this async back here to make the scrolling work on all browsers more reliably.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by tehapo** [comment]
Reviewed 1 of 4 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[test/keyboard.html, line 229 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9fFu-02nWruxb4yH5V:-K9fFu-02nWruxb4yH5W:-1525646510) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/test/keyboard.html#L229)):*
I think this doesn't actually test that the text is selected. Only that the cursor is moved to beginning of the text.

Maybe add `expect(getInput().selectionEnd).to.eql(3);` also?

---

*[test/keyboard.html, line 249 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9fFBYWRosbcScuh8Hx:-K9fFBYXP2nKF8r0N7mS:1369349114) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/test/keyboard.html#L249)):*
Same as the comment above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by Saulis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/keyboard.html, line 229 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9fFu-02nWruxb4yH5V:-K9fRAU81bdLzr5UNg-5:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/test/keyboard.html#L229)):*
Done.

---

*[test/keyboard.html, line 249 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121#-K9fFBYWRosbcScuh8Hx:-K9fRBbRaPBHl2psBeF6:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/10e8606dfb7f3362e57a9c0bfa2305da3689442f/test/keyboard.html#L249)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Comment by tehapo** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/121)*

**Pull request merged**
