### PR TITLE
Enable scrolling when navigating with keyboard.

### LINKED ISSUE #45: Scroll items with keyboard navigation
Currently, scroll position does not follow focused item when using keyboard navigation.

- Focused item should be aligned with "scroll-to-any" (escalator term)

### PR DESCRIPTION
**Pull request by Saulis**
Uses logic adopted from iron-list to determine the number of
visible items and the index of the last visible item to trigger
scrolling only when navigating out of the viewport.

Fixes #45

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/66)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/keyboard.html, line 232 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O6bA05VlUhJwtnycq:-K4O6bA05VlUhJwtnycr:-1016885803) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/test/keyboard.html#L232)):*
Missing semicolon at the end of the line.

---

*[test/scrolling.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O43P_k49lCH71NQbU:-K4O43P_k49lCH71NQbV:1999153897) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/test/scrolling.html#L45)):*
Why test without any assertion? Perhaps this needs to be wiped out, because scrolling using keyboard gets tested by test/keyboard.html

---

*[vaadin-combo-box.html, line 321 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O7Cy6trh4NgC2_TEP:-K4O7Cy6trh4NgC2_TEQ:-23803449) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L321)):*
Double space before "0".

Also it would be nice to have whitespaces between "if"-s and "(". Other ifs in this file have it.

---

*[vaadin-combo-box.html, line 324 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4OCEycmN4OLRyGcDP-:-K4OCEycmN4OLRyGcDP0:1119425194) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L324)):*
The last visible item is treated outside the viewport.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4O9wkRnPfxj76VA4uX:-518430123) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
What if we have items with different heights? Do we care about this case for now?

---

*[vaadin-combo-box.html, line 337 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4OAF63ObulTOYoI19k:-K4OAF63ObulTOYoI19l:415191836) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L337)):*
`Math.round` is fine as long as the last visible item is treated outside viewport (what I mentioned in one of the comments above). But generally it is quite inaccurate here. I think `Math.floor` would make more sense instead.

Viewports with the height of 7.5 items should be treated as capable of displaying 7 complete items, but `Math.round` would give us 8. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/keyboard.html, line 232 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O6bA05VlUhJwtnycq:-K4RFcZKo9hjsP5_Yg_y:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/test/keyboard.html#L232)):*
Done.

---

*[test/scrolling.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O43P_k49lCH71NQbU:-K4RFlFiZwFi0g55MMDf:-642015436) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/test/scrolling.html#L45)):*
Oops, I accidentally...

---

*[vaadin-combo-box.html, line 321 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O7Cy6trh4NgC2_TEP:-K4RFxLsIH7rANpkeYeG:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L321)):*
Done.

---

*[vaadin-combo-box.html, line 324 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4OCEycmN4OLRyGcDP-:-K4RIyshYZD1JpfuFJLG:-2090239535) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L324)):*
Not sure I understand, we need to meet next to some paper and pencils :smile: 

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4RGDCqwq8asljjUTXv:-1260856693) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Then we're pretty much screwed :smile: - we would then need to use some other means to determine how many items there are. I wouldn't consider that right now.

---

*[vaadin-combo-box.html, line 337 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4OAF63ObulTOYoI19k:-K4RH6WMr2cripwrj-dL:-1220245184) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L337)):*
But, wouldn't having a smaller `visibleItemsCount()` in some cases prevent from scrolling to the bottom, leaving the last item hidden? Wouldn't `Math.ceil` be a better option?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 337 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4OAF63ObulTOYoI19k:-K4RW1ZBZcaUQdy_V0Nz:1091614917) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L337)):*
We decided to go with `Math.floor` after some discussion and trying out. Much better now.

---

*[vaadin-combo-box.html, line 335 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4RVu12_ptOn2vLJPs1:-K4RVu12_ptOn2vLJPs2:-1829626185) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/da830466e290b9d8b6a1d7274950a22cb641c433/vaadin-combo-box.html#L335)):*
Mind the space after `if`, please.

---

*[vaadin-combo-box.html, line 343 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4RW-D2V0ewEnF5G0Jp:-K4RW-D2V0ewEnF5G0Jq:-1829626185) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/da830466e290b9d8b6a1d7274950a22cb641c433/vaadin-combo-box.html#L343)):*
Mind the space after `if`, please.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r6.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4RshrFqwe4KfDEIgb0:-194713432) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Not good. Items don't have explicit fixed height with current styles, and they wrap sentences into multiple lines. Too easy to break the formula here.

On the other hand, it's not too hard to make it correct. We just need to replace this formula with an iterator. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by jounik** [comment]
*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4RukMGaNI4IkB0GNsp:-664788954) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
I would force all items on one line now with white-space: nowrap; (do remember to add text-overflow: ellipsis; as well), and deal with this later when we add the support for item templates.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4S3B_aktdzza4avJMH:354305399) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Agree with forcing items to be on one line as well. Sauli, would you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4SLGLxzv8e-7jYnBdk:-907401032) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Sounds good. I quickly tried what happens with long items, but it doesn't seem to wrap them at all:

https://jsfiddle.net/he9v08sv/2/

---

*[vaadin-combo-box.html, line 335 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4RVu12_ptOn2vLJPs1:-K4SLCU2A9n-sMQ5FRcW:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/da830466e290b9d8b6a1d7274950a22cb641c433/vaadin-combo-box.html#L335)):*
Done.

---

*[vaadin-combo-box.html, line 343 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4RW-D2V0ewEnF5G0Jp:-K4SLFFy4jT1aDKH8bcl:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/da830466e290b9d8b6a1d7274950a22cb641c433/vaadin-combo-box.html#L343)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by jounik** [comment]
*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4SOagroluKqK0k5R-D:-2107388268) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Could you add the following to the combo box stylesl:

```css
.item {
  ...
  overflow: hidden;
  text-overflow: ellipsis;
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4SPzTmo46DfRsqSVUp:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Reviewed 1 of 3 files at r7, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4SQetmY495JhqiFq0i:1554194293) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
It wraps if you put some spaces and make words: https://jsfiddle.net/he9v08sv/3/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 336 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4O9wkRnPfxj76VA4uW:-K4TJn_gT4ZUZlxraf79:1389323843) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0ab9dd4b1c2b5ea7e3fc199f372ce2fb311e8f00/vaadin-combo-box.html#L336)):*
Please don't mind my comment with JSFiddle link above, it's FYI only.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by tomivirkki** [comment]
At least on Chrome the scrollbar gets hidden behind the focused item

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 259 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4W_egkxqD6Ro_JKTTo:-K4W_egl5U7KVoa_PPzj:-1812881486) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/abcca2a6d0b1aa96fbf7f391439ac382af9d07e2/vaadin-combo-box.html#L259)):*
Extra whitespace

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-:-K4W_UHnMR2Q_F3k3pUK:1225343281)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 251 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4WbhxGaP7S3HJJRFqL:-K4WbhxGaP7S3HJJRFqM:-440581048) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/abcca2a6d0b1aa96fbf7f391439ac382af9d07e2/vaadin-combo-box.html#L251)):*
Instead of imperatively applying this stuff in ready() a more "polymer" way to do this would be to bind overlay's scroller property declaratively like overlay=[[getOverlayScroller()]]

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 251 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4WbhxGaP7S3HJJRFqL:-K4gYCa_dgx8v24TSHxT:1441525920) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/abcca2a6d0b1aa96fbf7f391439ac382af9d07e2/vaadin-combo-box.html#L251)):*
Moved directly into <vaadin-adaptive-overlay/>.

---

*[vaadin-combo-box.html, line 259 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66#-K4W_egkxqD6Ro_JKTTo:-K4gYb0_81npzq_d58YD:1740281843) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/abcca2a6d0b1aa96fbf7f391439ac382af9d07e2/vaadin-combo-box.html#L259)):*
Removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 3 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/66)*

**Pull request merged**
