### PR TITLE
Position overlay to text-field

### LINKED ISSUE #549: Overlay alignment should take error message and label into consideration
The overlay should visually be attached to the text field, and not leave space because there’s an error message. The error message could be multiple lines long, even.

screen shot 2017-10-04 at 12 56 05

The same applies for the label:

screen shot 2017-10-04 at 12 57 51

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #549

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/600)

### CODE REVIEW

**Comment by vicsstar** [comment]
*[src/vaadin-combo-box.html, line 263 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-L2dnGZxof6bcEFn2gnX:-L2dnGZxof6bcEFn2gnY:b-d1esfl) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/be4d58930bcd5eebbcb74631e797faa8e53898fb/src/vaadin-combo-box.html#L263)):*
> ```HTML
>             _positionTarget: {
>               type: Element,
>               readOnly: true
> ```

This is useful for "public" properties only as for "private" properties it's not expected that they'd be written to by developers in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600)*

**Comment by samiheikki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-combo-box.html, line 263 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-L2dnGZxof6bcEFn2gnX:-L2emZDjwHJzOcMmAKkb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/be4d58930bcd5eebbcb74631e797faa8e53898fb/src/vaadin-combo-box.html#L263)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

This is useful for "public" properties only as for "private" properties it's not expected that they'd be written to by developers in the first place.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600)*

**Comment by vicsstar** [comment]
The issue this PR fixes should be covered by at least one test, so we don't break it in the future.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-:-L2esAbLdOKNw2ZYf2Mv:b-6w4ak2)*

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-:-L2tgUWHSyUbrbJYfpna:bnfp4nl)*

**Comment by vicsstar** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600)*

**Comment by web-padawan** [comment]
@tomivirkki is this something we want to have merged? Seems fine to me.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-combo-box.html, line 294 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-L2yG8-agUpTfKlJRGXs:-L2yG8-agUpTfKlJRGXt:bvt9ulm) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/74a917b3e4c0b2c148a9308fd8d567d37fc111b1/src/vaadin-combo-box.html#L294)):*
nit: this seems to work (and we still have this reference in a lot of test) but the upgrade guide notes:

> Use this.shadowRoot in place of Polymer.dom(this.root).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-:-L2yF9xlVfNzzbRAgF9U:b-ovg2kk)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600#-L3CiR5w2hPZqJj2fDj6:-L3CiR5xdbIin8bsGFD9:bu9se5d) (no related file):*
I wonder how `<vaadin-combo-box-light>` should act like.

At this point in this case `positionTarget` would be `<vaadin-text-field>`:

```html
<vaadin-combo-box-light>
  <vaadin-text-field></vaadin-text-field>
</vaadin-combo-box-light>
```

I would suggest a computed binding like:

```javascript
_getPositionTarget(inputElement) {
  // Use `[part="input-field"]` if found (for `<vaadin-text-field>` and such)
  return inputElement.shadowRoot && inputElement.shadowRoot.querySelector('[part="input-field"]') ||
    this.inputElement ;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/600)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600#-L3CiR5w2hPZqJj2fDj6:-L8xAR_n2dwL4wWL9D9m:b-886gsx) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I wonder how `<vaadin-combo-box-light>` should act like.

At this point in this case `positionTarget` would be `<vaadin-text-field>`:

```html
<vaadin-combo-box-light>
  <vaadin-text-field></vaadin-text-field>
</vaadin-combo-box-light>
```

I would suggest a computed binding like:

```javascript
_getPositionTarget(inputElement) {
  // Use `[part="input-field"]` if found (for `<vaadin-text-field>` and such)
  return inputElement.shadowRoot && inputElement.shadowRoot.querySelector('[part="input-field"]') ||
    this.inputElement ;
}
```
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600#-L3CiR5w2hPZqJj2fDj6:-L9oUgMA7zVTcFuiXC73:b-dabnph) (no related file):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Apparently, this fix does not work. I just checked out the branch and run demos and I still see the overlay not covering error message or label




Another observation, since in combo box the input is always a `vaadin-text-field`  I would avoid using dom queries and access instead the internal element.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600)*

**Comment by platosha** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600#-L3CiR5w2hPZqJj2fDj6:-L9oYloI8aMYCrItQaXT:blf04v9) (no related file):*
> Another observation, since in combo box the input is always a vaadin-text-field I would avoid using dom queries and access instead the internal element.

True that, I was asking about `<vaadin-combo-box-light>`, not the regular one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600#-L3CiR5w2hPZqJj2fDj6:-L9o_7wqB-g2LGE5xXbm:b-njx7ab) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

> Another observation, since in combo box the input is always a vaadin-text-field I would avoid using dom queries and access instead the internal element.

True that, I was asking about `<vaadin-combo-box-light>`, not the regular one.
</blockquote></details>

Right, for the light version it is also needed that to follow the same pattern of  `position-target="[[_getPositionTarget()]]"` so as the user might extend the element and override the method. There is a `combobox.inputElement` that could be used as default

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/600)*

**Comment by YuriyVaadin** [comment]
Checked with the demos, not yet solving the issue.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 2 of 3 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @samiheikki and @platosha)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/600#-:-LFRG0W_7Jo-tfwYCpfc:b2si9t2)*

**Comment by samiheikki** [comment]
Closing in favor of #732

**Pull request closed without merging**
