### PR TITLE
Remove disabled and autofocus properties, we already have them inherited from control-state-mixin

### PR DESCRIPTION
**Pull request by limonte**
https://github.com/vaadin/vaadin-control-state-mixin/blob/master/vaadin-control-state-mixin.html#L51

https://github.com/vaadin/vaadin-control-state-mixin/blob/master/vaadin-control-state-mixin.html#L79

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/511)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Hmm...why does combo box use control-date-mixin and date picker doesn't?

**Comment by limonte** [comment]
Good question, reported https://github.com/vaadin/vaadin-date-picker/issues/429

**Comment by manolo** [comment]
because, in combo box there was a reported issue to support tabindex, and the implementation was done by extending the control-state. In date-picker that feature was not requested. But I agree both elements need to be aligned, and any other vaadin element that takes focus.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-:-Kttuk5ZEgGTvcCNN78_:b-z4kiae)*

**Comment by manolo** [comment]
This PR is incomplete until you update the analysis file

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 198 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-KtuNBtbQo5__FS6kaID:-KtuNBtbQo5__FS6kaIE:b-o1e6jp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4c335aefc0a927e969068fcb7f047626b6013323/vaadin-combo-box.html#L198)):*
> ```HTML
>              * Set to true to disable this input.
>              */
>             disabled: {
> ```

If you remove disabled from here you need to remove from the drop-down mixin

---

*[vaadin-combo-box.html, line 231 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-KtuNOxW8gPDMt8i9yVc:-KtuNOxW8gPDMt8i9yVd:b-lkc3ng) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4c335aefc0a927e969068fcb7f047626b6013323/vaadin-combo-box.html#L231)):*
> ```HTML
>             },
> 
>             autofocus: {
> ```

We are going to mis this from the api doc unless you tell the analyser the parent mixin with the `@mixes` annotation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-:-KtuNbYaa3GsBJILbinN:b-uaor12)*

**Comment by limonte** [comment]
> This PR is incomplete until you update the analysis file

Done.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 198 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-KtuNBtbQo5__FS6kaID:-Ku3a7h8FmFBV4xr9ynS:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4c335aefc0a927e969068fcb7f047626b6013323/vaadin-combo-box.html#L198)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

If you remove disabled from here you need to remove from the drop-down mixin
</blockquote></details>

Done.

---

*[vaadin-combo-box.html, line 231 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-KtuNOxW8gPDMt8i9yVc:-Ku3a91rUkel_2ipnZWy:bfuchew) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4c335aefc0a927e969068fcb7f047626b6013323/vaadin-combo-box.html#L231)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We are going to mis this from the api doc unless you tell the analyser the parent mixin with the `@mixes` annotation
</blockquote></details>

It's alright: https://i.imgur.com/3Oacnoo.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/511#-:-Ku3aDjlzR54aDDSjRGW:b-e6to5c)*

**Pull request closed without merging**
