### PR TITLE
Update input value async instead of relying on aria-atomic

### PR DESCRIPTION
**Pull request by Saulis**
Fixes VoiceOver reading out focused items when navigating with keyboard.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/358)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/aria.html, line 100 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYsLNebsxgPnXaBSfGT:-KYsLNebsxgPnXaBSfGU:b140g0m) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08bbdb3fbb47aad3a55051da8a5159fb2c9536f8/test/aria.html#L100)):*
> ```HTML
>       });
> 
>       it('should change the input value with atomic change', function(done) {
> ```

Now there is a room for a regression back to synchronous partial updates. Please add a test specifically requiring the async complete input value update instead. I mean:

```javascript
it('should reset the input value asynchronously', function(done) {
  // on selected item change
  expect(getInput().bindValue).to.eql('');
  comboBox.async(function() {
    expect(getInput().bindValue).to.eql('foo');
    done();
  }, 1);
});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by Saulis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/aria.html, line 100 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYsLNebsxgPnXaBSfGT:-KYsTC_qykdiGKCnEAAq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08bbdb3fbb47aad3a55051da8a5159fb2c9536f8/test/aria.html#L100)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Now there is a room for a regression back to synchronous partial updates. Please add a test specifically requiring the async complete input value update instead. I mean:

```javascript
it('should reset the input value asynchronously', function(done) {
  // on selected item change
  expect(getInput().bindValue).to.eql('');
  comboBox.async(function() {
    expect(getInput().bindValue).to.eql('foo');
    done();
  }, 1);
});
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-:-KYsa1xXChiSHes-2oP4:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-combo-box-behavior.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYwwCJFO82Lje7cJf5w:-KYwwCJGYwMBf8qopdD7:b2mvflf) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bbe1ad4e78d28fa5d70eb7e3657569812096f2e0/vaadin-combo-box-behavior.html#L272)):*
> ```HTML
>           this._inputElementValue =  this._getItemLabel(this.$.overlay._focusedItem);
>           this._setSelectionRange();
>         }, 1);
> ```

Why do we need one millisecond here?  is it not enough just an async run?.
To me one means that we need some time to make this work correctly, and zero that we have just to delay until everything in the thread finishes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYwwCJFO82Lje7cJf5w:-KYwyP2_nX0qHR3glDZ2:b-2xgs0m) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bbe1ad4e78d28fa5d70eb7e3657569812096f2e0/vaadin-combo-box-behavior.html#L272)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why do we need one millisecond here?  is it not enough just an async run?.
To me one means that we need some time to make this work correctly, and zero that we have just to delay until everything in the thread finishes. 
</blockquote></details>

Me and @saulis tried it. Zero time is too small and just does not work for macOS VoiceOver. It starts to work same way as a synchronous value change and results in pronouncing partial half-word value updates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYwwCJFO82Lje7cJf5w:-KYwzvVOhfFYFP1iKb0S:b7fitrl) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bbe1ad4e78d28fa5d70eb7e3657569812096f2e0/vaadin-combo-box-behavior.html#L272)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Me and @saulis tried it. Zero time is too small and just does not work for macOS VoiceOver. It starts to work same way as a synchronous value change and results in pronouncing partial half-word value updates.
</blockquote></details>

Mind to include the reason in the comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by Saulis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-behavior.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-KYwwCJFO82Lje7cJf5w:-KYxFCEHBv0zNa0TAoJo:bndcwk7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bbe1ad4e78d28fa5d70eb7e3657569812096f2e0/vaadin-combo-box-behavior.html#L272)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Mind to include the reason in the comment?
</blockquote></details>

Good idea, added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/358#-:-KYxFukRAQOJaX_oaTkW:bnfp4nl)*

**Pull request merged**
