### PR TITLE
Add label property

### LINKED ISSUE #41: Add label
Add label behaving similarily to one in `paper-input` element (a "label" property/attribute).

Consider also how bottom-aligned dropdown should be positioned if there is no label present. It might require some negative margin etc.

Add the label attribute to the existing examples, and mention the use of it in the first example.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #41

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/54)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54)_

**Comment by Saulis** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[vaadin-combo-box.html, line 359 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54#-K3nkQszKbnhsAusevjc:-K3nkQt-znPPEq9a9tkP:674626531) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/81b960c33ccb471aac0363dea34e64f68d8d2a57/vaadin-combo-box.html#L359)):_
This comment could maybe elaborated, stating for example that we are using separate mixins for when the label exists and when not. One option could actually be to document that directly as code: adding an if-clause to check whether the label has changed from `undefined` to a string and vice-versa.

But, I'm also OK by having only the comment here.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54)_

**Comment by tehapo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[vaadin-combo-box.html, line 359 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54#-K3nkQszKbnhsAusevjc:-K3nmClP0OvdQX_TJ0Q_:-1856500868) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/81b960c33ccb471aac0363dea34e64f68d8d2a57/vaadin-combo-box.html#L359)):_
Done. Updated the comment.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54)_

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/54)_

**Pull request merged**
