### PR TITLE
Cancel down for custom clear/toggle buttons also

### LINKED ISSUE #334: Custom clear icon does not work
Custom clear icon does not clear the combo-box input. Doesn't register `tap` event. (See the demo/advanced.html site)

ezgif com-video-to-gif

### LINKED ISSUE #351: Custom “clear” button should restore focus to the input
When using a custom “clear” button element, clicking the button causes the input to lose focus. We should move/restore the focus back to the input when the user clicks/tabs the clear button.

We should also consider if we should automatically add `tabindex='-1'` to custom “clear” and “toggle” buttons, so that keyboard navigation would work the same with the normal and light versions.

Related to #334

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #334 
Fixes #351

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/370)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-:-KaMsgrFzBRIcvHQNiOm:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-combo-box.html, line 337 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-Kagk6xCoqys9kFoAlz4:-Kagk6xDgfhtZW5ZuW5g:bhdn7si) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/465e0179193b565314b13944e409cad2e008a9aa/vaadin-combo-box.html#L337)):*
> ```HTML
>       this._clearElement = Polymer.dom(this).querySelector('.clear-button') || this.$.clearIcon;
>       this.listen(this._toggleElement, 'down', '_preventDefault');
>       this.listen(this._clearElement, 'down', '_preventDefault');
> ```

`unlisten` should be called on detach. It's not a big deal because running preventDefault multiple times does not cause any problem, and probably toggle/clear elements are not being reused out of this component.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 337 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-Kagk6xCoqys9kFoAlz4:-KagsAOnjZxKqp-IKVew:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/465e0179193b565314b13944e409cad2e008a9aa/vaadin-combo-box.html#L337)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`unlisten` should be called on detach. It's not a big deal because running preventDefault multiple times does not cause any problem, and probably toggle/clear elements are not being reused out of this component.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-:-KahBj1Lyhs8ahLVKTBk:bnfp4nl)*

**Comment by manolo** [comment]
Why is license status waiting for being reported in this PR? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-:-KahByg1yxF8d3R7bW7n:b-4vosfe)*

**Comment by tomivirkki** [comment]
Strange...should be just fine.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/370#-:-KahPtN9hFZKBRJG9fwQ:b-z8kyft)*

**Pull request merged**
