### PR TITLE
Extracted sub-sections as separate documents

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes https://github.com/vaadin/components-team-tasks/issues/106

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/219)

### CODE REVIEW

**Comment by platosha** [comment]
The order of pages has changed. Not a blocker for me, but the previous order makes more sense, IMO.

Why change from this:
- Events
- Inside Form
- Custom Input Values
- Object Items
- Styling

to this:
- Events
- Object Items
- Custom Input Values
- Styling
- Inside Form

?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFJk8Oxt4r__BIr4WRi:337128296)*

**Comment by tomivirkki** [comment]
Tried to keep it somewhat aligned with the order of date picker documentation (where Form is currenty the last one)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFJle9nJVvcNbN7PWHs:1088214981)*

**Comment by tomivirkki** [comment]
Switched indexes of Styling and Inside Form as discussed

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFJnragno8u38Y7LWKa:545520677)*

**Comment by platosha** [comment]
:thumbsup: :lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFJokyYE7XgVeBfF_WH:-235834047)*

**Comment by tomivirkki** [comment]
Notice: Also renamed "Basic Usage" to "Getting Started"

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFJvV3hrWWPESnDisIA:1729634037)*

**Comment by jounik** [comment]
Hmm, might be better to align with date picker, and combine the "Getting Started" and "Events" sections into "Handling the Value". That’s what those talk about, right?

**Comment by jounik** [comment]
And while you’re at it, could you replace the documentation image with an updated one, with the new toggle icon?

I’ve mentioned this to @tehapo earlier also, but would it make sense to remove the "screenshot.png" image from the root or the repo, and instead use the image from the "docs/img" folder? Would perhaps be easier to keep in sync.

**Comment by tomivirkki** [comment]
Done. Screenshot also updated.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-:-KFK3wDC5JMCd1NBa6Qj:-1434362613)*

**Comment by platosha** [comment]
Reviewed 9 of 10 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 7 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-KFNanamGeyyU0Eil2qd:-KFNanan4RqJKxh5Tyx5:715319442) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5c5c4106d06345ed2a1d6f4ee0f5445bc638cc81/README.md#L7)):*
The new screenshot width is 387.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219)*

**Comment by tomivirkki** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219#-KFNanamGeyyU0Eil2qd:-KFNgpPUzdy8IRp_CHQJ:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5c5c4106d06345ed2a1d6f4ee0f5445bc638cc81/README.md#L7)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/219)*

**Pull request merged**
