### PR TITLE
Extract icons to its own file

### PR DESCRIPTION
**Pull request by Saulis**
Done to display the original BSD license to iron-icons.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/283)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-icons.html, line 18 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-KNkr42vdskTbcQOWHI8:-KNkr42vdskTbcQOWHI9:-1520777401) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/60282c460d7b6ce2863bcb9df107ed46e22df1ac/vaadin-combo-box-icons.html#L18)):*
> ```HTML
>

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-icons.html, line 18 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-KNkr42vdskTbcQOWHI8:-KNloPKp4vtiLDIMfiOW:-361109955) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/60282c460d7b6ce2863bcb9df107ed46e22df1ac/vaadin-combo-box-icons.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Unclosed element name “<vaadin-combo-box-icons”
</details>
what is unclosed ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-icons.html, line 18 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-KNkr42vdskTbcQOWHI8:-KNlpm4Li6xlUfxZzxUC:1120492714) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/60282c460d7b6ce2863bcb9df107ed46e22df1ac/vaadin-combo-box-icons.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> what is unclosed ? 
</details>
I mean, it begins with the opening <, but ends without the closing >.

This is fixed, apparently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-:-KNlq5AYwB9MbWGVvaGh:1417088721)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-combo-box-icons.html, line 18 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-KNkr42vdskTbcQOWHI8:-KNm1LJbUn6wZNjzdLvi:-1800889324) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/60282c460d7b6ce2863bcb9df107ed46e22df1ac/vaadin-combo-box-icons.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I mean, it begins with the opening <, but ends without the closing >.
> 
> This is fixed, apparently.
</details>
yeah, I saw it fixed and that was my question.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/283#-:-KNm1h7wJsJUkKQW2d3U:1417088721)*

**Pull request merged**
