### PR TITLE
Moved styles from bakery.

### PR DESCRIPTION
**Pull request by Toshegg**
Moved necessary styles from bakery hack to combo-box standard styles to fix https://github.com/vaadin/bakery-app-starter-polymer/issues/65

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/494)

### CODE REVIEW

**Comment by tomivirkki** [comment]
I don't think these changes should be applied to the component's default styles

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2u2Nby2LmoUwUGDq7:b-zf3rsr)*

**Comment by Toshegg** [comment]
@manolo, what do you think?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2uXZ0LYJQm--TpVnS:b-veueaa)*

**Comment by tomivirkki** [comment]
...since they're fixes to theme/app -specific problems, they should be fixed in the correct place.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2ud5S4302aBuunAcC:bsvhw5o)*

**Comment by Toshegg** [comment]
I've discovered that we doesnt have any valo theme for vaadin-combo-box. So, I've decided to move it here.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2uhDkxfrC-vU7nly1:b-5lhijg)*

**Comment by tomivirkki** [comment]
This is not the right place for these styles

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2vHdDFiM3p-EcKVPo:b-2otp20)*

**Comment by Toshegg** [comment]
Manolo told me to move them somewhere from the bakery. I don't know what place will be the best.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2vOdKqCRV5xKvhC63:b-13bp55)*

**Comment by tomivirkki** [comment]
If they're supposed to go in the theme eventually, then we need to keep the styles in bakery until we have the theme. Core element default styles is the last place for theme/app -specific fixes.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq2w491_oCQDYZOw0_X:bjpapiz)*

**Comment by manolo** [comment]
I agree with @tomivirkki element is the last place to have these, I think if we want bakery app work out of the box when applying valo theme, is responsability of the valo theme to prepare everything to make elements display correctly. 
I think we need a proper theme in vaadin-themes for the combo-box element like we are doing with form-layout for instance. 

To me, the bakery app is the reference app for applying a valo theme and everything works without the user having to figure out how to fix margin or align issue.  Only few things should remain in bakery overrides, like the app prefers the arrow icon instead of the calendar icon for the date-picker, or it prefers not having the clear button etc. In principle I think these fixes could go to the valo theme. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/494#-:-Kq3-1QwvBLbuynd0P9x:b-370d2j)*

**Pull request closed without merging**
