### PR TITLE
Switch to using vaadin-overlay

### LINKED ISSUE #472: Switch to using vaadin-overlay

### PR DESCRIPTION
**Pull request by YuriyVaadin**
fixes #472

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/498)

### CODE REVIEW

**Comment by samiheikki** [comment]
Code looks good, but the tests are failing atm.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-Kqb4P503DWUX3T6flSF:b-9fcdgs)*

**Comment by YuriyVaadin** [comment]
vaadin-overlay version was updated to the new release and now should be Ok.

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-KqbUml-J-Vh1PS21AC-:b-ec29th)*

**Comment by tomivirkki** [comment]
The dropdown doesn't open for me when I click the arrow

---

Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-Kqbp52Vup_-1wtzhPx0:-Kqbp52WEiXUqiQ2CJOE:b-twghub) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/dbac0b34776956e6afa2d2758bc11a39d9376024/vaadin-dropdown.html#L111)):*
> ```HTML
> 
>         // Preventing the default modal behaviour of the overlay on input clicking
>         this.$.overlay.addEventListener('outside-click', e => e.preventDefault());
> ```

Event name is wrong.

Also, this looks a bit suspicious: You should be able to close the overlay with outside click, just not when the component is clicked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-KqbpSGbBd106e4SEfDN:b-7cqjbb)*

**Comment by YuriyVaadin** [comment]
Fixed.

---

Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-Kqbp52Vup_-1wtzhPx0:-Kqc172Z3eTIjBqvg5FN:bt2vr1b) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/dbac0b34776956e6afa2d2758bc11a39d9376024/vaadin-dropdown.html#L111)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Event name is wrong.

Also, this looks a bit suspicious: You should be able to close the overlay with outside click, just not when the component is clicked.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-Kqc10k6Py6QuMGRzbd-:bt2vr1b)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-KqcBHt5IKy30Wz8amWJ:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/498#-:-KqcQEEX7dGodoTFiOMt:bnfp4nl)*

**Pull request merged**
