### PR TITLE
Add a CSS property to change overlay width

### PR DESCRIPTION
**Pull request by Saulis**
Relates to #429

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/444)

### CODE REVIEW

**Comment by jouni** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box.html, line 63 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/444#-KjldzDJVW9gg1Q4otgC:-KjldzDJVW9gg1Q4otgD:btk6jou) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ed8a85b4db2f4274fab7d609dc36a117b6e0cd94/vaadin-combo-box.html#L63)):*
> ```HTML
> ----------------|-------------|-------------
> `--vaadin-combo-box-overlay-max-height` | The maximum height of overlay | `65vh`
> `--vaadin-combo-box-overlay-width` | The width of overlay | Input field width
> ```

Maybe change the last part to “Undefined, the width matches the input field width”.

---

*[demo/styling.html, line 47 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/444#-KjleNOP836emkTbE6qq:-KjleNOP836emkTbE6qr:boj48tp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ed8a85b4db2f4274fab7d609dc36a117b6e0cd94/demo/styling.html#L47)):*
> ```HTML
> </body>
> 
> </html>
> ```

Probably not part of this PR, but we should maybe add an example of the overlay-max-height here as well as some other styling examples.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/444)*

**Comment by jouni** [comment]
Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/444)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/444#-:-KkLUC3pw0h_rbtIvVrM:bnfp4nl)*

**Comment by H3dz** [comment]
@manolo was this merged? I can't find it in 2.0.0-beta2

Thanks

**Pull request closed without merging**
