### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/331)

### CODE REVIEW

**Comment by platosha** [comment]
Not sure if the headings here should be in Title Case or in Sentence case, but all of them should have the same case.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ISSUE_TEMPLATE.md, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-KUuupJ9MBi6KyINDRgf:-KUuupJ9MBi6KyINDRgg:b-843jiq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5b619e8347dc0bcf7e102f17cfa3ffcc76c7844d/ISSUE_TEMPLATE.md#L1)):*
> ```Markdown
> ### Description
> ```

BTW: Description header is redundant and noisy. It makes the issue notifications less informative. For example, the first line email preview sometimes looks like “Description: The dropdown is incorrectly...”, instead of “The dropdown is incorrectly placed on iPhone...”.

Would be nice to drop the header and encourage users to start right straight with the description.

---

*[ISSUE_TEMPLATE.md, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-KUuv5EVifF9qbI-kEJB:-KUuv5EVifF9qbI-kEJC:b-phsvqd) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5b619e8347dc0bcf7e102f17cfa3ffcc76c7844d/ISSUE_TEMPLATE.md#L21)):*
> ```Markdown
> 
> ### Browsers Affected
> 
> ```

BTW: Users often don’t respect the checkboxes syntax in the browsers list, nor tick them in the GUI.

I would transform it from the checkbox list to the plain list inside the example comment. Hope this way it would be less confusing and more search-friendly, as the only affected browsers would be listed in the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-:-KUuwALP8H8Ka0X3RYq0:b-vvot3x)*

**Comment by samiheikki** [comment]
ISSUE_TEMPLATE was a direct copy from date-picker's repo. And that was loosely based on Polymer element's issue templates (https://github.com/PolymerElements/paper-input/issues/new). Now I feel that we should follow this pattern in all of our elements, meaning we would have a `Description` as a first title and have browsers with checkboxes. For the  title/sentence case I see your point. I'd go with Sentence case. Opinions?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-:-KUvPxMgzpnA-YGeHanj:b5a2ohr)*

**Comment by manolo** [comment]
Agree, we should be as closed as possible as polymer templates. Users using other elements, would find our templates more familiar.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-:-KUzYnJXDsDh3u04CBER:bkh1fwt)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-KUuupJ9MBi6KyINDRgf:-KUzZgilcoHIwxZPGWij:b-e4x93s) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5b619e8347dc0bcf7e102f17cfa3ffcc76c7844d/ISSUE_TEMPLATE.md#L1)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> BTW: Description header is redundant and noisy. It makes the issue notifications less informative. For example, the first line email preview sometimes looks like “Description: The dropdown is incorrectly...”, instead of “The dropdown is incorrectly placed on iPhone...”.
> 
> Would be nice to drop the header and encourage users to start right straight with the description.
</details>
This field is in all repos in polymer and polymer repos. I consider it's ok.

---

*[ISSUE_TEMPLATE.md, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-KUuv5EVifF9qbI-kEJB:-KUzZro2AxExJr67RV1T:bxesn88) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5b619e8347dc0bcf7e102f17cfa3ffcc76c7844d/ISSUE_TEMPLATE.md#L21)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> BTW: Users often don’t respect the checkboxes syntax in the browsers list, nor tick them in the GUI.
> 
> I would transform it from the checkbox list to the plain list inside the example comment. Hope this way it would be less confusing and more search-friendly, as the only affected browsers would be listed in the issue.
</details>
Users can always remove browsers from the list, or just write their own list just separated by coma. Not a problem I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331)*

**Comment by platosha** [comment]
As for me, it turned out in practice that there are issues with the Polymer’s template. Nothing big, but in the commented aspects having no template was better than having this one, IMO.

We definitely can improve it. I’m OK to improve it later, so no blocks here from my side now. Just wanted to share my thoughts here.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/331#-:-KV-obxHA0oI7DbTuzLc:b-sg9yiq)*

**Pull request merged**
