### PR TITLE
Fix for last item fully visible. fixes #177

### LINKED ISSUE #177: Unable to scroll all items fully visible
Happens in all browsers.

screen shot 2016-02-29 at 11 29 28

See the scrollbar going outside the bottom of the dropdown.

### LINKED ISSUE #180: iron-list padding-bottom not applied properly
`#selector` should have `padding-bottom: 8px`, but it does not get applied with a long list. (short filtered list does seem to work properly)

One fix would be to apply margins to mixin `--iron-list-items-container` instead, but it requires `iron-list` 1.1.x or newer.

image

### PR DESCRIPTION
**Pull request by manolo**
Fixes #177 
Fixes #180 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/209)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/209)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/209#-:-KEjt5iRr7-qsmTGsxUp:980077423)*

**Comment by jounik** [comment]
Fixes #180 also I believe.

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/209)*

**Pull request merged**
