### PR TITLE
Feature/disabled read only

### LINKED ISSUE #141: Disabled and read-only
Add a disabled and read-only properties (like in paper-input).

The dropdown should not be openable and the dropdown toggle and clear input buttons should be hidden when either property is set.

### PR DESCRIPTION
**Pull request by samiheikki**
fixes #141

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/145)

### CODE REVIEW

**Comment by tehapo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-dropdown-behavior.html, line 45 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKZiIoYjpbk875IP5n:-KAKZiIoYjpbk875IP5o:1395485043) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L45)):*
Typo in the comment. Change `beign` to `being`.

---

*[vaadin-dropdown-behavior.html, line 46 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKZq-tCHPXkoJSRowg:-KAKZq-tCHPXkoJSRowh:-189767798) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L46)):*
Missing white-space after `if`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by tehapo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-dropdown-behavior.html, line 44 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAK_c7morLrv30LWWaw:-KAK_c7morLrv30LWWax:-2008804882) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L44)):*
I would actually rewrite the logic of this method to check `if (!this.disabled && !this.readonly) { ... }` so that it would not require an explicit `return` at all.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by tehapo** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/toggling-dropdown.html, line 18 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKaSmRwsoQuhwnUhIA:-KAKaSmSNoo_zgkElSAk:1956184525) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/toggling-dropdown.html#L18)):*
We normally use double-quotes (") on HTML attributes.

---

*[vaadin-combo-box.html, line 535 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKask6FKHN7AgWFfal:-KAKask6FKHN7AgWFfam:1558686960) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-combo-box.html#L535)):*
Line break accidentally removed?

---

*[vaadin-dropdown-behavior.html, line 136 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKala3opUp8d42cqkH:-KAKala3opUp8d42cqkI:1558686960) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L136)):*
Line break accidentally removed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[test/form-input.html, line 33 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYxBjukn4zBRMAExyp:-KAYxBjukn4zBRMAExyq:76476928) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/form-input.html#L33)):*
I would add a `beforeEach` function here, and set the `required`, `disabled`, and `readonly` properties inside the tests (also the old ones) with normal setters.

---

*[test/form-input.html, line 58 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYxY-_bXWbD2UG9xxc:-KAYxY-_bXWbD2UG9xxd:13965941) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/form-input.html#L58)):*
Could add a separate test testing that `paper-input-container` has `disabled` attribute.

---

*[test/form-input.html, line 60 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYwg5irJqOiY1-HXkN:-KAYwg5irJqOiY1-HXkO:1015548315) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/form-input.html#L60)):*
`comboBox.$.input` could be simpler (also on the old tests) (just a matter of taste, I'll leave it up to you to decide.)

---

*[test/toggling-dropdown.html, line 19 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYtvLnHktmPr6JXm3p:-KAYtvLo3wJIZhShiypa:330582691) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/toggling-dropdown.html#L19)):*
You don't actually need to define the `disable` and `readonly` properties here at all, it's enough to set them in the `beforeEach` functions.

---

*[test/toggling-dropdown.html, line 179 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYwNh406GUTGEeSyuU:-KAYwNh406GUTGEeSyuV:698937249) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/toggling-dropdown.html#L179)):*
Would just `combobox.$.input.fire('tap')` work?

---

*[test/toggling-dropdown.html, line 195 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYwB0U6E9U3FyJw27E:-KAYwB0U6E9U3FyJw27F:698937249) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/toggling-dropdown.html#L195)):*
Would just `combobox.$.input.fire('tap')` work?

---

*[vaadin-dropdown-behavior.html, line 19 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAYyOhrBazuciCfQCtT:-KAYyOhrBazuciCfQCtU:1860495247) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L19)):*
I think we should have these properties defined in the combobox itself, because they only affect the toggle icon, which is currently defined there. Remember to add documentation for these properties, you can seek for inspiration from `paper-input` docs if needed.

---

*[vaadin-dropdown-behavior.html, line 44 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAK_c7morLrv30LWWaw:-KAYyw5DUgA9kbwEm89G:28711525) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L44)):*
I'd say we don't need to prevent the dropdown from opening using JS at all. It's enough prevent user actions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[test/toggling-dropdown.html, line 18 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAKaSmRwsoQuhwnUhIA:-KAZ8DmAskeoqeB-rtnQ:-1377121268) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/test/toggling-dropdown.html#L18)):*
If there’re no bindings used, as Sauli suggests, there’s no need to use `is="dom-template"` for the wrapping `<template>` as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[vaadin-combo-box.html, line 206 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAZg2_rA1MoM8v8tkkP:-KAZg2_rA1MoM8v8tkkQ:107281960) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bb44376e87d86eaf6cd8d1c8373f557b8e833ec3/vaadin-combo-box.html#L206)):*
Could you move these back to `vaadin-dropdown-behavior.html`? kthx :+1: 

---

*[vaadin-dropdown-behavior.html, line 44 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-KAK_c7morLrv30LWWaw:-KAZfT5SmtLK0l3e2oZa:-988039821) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4acfc21fb8284317297f1cd14ea13775c894670d/vaadin-dropdown-behavior.html#L44)):*
After discussing with Sami, it feels cleaner to check for disabled and readonly statuses in `open` function instead of replacing the `on-tap` handlers on `<input>` and `<label>` elements with a separate function. 

This will effectively prevent opening the overlay using `combobox.open()`, but we can deal with that later if it becomes an issue to someone.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145)*

**Comment by Saulis** [comment]
:lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/145#-:-KAcw_96vWVcs0bJvLIi:980077423)*

**Pull request merged**
