### PR TITLE
Feature/overlay alignment

### LINKED ISSUE #70: Dropdown alignment
The dropdown item list might, in some cases, be better aligned above the input field, or next to it on the left or right side.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #70

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/151)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/corner-cases.html, line 29 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAe7CzCjQuOEsqM3dyk:-KAe7CzCjQuOEsqM3dyl:-598741520) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/demo/corner-cases.html#L29)):*
This example seems like unfinished: 
- why is this combobox commented.?
- why this demo is not in the index.html ?

---

*[demo/corner-cases.html, line 41 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAe7WJgkFFBA_1BhB4P:-KAe7WJhx5SF0LPEWUA1:-81492541) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/demo/corner-cases.html#L41)):*
I see this difficult to follow, I'd rather something simpler like:

```
function openDialog1(e) {
     dialog1.open()
}
function openDialog2(e) {
     dialog2.open()
}

```
we don't have to transverse the dom in each click

---

*[test/overlay-position.html, line 114 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeInM3vyi9Wv-VvpBh:-KAeInM3vyi9Wv-VvpBi:404284597) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/test/overlay-position.html#L114)):*
Is it possible to use someway overlay.iosDevice property so as we use/test the same ios detection algo ?

---

*[test/overlay-position.html, line 115 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeImIq1moMsSwRExUG:-KAeImIq1moMsSwRExUH:958763155) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/test/overlay-position.html#L115)):*
use describeSkipIf(ios ....)

---

*[vaadin-combo-box-overlay.html, line 113 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeJ79cWaRS1XWLSyqT:-KAeJ79cWaRS1XWLSyqU:1219259966) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/vaadin-combo-box-overlay.html#L113)):*
shouldn't be private ?
It's not used in the overlay component, why not to move it to the combo box ?

---

*[vaadin-dropdown-behavior.html, line 98 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeK5MNHQ5FtnDkT7Wm:-KAeK5MNHQ5FtnDkT7Wn:-1786735567) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/vaadin-dropdown-behavior.html#L98)):*
I feel like this should be moved to the overlay, if we have  there the iosDevice property. 
Because this could be reused if some component reuses the overlay element.
Something like:

overlay.setAlignment(this.$.input) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by samiheikki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/corner-cases.html, line 29 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAe7CzCjQuOEsqM3dyk:-KAhvO87zFFFHDHtA1kY:-1620174438) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/demo/corner-cases.html#L29)):*
I finished with example. Demo is not in index.html because this is not used for showing how to use combo-box. This is used for visual-testing in corner-cases. Developers can add their own corner cases in this file.

---

*[test/overlay-position.html, line 114 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeInM3vyi9Wv-VvpBh:-KAhuu2Ua7Qku13lHrK3:1757334338) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/test/overlay-position.html#L114)):*
combo-box is created beforeEach so overlay doesn't probably exist yet. 
Algo is the same in both cases: `/iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream`

---

*[vaadin-combo-box-overlay.html, line 113 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeJ79cWaRS1XWLSyqT:-KAhwkchlULOCZlN16Fc:-1893442958) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/vaadin-combo-box-overlay.html#L113)):*
Changed to private. Left it in combo-box-overlay as I moved `_setOverlayAlignment` to combo-box-overlay.html.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r2, 1 of 4 files at r3, 1 of 4 files at r4, 3 of 4 files at r5.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demo/corner-cases.html, line 44 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAiPCSRdSE0JrGLt0Wk:-KAiPCSSKJE5lP2OpXMM:73035291) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/485de179185b04d7ef5d266c155ce1448afacc45/demo/corner-cases.html#L44)):*
Nit: I would remove the if null here, we don't expect this function be called incorrectly since we wrote the two cases. 

    document.getElementById(id).open()

---

*[vaadin-combo-box-overlay.html, line 113 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeJ79cWaRS1XWLSyqT:-KAiPgpVQOhxk1_lIZLf:-1749871810) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/vaadin-combo-box-overlay.html#L113)):*
much better

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-dropdown-behavior.html, line 95 \[r8\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAjafdGTxNoLKj-1uFE:-KAjafdGTxNoLKj-1uFF:-1307691696) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bb04b8240d4c83f586298c159f1ae8ce2301709/vaadin-dropdown-behavior.html#L95)):*
This doesn't quite work, the `_setOverlayAlignment` isn't called on window resize if you debug it.

I would suggest, that instead of adding a separate add event listener here, you make use of the existing listener inside the overlay and call `_setOverlayAlignment()` & `_setOverlayPosition` from there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by samiheikki** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-dropdown-behavior.html, line 95 \[r8\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAjafdGTxNoLKj-1uFE:-KAnFPP5vqD-oHYSTuBR:-499146022) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7bb04b8240d4c83f586298c159f1ae8ce2301709/vaadin-dropdown-behavior.html#L95)):*
Done!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by manolo** [comment]
Reviewed 2 of 4 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by samiheikki** [comment]
Reviewed 1 of 2 files at r6, 1 of 4 files at r8, 1 of 2 files at r9, 1 of 2 files at r11.
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-overlay-behavior.html, line 62 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAn_tUVhM4Bpi6D-rT2:-KAn_tUVhM4Bpi6D-rT3:1308430995) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28367f62e3638502aadef634cea2838fd373412b/vaadin-overlay-behavior.html#L62)):*
This function is no longer used? Should it be removed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/overlay-position.html, line 114 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAo6SVtCmHEVW6JJWQq:-KAo6SVuk4aF-k6-ZXec:-691094811) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28367f62e3638502aadef634cea2838fd373412b/test/overlay-position.html#L114)):*
We can now run these tests for iOS also.

---

*[vaadin-overlay-behavior.html, line 62 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAn_tUVhM4Bpi6D-rT2:-KAo67dcOGTDuWFfxf6l:-767323200) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28367f62e3638502aadef634cea2838fd373412b/vaadin-overlay-behavior.html#L62)):*
Yes, we can remove this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r6, 1 of 4 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 2 of 2 files at r11.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/overlay-position.html, line 114 \[r11\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAo6SVtCmHEVW6JJWQq:-KAoB-Q5V5NMVttLrAI9:-966881964) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28367f62e3638502aadef634cea2838fd373412b/test/overlay-position.html#L114)):*
I'll take that back, we it doesn't open above the input because of Safari scrolling the input.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by samiheikki** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/corner-cases.html, line 41 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAe7WJgkFFBA_1BhB4P:-KAt0Y2JZVMlJppgYNou:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/demo/corner-cases.html#L41)):*
Done.

---

*[demo/corner-cases.html, line 44 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAiPCSRdSE0JrGLt0Wk:-KAsn0-MRZ4zTbcSWB0W:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/485de179185b04d7ef5d266c155ce1448afacc45/demo/corner-cases.html#L44)):*
Done.

---

*[test/overlay-position.html, line 115 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeImIq1moMsSwRExUG:-KAsmyqEzGT95-QkB3VY:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/test/overlay-position.html#L115)):*
Done.

---

*[vaadin-dropdown-behavior.html, line 98 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAeK5MNHQ5FtnDkT7Wm:-KAt08p8la6MdB9hddh3:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/bfdbafae17cd69753eaab20ebbabda1d102fb1c1/vaadin-dropdown-behavior.html#L98)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by tomivirkki** [comment]
*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtIbnDCjxve91t3a-U:-1834681149) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
What's the purpose of wrapping the combo-boxes in dialogs? Both of the dialogs are centered, the other one is modal but both wrap identical combo-boxes. I don't get how this demos the feature build in this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by platosha** [comment]
Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-overlay-behavior.html, line 29 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtJQsvCl8q-GunuOrO:-KAtJQsw1waJf9mHGW0z:-123030070) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/vaadin-overlay-behavior.html#L29)):*
Would it make sense to call it `alignedAbove` and make read-only? This property is a state indicator flag, but seems not to be useful for setting the alignment from the outside.

There’s no proper support of setting this property from the outside currently. It would probably get overwritten soon after.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by tomivirkki** [comment]
Opened the demo and the dropdown only shows 2 lines even thought there's lots of room available https://www.dropbox.com/s/wwzf6mvcx0kmjnt/Screenshot%202016-02-19%2013.32.56.png?dl=0

---

Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-:-KAtKMSnYoBpGsGmoQyU:-305502931)*

**Comment by Saulis** [comment]
Yes, the <body> ends there, so it's a feature. We expect that in real use cases the body would actually have some other content. We could maybe add height: 100vh for the body in corner-cases.html

---

Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtKqJ3xw6oUtGIEz05:1494226082) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
This file isn't meant as a public demo, but rather to manually test how combo-box works inside a paper-dialog, which we have had a few problems with.

---

*[vaadin-overlay-behavior.html, line 29 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtJQsvCl8q-GunuOrO:-KAtL772QomP5oyr7kb_:-503368878) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/vaadin-overlay-behavior.html#L29)):*
This property was actually originally set from the vaadin-combo-box, as it is currently, we could maybe even make it private?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-:-KAtLNKvaAz01wSTIqK0:-1286562035)*

**Comment by Saulis** [comment]
"Yes, the `<body>` ends there..."

---

Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-:-KAtLmGjH81kt8YhZTo0:1136232099)*

**Comment by platosha** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-overlay-behavior.html, line 97 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtLeJERNURvyoE_hY2:-KAtLeJERNURvyoE_hY3:-1690263355) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/vaadin-overlay-behavior.html#L97)):*
Not a merge-blocker for me, but we should consider renaming `_setOverlayPosition` and `_setOverlayAlignment`:

1. All the methods here are related to overlay, no need to mention `Overlay` it in method names.

2. The `_set` prefix usually means that you can provide the new value in the parameter, but that's not the case here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by tomivirkki** [comment]
*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtM6ukRUO4htgLxt0v:-1860279175) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
It shouldn't be included in the PR then. Also it adds an otherwise unnecessary dependency to the component.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by platosha** [comment]
Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-overlay-behavior.html, line 29 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtJQsvCl8q-GunuOrO:-KAtMrWQzOCw-snAQOWd:-1504763431) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/vaadin-overlay-behavior.html#L29)):*
Good idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtNEzp6zlilc9Wt_tc:736165663) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
We definitely want to have this test file in the repo for manual testing. Maybe it would be better to place it under `test` folder? Dependency to `paper-dialog` is a devDependency, so it shouldn't be a problem.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by tomivirkki** [comment]
*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtOPiYMMyjX6oHSJPW:239012467) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
A file that's meant for being a playground for testing some random corner-case really doesn't belong in master. By all means have a separate branch for debugging/investigating that issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Squashed and rebased to master.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/corner-cases.html, line 25 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtIbnCVmyJlCy176JW:-KAtRsCHofaDk6mLxRM0:53241050) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/demo/corner-cases.html#L25)):*
OK, maybe the file name isn't the best here – it's meant for manual regression testing to cover possible issues our automated tests might miss. But you're right, I'll remove the file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-:-KAtXPbMAauJUy0U-uNa:-595202163)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-behavior.html, line 85 \[r13\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtXh6jnDHhIKnLOwJu:-KAtXh6jnDHhIKnLOwJv:-129431468) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/23098fdd2d2f5ba7b43a5d7beaace51672f7c113/vaadin-dropdown-behavior.html#L85)):*
This call was unnecessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box.html, line 496 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtbMOBYVHdj6a56_UG:-KAtbMOCyac_Ocn1lAWu:1445396845) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e003a0bae5e4b0700a1878b532a888bb6db9b4e7/vaadin-combo-box.html#L496)):*
Hmm...in which cases should filtering affect position? Does it mean that the dropdown can jump between above/below while filtering?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 496 \[r14\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151#-KAtbMOBYVHdj6a56_UG:-KAtcxGA52PXIrpGjHcr:1891290795) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/e003a0bae5e4b0700a1878b532a888bb6db9b4e7/vaadin-combo-box.html#L496)):*
The comment is a bit inaccurate, this call is to make sure the overlay height is updated correctly after the amount of list items is rapidly changing.

The overlay above/below alignment doesn't take the height of the overlay into account at all, so in practice the alignment can change only when scrolling or resizing the window.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by platosha** [comment]
Reviewed 3 of 7 files at r14, 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Comment by platosha** [comment]
Reviewed 1 of 7 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/151)*

**Pull request merged**
