### PR TITLE
Add link to item templates in styling doc. Fixes #384

### LINKED ISSUE #384: The styling chapter should link or describe item styling

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/397)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/vaadin-combo-box-styling.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397#-KcXbLVWnOR8xsKvrn_S:-KcXbLVWnOR8xsKvrn_T:bnbz85c) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7de35ac221f6c3a2c2d438f1c2666afc5ec66ea4/docs/vaadin-combo-box-styling.adoc#L15)):*
> ```AsciiDoc
> The [propertyname]#vaadin-combo-box-overlay-max-height# property overrides the default maximum height of the overlay.
> 
> In addition, you can customize how items are displayed by using templates as it is described in this link:vaadin-combo-box-item-template.html[document].
> ```

I suggest to use more descriptive link text: `as described in the link:vaadin-combo-box-item-itemplate.html[Custom Item Template guide].`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-combo-box-styling.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397#-KcXbLVWnOR8xsKvrn_S:-KcXd_U2XHwKC3Aatoj7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7de35ac221f6c3a2c2d438f1c2666afc5ec66ea4/docs/vaadin-combo-box-styling.adoc#L15)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I suggest to use more descriptive link text: `as described in the link:vaadin-combo-box-item-itemplate.html[Custom Item Template guide].`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397)*

**Comment by limonte** [comment]
:lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397#-:-KcXeH20QWDtAWiZolez:b-uwkowd)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/397#-:-KcXp7p3UCX_O2yc1NdC:bnfp4nl)*

**Pull request merged**
