### PR TITLE
Document need of item-label-path in templates. Fixes #381

### LINKED ISSUE #381: Clarify using `item-label-path` with item templates
When using object items and item templates, setting `item-label-path` is still often necessary, since it sets the text displayed in the input field and used for filtering.

This should be mentioned in the documentation.

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/396)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-KcXnz1Jfpux07Mbnq2n:-KcXnz1Kj7kNKKVY9IhE:b-1yh3qp) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1d7fd8abf39da6df6f871c2ee58973fd6ef8ba3b/vaadin-combo-box-behavior.html#L109)):*
> ```HTML
>        * input, i.e., for filtering and selecting items.
>        *
>        * This property is still needed when using item templates, since it is used
> ```

Maybe start with `When using item templates`? It would sound more connected to the use case, IMO.

---

*[docs/vaadin-combo-box-item-template.adoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-KcXoP_lqhOpr-wAcsPj:-KcXoP_lqhOpr-wAcsPk:bihrswx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1d7fd8abf39da6df6f871c2ee58973fd6ef8ba3b/docs/vaadin-combo-box-item-template.adoc#L16)):*
> ```AsciiDoc
> 
> [NOTE]
> Setting the `item-label-path` property is necessary when using object as items, and item templates. This is because the value specified by the `item-label-path` property is displayed in the input field when the item is selected, and it's also used for filtering.
> ```

Same suggestion to start with describing use case here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-KcXnz1Jfpux07Mbnq2n:-KcYN6_9BAv4STLQnzVY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1d7fd8abf39da6df6f871c2ee58973fd6ef8ba3b/vaadin-combo-box-behavior.html#L109)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe start with `When using item templates`? It would sound more connected to the use case, IMO.
</blockquote></details>

Done.

---

*[docs/vaadin-combo-box-item-template.adoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-KcXoP_lqhOpr-wAcsPj:-KcYOCttQFYwM8yJ0_p1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1d7fd8abf39da6df6f871c2ee58973fd6ef8ba3b/docs/vaadin-combo-box-item-template.adoc#L16)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Same suggestion to start with describing use case here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-:-KcYSmsP52we-ZifX5Ut:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/396#-:-KcbbgkZtEhoOkuBlG2t:bnfp4nl)*

**Pull request merged**
