### PR TITLE
Add CSS property for overlay max-height.

### LINKED ISSUE #181: Add a custom property for overriding overlay max-height
Need a custom css property for overriding the `#scroller` `max-height` property, which is `65vh` by default.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #181

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/186)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186#-KBsiUsW3QrvdIDK8Gnc:-KBsiUsW3QrvdIDK8Gnd:796452349) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9adf5eae52a6383de6bb5c7bc52bac4ba5b49767/vaadin-combo-box.html#L34)):*
How about adding a "Default" column, like was done with `vaadin-date-picker`?
https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L24-L50

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186)*

**Comment by Saulis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186#-KBsiUsW3QrvdIDK8Gnc:-KCF6r50Wn7i_T1YcKVq:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9adf5eae52a6383de6bb5c7bc52bac4ba5b49767/vaadin-combo-box.html#L34)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186#-:-KCFOuuP9AQiWbbcqsb7:1417088721)*

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/186)*

**Pull request merged**
