### PR TITLE
Apply Material Design styles

### LINKED ISSUE #35: Material Design styling
Implement the Material Design styling designed in ticket vaadin/components-team-tasks#22

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #35

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/42)

### CODE REVIEW

**Comment by Saulis** [comment]
I restarted the Travis build, SauceLabs devices had been timing out. I guess it's `that` time of the month again, sigh.

Styles look awesome :+1


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[vaadin-combo-box.html, line 28 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ue3XgbrVu6qJQ-49p)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L28)):</sup>
Are these styles intentionally combo-box specific (not generic to all adaptive overlays)?


---

<sup>**[vaadin-combo-box.html, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2udqky04_cg48y6_rd)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L40)):</sup>
This selector targets the same element as the one below.


---

<sup>**[vaadin-combo-box.html, line 57 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ufUqT7Vg8EMa6YbWV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L57)):</sup>
These should be limited to non-fullscreen mode. On fullscreen focus doesn't matter and scrolling the list will apply hover styles to the item at touch position .


---

<sup>**[vaadin-combo-box.html, line 74 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ubH2cu0-lRcNNsg6M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L74)):</sup>
This makes the component appear on top of the dropdown content on fullscreen (tested with IOS simulator)


---

<sup>**[vaadin-combo-box.html, line 309 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2uiRpNaZb9egYSx_9-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L309)):</sup>
"open" style is only needed internally. Should be restricted inside the local dom: <paper-input-container dropdownopen$=[[opened]] for example... Unless it's decided we want to expose "open" style


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 309 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2uiRpNaZb9egYSx_9-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L309)):</sup>
or maybe directly to iron-icon <iron-icon rotated$=[[opened]] ...>


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 309 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2uiRpNaZb9egYSx_9-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L309)):</sup>
damn reviewable.....tried to type <iron-icon rotated$=[[opened]]


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tehapo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[vaadin-combo-box.html, line 28 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ue3XgbrVu6qJQ-49p)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L28)):</sup>
Yes, this is intentional. The idea was to keep the adaptive overlay without too much styling in order to make it easier to reuse with future components. We can add/move some styles there later if needed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tehapo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[vaadin-combo-box.html, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2udqky04_cg48y6_rd)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L40)):</sup>
Done.


---

<sup>**[vaadin-combo-box.html, line 57 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ufUqT7Vg8EMa6YbWV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L57)):</sup>
Done.


---

<sup>**[vaadin-combo-box.html, line 74 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ubH2cu0-lRcNNsg6M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L74)):</sup>
Done. Applied z-index to full screen dropdown in vaadin-adaptive-overlay.


---

<sup>**[vaadin-combo-box.html, line 309 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2uiRpNaZb9egYSx_9-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L309)):</sup>
Done. Thanks, the suggested version is a lot better! :+1: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by jounik** [comment]
<sup>**[vaadin-combo-box.html, line 74 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ubH2cu0-lRcNNsg6M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L74)):</sup>
This happens in desktop Safari as well.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by jounik** [comment]
One more issue I noticed: the keyboard highlight and mouse pointer highlight should be one and the same, so hovering with the mouse should clear any previous keyboard highlight from the list. Now you get two highlighted rows.

**Comment by tomivirkki** [comment]
Noticed one more issue, reproduces on fullscreen Android at least: Open the example with many items (Automatic sizing and alignment), scroll all the way to the end, keep scrolling and the input field slides out of the viewport. You can notice two scrollbars on the right while this happens.


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by Saulis** [comment]
@jounik 
>> The keyboard focus should also move along with the mouse highlighting, so you can continue navigating with the keyboard from where you left off with the mouse.

I was actually thinking about this when implementing the keyboard navigation, but came to a conclusion that there might be more cons than pros. Technical cons being mostly related with `vaadin-grid` where we need to re-render the rows in order to change the classes on highlight change. This would then happen every time a row is hovered on. 

Also, I was a bit worried if changing the highlighted row on mouse hover could cause some accidental selection changes. For example you're just about to hit enter to select a row when your hand touches the mouse and accidentally moves the selection.

What I originally had in mind was to have visually clearly separate styles for mouse hover and keyboard highlighting. For example using background color for hover and border color for keyboard.

I guess it boils down to UX - do people find it more natural to use keyboard and mouse for navigating simultaneously (which implies having same highlighting for both devices) or separately? How much people actually move their hands between the keyboard and mouse/touchpad? These are, again, them big questions that we just need to try out to find the answer :smiley:

**Comment by tehapo** [comment]
The Android issue mentioned by @tomivikki is now fixed. :iphone: 

Regarding the keyboard focus and mouse hover effect, we decided to keep the two separate highlights still there. We might need to revisit this UX issue later.

This PR is now ready for another round of review. :rocket: 


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[vaadin-combo-box.html, line 74 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42#-K2ubH2cu0-lRcNNsg6M)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9e6baa05ebb998d7842d8abff8cc8d3abf0f7c27/vaadin-combo-box.html#L74)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tehapo** [comment]
Oops, sorry @tomivirkki about the typo in your name. :laughing: 


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
I don't know if it's related but the vertical scrollbar gets hidden under a focused/hovered item (Chrome on os x). Other than that lgtm.


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by jounik** [comment]
🏅 for @tehapo for using emojis in comments :smiley: 

We discussed with @tehapo also about the keyboard vs. mouse highlight styles, and decided that it’s something we want to fix, but it should be done in a separate patch, and the current styling is the least confusing/dangerous to the end user.

**Comment by tehapo** [comment]
@tomivirkki Fixed the scrollbar + focus/hover issue by applying flexbox layout also in non-fullscreen mode (which is actually the case also in master branch).


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Comment by Saulis** [comment]
:+1 from me. Clicking on a already selected item toggles the selection and somehow breaks the keyboard navigation. This is an `iron-list` issue and wouldn't do anything about it at this point. :shipit: 


---

Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/42)

**Pull request merged**
