### PR TITLE
Added support for HTML forms (fixes #11)

### LINKED ISSUE #11: Support HTML forms
- Use the approach as Polymer elements (iron-form)
- Implement `Polymer.IronFormElementBehavior`
- `iron-form` could be used in testing (`serialize()` maybe?)

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/14)

### CODE REVIEW

**Comment by Saulis** [comment]
I think it should have an example of using inside `iron-form` otherwise :+1: 


---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/14)

**Comment by tomivirkki** [comment]
Added an example


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/14)

**Comment by jounik** [comment]
So you always need to use `iron-form` for it to work, right?

**Comment by tomivirkki** [comment]
Vaadin-combo-box local DOM does contain an <input> that's decorated with the 'name' and 'required' properties as attributes so it can be used in a plain HTML form also; as long as native shadow DOM isn't enabled. That's the case with <paper-input> also.

Note: There was some issues with this PR regarding the use in and <iron-form>, fixed in https://github.com/vaadin/vaadin-combo-box/pull/18

**Comment by jounik** [comment]
So if Iʼm using native shadow DOM, does it work with iron-form at least?

**Comment by tomivirkki** [comment]
Sure does. The shadow dom limitation only concerns use in a plain HTML form (non iron-form)

**Pull request merged**
