### PR TITLE
Replace deprecated --default-primary-color with --primary-color

### PR DESCRIPTION
**Pull request by tehapo**
Connects to vaadin/components-team-tasks#116

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/193)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-KDOgHaKJiuAN6Gma0hT:-KDOgHaLpxTWg-crnF8x:443453729) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7c6aa8b563f0b7ea3d9eff8fb916ba568ea716e9/vaadin-combo-box-overlay.html#L54)):*
I would add a second parameter with the default color if --primary-color was not available

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-overlay.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-KDOgHaKJiuAN6Gma0hT:-KDOgczVrXwNt5X_wKmS:-604100258) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7c6aa8b563f0b7ea3d9eff8fb916ba568ea716e9/vaadin-combo-box-overlay.html#L54)):*
I'd leave it like this as --default-primary-color is deprecated and --primary-color is the new default.

To be precise, this _should_ use a custom property and have --primary-color as the default. Like var(--vaadin-upload-item-selected-color, --primary-color) but I guess it's out of the scope of this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-:-KDOmw77D0G3_g89_bau:1417088721)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-combo-box-overlay.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-KDOgHaKJiuAN6Gma0hT:-KDRuOi7g5TED8ndgBhG:147661198) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7c6aa8b563f0b7ea3d9eff8fb916ba568ea716e9/vaadin-combo-box-overlay.html#L54)):*
I remember a discussion about having default fallback values.

At that time it was decided that those are not strictly needed here, as we already include `paper-input-container` which imports `paper-styles/default-theme` -> some `--primary-color` is always available.

But Tomi's suggestion is still a good idea to add at some point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-:-KDRyfk67iIoPmU2-dpr:1417088721)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193#-KDOgHaKJiuAN6Gma0hT:-KDS4GxeObOfsYPwzdhm:-1856019850) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7c6aa8b563f0b7ea3d9eff8fb916ba568ea716e9/vaadin-combo-box-overlay.html#L54)):*
yep that is a different task to this PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/193)*

**Pull request merged**
