### PR TITLE
Prevent form submit when selecting a value with enter key

### LINKED ISSUE #47: Form submit should be prevented when selecting an item using the enter key
Currently, in our “Using as a form field” demo, if you select an item using the keyboard, the form is submitted immediately at the same time when the item is selected.

The form should only be submitted if the items list is not open and the user pressed the enter key – in other words, the default browser action should be prevented when the user selects an item from the list using the keyboard.

The form SHOULD be submitted when you press the enter key if the list is closed and the focus is in the input.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #47

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/57)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 82 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57#-K41Wtjv2tFzRKZ0AEvi:-K41Wtjv2tFzRKZ0AEvj:580718202) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0329cdfb697dee2fab0281b308ec122ff70d8b36/test/form-input.html#L82)):*
As we're testing enter behaviour here, these should rather reside under keyboard.html test suite

---

*[test/form-input.html, line 103 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57#-K41XXb5W6vQTCI91rXH:-K41XXb5W6vQTCI91rXI:874986667) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0329cdfb697dee2fab0281b308ec122ff70d8b36/test/form-input.html#L103)):*
comboBox and input could also be extracted as common variables in beforeEach

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57)*

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 82 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57#-K41Wtjv2tFzRKZ0AEvi:-K41ZEOB5FkVq2q1HjjR:-882266259) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0329cdfb697dee2fab0281b308ec122ff70d8b36/test/form-input.html#L82)):*
I guess you're right. On the other hand: , this is related to the issue of pressing enter when using the combobox inside a form. Which one should it be? :smile: 

---

*[test/form-input.html, line 103 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57#-K41XXb5W6vQTCI91rXH:-K41Zt3eSuWQTa6XNR_W:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0329cdfb697dee2fab0281b308ec122ff70d8b36/test/form-input.html#L103)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57)*

**Comment by tomivirkki** [comment]
*[test/form-input.html, line 82 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57#-K41Wtjv2tFzRKZ0AEvi:-K41jlFRIdOwF3756i6J:-609951940) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0329cdfb697dee2fab0281b308ec122ff70d8b36/test/form-input.html#L82)):*
Yeah, was wondering if the problem occurs more generally than just in an html form. For example inside a dialog popup where enter key is the default action for "ok". Didn't seem to be a problem with paper-dialog at least (tried placing a combo-box inside the "Dialog with actions" popup at https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/57)*

**Pull request merged**
