### PR TITLE
Use screenshot from vaadin.com

### PR DESCRIPTION
**Pull request by limonte**
The old one is dead with the `docs` folder.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/546)

### CODE REVIEW

**Comment by limonte** [comment]
@tomivirkki is it safe enough to depend on vaadin.com image URL?

**Comment by tomivirkki** [comment]
Good question...Safest bet would be to copy the image to combo-box repo. Or even better, make a nice animated gif like the (outdated) one in grid Readme ;)

**Comment by limonte** [comment]
> Safest bet would be to copy the image to combo-box repo.

Copied.

> Or even better, make a nice animated gif like the (outdated) one in grid Readme ;)

Let's make the cool gif after Valo stable :)

**Comment by platosha** [comment]
The new screenshot is blurry and clipped from the right edge.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/546#-:-KvBpiQzWze4zm4g4Vkg:b-5ta08c)*

**Comment by tomivirkki** [comment]
I think the theme in the image isn't actually Valo. The image also promises more than what the element delivers :)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/546#-:-KvBpwajBvgJwk-NiQcI:bkwjqg0)*

**Pull request closed without merging**
