### PR TITLE
Fix for input value bottom cutting off in IE11

### LINKED ISSUE #130: Input value bottom gets cut off in IE11
For values with letters like `y`, the bottom half gets cut off. Seems to happen only on IE11 (tested on Windows 7)

image

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #130

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/144)

### CODE REVIEW

**Comment by jounik** [comment]
Just checking, that I understand this right: this only happens in vaadin-combo-box, and not in paper-input? Just wondering why we need a patch for it in our element, when it seems like it’s caused by paper-input or paper-input-container.

**Comment by Saulis** [comment]
At least it's not happening in the `paper-input` demos on IE11. ..

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/144#-:-KAZ2Q7TTrIe990ivPQ8:1025113059)*

**Comment by platosha** [comment]
Works for me.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/144#-:-KA_miXWmFK17Y-1_T8M:-698977764)*

**Comment by jounik** [comment]
This still seems like it’s not the right fix, as it again causes #91 to not be okay. There are minor alignment issues in Safari, Chrome and Firefox (click the screenshot for full view).

combo-box-vs-paper-input

Messing with the internal styles of paper-input-container feels like we’re fixing it from the wrong place.

Also, this `padding-bottom: 0;` is causing vertical-alignment issues in IE11 at least, and to me feels totally wrong to override: https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box.html#L60

The padding affects the dropdown position, yes, but we should fix that somehow else, maybe by computing the position from some other element, or then computing the bottom padding and taking that into account.

**Comment by jounik** [comment]
It actually seems like an issue in paper-input also. Win 8.1, IE11:

screen shot 2016-02-19 at 11 11 06

**Comment by jounik** [comment]
So I would want us to remove this fix. I’ll create a separate issue about the bottom padding override.

**Comment by tomivirkki** [comment]
Link to the paper-input issue https://github.com/PolymerElements/paper-input/issues/171

**Comment by jounik** [comment]
Thanks Tomi, just searched for it myself as well and found the same thing :)

**Comment by Saulis** [comment]
I'll revert the commit :smiley_cat:

**Pull request merged**
