### PR TITLE
Fix hidden items in overlay

### PR DESCRIPTION
**Pull request by JosefJezek**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/418)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Hi @JosefJezek, thanks for the PR. For me however the hidden items are properly hidden without an additional style. Is there some specific case or browser where you’re having issues with the hidden items?

**Comment by JosefJezek** [comment]
Yes, when use custom filter using `filtered-items` property. :-/

**Comment by tomivirkki** [comment]
At least the "Custom Filtering" demo at https://vaadin.com/elements/-/element/vaadin-combo-box#demos uses the `filtered-items` property and properly hides non-visible items.

Can you provide a test case with your PR that validates the fix (a test that breaks before and passes after the change)?

**Comment by jouni** [comment]
Closing because there hasn’t been any activity in almost 2 months.

**Pull request closed without merging**
