### PR TITLE
Fix indent, imports and variables in demos

### LINKED ISSUE #336: Imports of iron-input and paper-button are missing in advanced demo

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #336

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/338)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV4vIBzi4IL7gHm6aUM:b-sz8e2b) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
> ```HTML
>   <link rel="import" href="../../iron-icon/iron-icon.html">
>   <link rel="import" href="../../iron-input/iron-input.html">
> </head>
> ```

Why are these needed in the example, they are imported via the common.html
The example is working, or I'm missing something ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by samiheikki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV4yR_CaAstyCf_X0Gm:b-bjthi9) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Why are these needed in the example, they are imported via the common.html
> The example is working, or I'm missing something ? 
</details>
They are added because some of the examples uses those elements and are not imported in common.html.  And they work, because vaadin-combo-box imports them. But I think those should be still be imported in that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV4zL4BkqS6vIRIandK:beow3xa) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> They are added because some of the examples uses those elements and are not imported in common.html.  And they work, because vaadin-combo-box imports them. But I think those should be still be imported in that.
</details>
I wanted to leave examples with the minimum stuff so as the reader focus in the example. If imports are not needed I don't see any need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by samiheikki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV5-zt3Gpm7loL9fTnG:btle3t9) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I wanted to leave examples with the minimum stuff so as the reader focus in the example. If imports are not needed I don't see any need.
</details>
Well I see it differently :) This is advanced demo and demonstrates how you can couple combo-box with other custom elements, and those always need an import. But I see your point also. We need a tie-breaker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by platosha** [comment]
Regardless of the importing structure we decide, currently for this PR the imports are inconsistent:

1. `iron-form` is imported in `common.html`, only used in `index.html`
2. `paper-input` is imported in `common.html`, only used in `advanced.html`
3. `paper-button`, `paper-icon-button`, and `iron-input` are imported and used only in `advanced.html`,
4. `iron-icons` are not explicitly imported in demos, although they are required for at least one of the demos from `advanced.html`.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV57bHj5368yu7WX8KW:bdsspnq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Well I see it differently :) This is advanced demo and demonstrates how you can couple combo-box with other custom elements, and those always need an import. But I see your point also. We need a tie-breaker.
</details>
As for me, the additional imports are not distracting me in any way from reading the source code. Normally my eyes skip the `<head>` section completely, starting directly from `<body>`.

Except for the case when I actually want to see what is required here. In this case, moving the page-specific imports to the `"common.html"` actually makes discovering them harder. That’s not a good idea, IMO.

I think, we should apply and promote general rules of good import structure here: import common stuff in the common file, import page-specific stuff in the page, so that these demos work as examples of how to structure the imports properly as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-:-KV5ArVaz_KgWGfNHKzY:bwsmz2d)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV5DiACKeNgIh4YAKV1:bb6mt9b) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> As for me, the additional imports are not distracting me in any way from reading the source code. Normally my eyes skip the `<head>` section completely, starting directly from `<body>`.
> 
> Except for the case when I actually want to see what is required here. In this case, moving the page-specific imports to the `"common.html"` actually makes discovering them harder. That’s not a good idea, IMO.
> 
> I think, we should apply and promote general rules of good import structure here: import common stuff in the common file, import page-specific stuff in the page, so that these demos work as examples of how to structure the imports properly as well.
</details>
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV5E7snoF4zGEqwwXvw:b777vgu) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> :+1:
</details>
Agree. I'll separate common.html so that page specific elements are loaded in their own files and the actual common stuff in common.html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by samiheikki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KV4vIBzi4IL7gHm6aUL:-KV95z5ocOrLJlug00qK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/70c566a7f0a1eff75e7d98496171d50f73138de6/demo/advanced.html#L18)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Agree. I'll separate common.html so that page specific elements are loaded in their own files and the actual common stuff in common.html.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/advanced.html, line 17 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KVAfPT7vGzunfZsDLe6:-KVAfPT8BHVPxkvU4puS:b3jzmxw) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/496b751b20465f1b06d47c56b4273d279c880237/demo/advanced.html#L17)):*
> ```HTML
>   <link rel="import" href="../../paper-button/paper-button.html">
>   <link rel="import" href="../../paper-icon-button/paper-icon-button.html">
>   <link rel="import" href="../../iron-icon/iron-icon.html">
> ```

The demo that uses `iron-icon` actually uses an icon from the `iron-icons` set. It is imported by some demo dependencies. Should we do it explicitly? Maybe add an import of `iron-icons` here?

---

*[demo/advanced.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KVAgGxB3moWSrgLf0RU:-KVAgGxCzglV1GezVs1-:bwvr8zc) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/496b751b20465f1b06d47c56b4273d279c880237/demo/advanced.html#L19)):*
> ```HTML
>   <link rel="import" href="../../iron-icon/iron-icon.html">
>   <link rel="import" href="../../iron-input/iron-input.html">
>   <link rel="import" href="../vaadin-combo-box-light.html">
> ```

BTW The light combo-box is a local import. I would personally like to place it after the non-local dependencies, such as iron- and paper- elements. Not a blocker, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by samiheikki** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/advanced.html, line 17 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KVAfPT7vGzunfZsDLe6:-KVOPRNxYLRA97e54N_g:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/496b751b20465f1b06d47c56b4273d279c880237/demo/advanced.html#L17)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> The demo that uses `iron-icon` actually uses an icon from the `iron-icons` set. It is imported by some demo dependencies. Should we do it explicitly? Maybe add an import of `iron-icons` here?
</details>
Done.

---

*[demo/advanced.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-KVAgGxB3moWSrgLf0RU:-KVOP_I9ZrZRQEA6N7j_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/496b751b20465f1b06d47c56b4273d279c880237/demo/advanced.html#L19)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> BTW The light combo-box is a local import. I would personally like to place it after the non-local dependencies, such as iron- and paper- elements. Not a blocker, though.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-:-KVOX5BxzeQcMayoWIG6:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-:-KVPB3YrGe2t_7CvmAHt:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/338#-:-KVPOkzEhcZrjK52RT8X:bnfp4nl)*

**Pull request merged**
