### PR TITLE
Hide dropdown when there are no matching items

### LINKED ISSUE #140: Hide dropdown when there are no matching items
The empty dropdown for custom input values (which do not match any item in the dropdown) causes some confusion for end users, and it should be hidden.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #140

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/146)

### CODE REVIEW

**Comment by jounik** [comment]
@samiheikki why does the cla-assistant constantly nag about your PRs?

**Comment by Saulis** [comment]
Seems like @samiheikki Git isn't configured properly, it's missing your author email that would link the commits to your Github account. Let's fix that.

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box.html, line 363 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6BVSYh5Uc7bdwfT4:-KAZ6BVSYh5Uc7bdwfT5:-1010981037) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L363)):*
Is this needed for something? All the tests pass without it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 468 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6b0PWAUZGV5mo-JZ:-KAZ6b0PWAUZGV5mo-J_:1405700403) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L468)):*
Is the `notifyResize` needed? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146)*

**Comment by Saulis** [comment]
@jounik should we do something with the icons to indicate better that when a custom value is going to be inserted? Like changing the whole toggle icon to something else or turning it a bit:

image

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/filtering.html, line 192 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ8v02rWNl0DQE7mHE:-KAZ8v02rWNl0DQE7mHF:796032197) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/test/filtering.html#L192)):*
Excessive empty line.

---

*[vaadin-combo-box.html, line 363 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6BVSYh5Uc7bdwfT4:-KAZ9jSKW3syysnisg-E:203963046) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L363)):*
Should we shorten this check to: `this.items == null` here and below?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146)*

**Comment by jounik** [comment]
> @jounik should we do something with the icons to indicate better that when a custom value is going to be inserted? Like changing the whole toggle icon to something else or turning it a bit:

@Saulis, that’s a separate discussion from this patch. But changing the icon might be an option, but I haven’t really thought about it. I would avoid rotating it, though, as to me it seems it would confuse users more than make it clear. @tuomasnironen, any thoughts if we we could add some indicator in the input when a custom value is being used?

**Comment by tuomasnironen** [comment]
@Saulis @jounik My first reaction was also not to use the same triangle icon that the dropdown has because of the possible confusion. Maybe rather just the plus shaped add icon "+"? https://design.google.com/icons/

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box.html, line 363 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6BVSYh5Uc7bdwfT4:-KAcm89SUL2wSjhRDj5e:1620230768) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L363)):*
Both are needed. If `combobox.items` is not defined it is `undefined`. If `combobox.items` is empty array it is `null`.

---

*[vaadin-combo-box.html, line 468 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6b0PWAUZGV5mo-JZ:-KAcj_eqItvBU3qxKPGr:2009397905) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L468)):*
Yes. If filtering hides dropdown and removing characters shows it again -> dropdown is in wrong place. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146)*

**Comment by Saulis** [comment]
:lgtm: :shipit: 

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-:-KAcs4-7EGobRoAqdBp9:2115672440)*

**Comment by platosha** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box.html, line 363 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146#-KAZ6BVSYh5Uc7bdwfT4:-KAczQqWyRUUd5bR5t-G:-1660383295) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7be95474193d1802c2dfb2e86342c03010fc56e9/vaadin-combo-box.html#L363)):*
FYI: loose equality check for `foo == null` will be true in both cases, either with `undefined` and `null` itself.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/146)*

**Pull request merged**
