### PR TITLE
Revert to custom value on esc

### LINKED ISSUE #291: Custom value is removed when pressing ESC after navigating the dropdow with arrow keys
### Recording:

After navigating the dropdown list with arrow keys, I press ESC twice. The first press should cancel the keyboard navigation, and reset the input value to the previous value, "custom" in this case. The internal field value is also cleared at the same time, as seen from the label under the field.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #291

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/371)

### CODE REVIEW

**Comment by manolo** [comment]
Rebase with master and  :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/371#-:-Kagalnl944SV9thE6JW:bypx348)*

**Comment by manolo** [comment]
wow, I pushed some button in reviewable and it  rebased 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/371#-:-Kagb0ddL70vnMG--yXZ:b-vn1gtx)*

**Comment by limonte** [comment]
It's most probably a GitHub button, which is proxied by Reviewable: https://github.com/blog/2051-protected-branches-and-required-status-checks (latest picture)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/371#-:-KaggVGyPaSfpxrS55BP:b-f0zp9n)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/371#-:-KaghfmkmnTQF0-ttRIu:bnfp4nl)*

**Comment by manolo** [comment]
Yep should be a github feature, but reviewable has a shortcut for it in the checks ring context menu

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/371#-:-KagheqnED0ZSLq7fRVA:b-mm97uu)*

**Pull request merged**
