### PR TITLE
Overlay no longer uses sup-pixels for positioning

### LINKED ISSUE #205: Blurry text in dropdown on OS X Chrome
The dropdown element translate is done using sub-pixels, which causes the text to be blurry inside the dropdown.

Comparison (GIF) – original vs. translate offset rounded to full pixels:
combo-box-blurry mov

Culprit:
screen shot 2016-03-31 at 13 05 26

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #205 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/217)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay-behavior.html, line 121 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFEQTRg2Dbjy_qevVfI:-KFEQTRhTVR5Jnd7zu5h:-335747250) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28bff95c02c2ac21fd58d0fbde5872e57d354860/vaadin-overlay-behavior.html#L121)):*
Why not Math.round?

Why round to exact pixels, not to device pixels? E.g., devicePixelRatio == 2, isn't it better to round half-pixels?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 121 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFEQTRg2Dbjy_qevVfI:-KFEXcqqS9ZY91md_aLx:-1974497353) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28bff95c02c2ac21fd58d0fbde5872e57d354860/vaadin-overlay-behavior.html#L121)):*
Don't you think using devicePixelRatio would be overoptimizing? If the position is initially a sub-pixel then we can never make the gap between the component and overlay perfect unless we shift the component also.

The overlay translate is pretty much always negative so using ~~ can never shift it vertically upwards (when it might cover some of the field focus indicator). Math.round would for example translate -1000.6 into -1001 making the overlay shift upwards. This was just theoretical though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 121 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFEQTRg2Dbjy_qevVfI:-KFEnXlv54VLamHP33up:-130833892) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28bff95c02c2ac21fd58d0fbde5872e57d354860/vaadin-overlay-behavior.html#L121)):*
Fixed to take devicePixelRatio into account in position computation as you suggested :thumbsup: 

Now overlay.getBoundingClientRect().top actually always returns a valid number dividable by the pixel ratio of device.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/overlay-position.html, line 146 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFISN4IJTD3NT7AOQ2r:-KFISN4IJTD3NT7AOQ2s:899347640) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50c287fde575b3b6ab2dc96009948f24818bdb41/test/overlay-position.html#L146)):*
Failing for Android in Travis: “expected 0.0000019073486328125 to equal 0”

---

*[test/overlay-position.html, line 147 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFISNwH051S9sFZo0zP:-KFISNwIVH-sU53tfM8Z:-1965907033) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50c287fde575b3b6ab2dc96009948f24818bdb41/test/overlay-position.html#L147)):*
Both lines check the same ```.top``` coordinate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/overlay-position.html, line 146 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFISN4IJTD3NT7AOQ2r:-KFIUHWXulriKutb67fL:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50c287fde575b3b6ab2dc96009948f24818bdb41/test/overlay-position.html#L146)):*
Done.

---

*[test/overlay-position.html, line 147 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFISNwH051S9sFZo0zP:-KFIUHo-OBeGfYCfD6Gl:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/50c287fde575b3b6ab2dc96009948f24818bdb41/test/overlay-position.html#L147)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 121 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFEQTRg2Dbjy_qevVfI:-KFIdWCYR3aAdHJzw-es:710655904) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/28bff95c02c2ac21fd58d0fbde5872e57d354860/vaadin-overlay-behavior.html#L121)):*
Ok one more fix. So now the overlay translate is done in sub-pixel precision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r5, 4 of 4 files at r7, 1 of 1 files at r8.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-overlay-behavior.html, line 105 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFJA4q74QginRe1IsP3:-KFJA4q8SI5fPkDv6Uzp:878021685) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/45ace1608cc38eb1521de7766140972ff3577861/vaadin-overlay-behavior.html#L105)):*
I think it's more logical to check if the scroll target contains the overlay, rather than the other way around. This would exclude other scrollable elements inside body.

---

*[test/overlay-position.html, line 74 \[r8\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFJDVRej6lZVe2lcMWX:-KFJDVRej6lZVe2lcMWY:932584637) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/68d0d39f6d56b366b84ddd21c2e2df154eef0b82/test/overlay-position.html#L74)):*
The comma shouldn't be here, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/overlay-position.html, line 74 \[r8\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFJDVRej6lZVe2lcMWX:-KFJE8-jtvYtffMMsXQE:-416109336) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/68d0d39f6d56b366b84ddd21c2e2df154eef0b82/test/overlay-position.html#L74)):*
Oh, this is fixed already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 105 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFJA4q74QginRe1IsP3:-KFJGQqZe4UN4d0chXtg:-2079235759) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/45ace1608cc38eb1521de7766140972ff3577861/vaadin-overlay-behavior.html#L105)):*
That wouldn't work. The positioning would be broken if combo box was placed in any scrollable container.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 105 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-KFJA4q74QginRe1IsP3:-KFJGlbuIMQ4OdBQdn8B:-1495535988) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/45ace1608cc38eb1521de7766140972ff3577861/vaadin-overlay-behavior.html#L105)):*
....because "This would exclude other scrollable elements inside body"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217#-:-KFJZCW0suZhbi2nP8_1:1417088721)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/217)*

**Pull request merged**
