### PR TITLE
Fix tests: include webcomponents.js instead of webcomponents-lite.js

### PR DESCRIPTION
**Pull request by limonte**
Also 

- remove Angular2 tests for speed up build
- add `wct-random-output` to prevent TravisCI 10m timeout
- for Edge still use `webcomponents-lite.js` because of https://github.com/webcomponents/webcomponentsjs/issues/575

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/389)

### CODE REVIEW

**Comment by manolo** [comment]
Do we want to maintain the build running  if  they last more than 10 minutes. I think it's better to fail it, even though it is a problem in travis or sauce side.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/389#-:-Kc-LUVarAMmqp0m2KfH:bwzk5c6)*

**Comment by limonte** [comment]
Nice question! Let's take the example: 2 pushes to grid and date-picker were made at the same time. Each Travis job requires 5 SauceLabs sessions. If grid took all those sessions date-picker job will open SauceLabs tunnel, but because there's no available sessions (limit 5) it will be queued for as long as grid build runs. That means no output and Travis will stop that build which is not what we want.

Adding `wct-random-output` will solve that case. 

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/389#-:-Kc-ObdVeT48jBMIBlYZ:b4jlzsw)*

**Comment by manolo** [comment]
Sounds reasonable. My only concern is that we let stuck build running for ever. Let's see if this happens.

:lgtm: 

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/389#-:-Kc2Q3JjRJsCz5leYlE4:b-yz2lax)*

**Comment by manolo** [comment]
You need to rebase this.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/389#-:-Kc2Qrdxsz0cnu9rThKa:btegf91)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/389)*

**Pull request merged**
