### PR TITLE
Use StackOverflow API for the 'Remote Data Source' example

### LINKED ISSUE #542: Fix Remote Data Source demo
https://cdn.vaadin.com/vaadin-combo-box/3.0.0-alpha6/demo/#combo-box-filtering-demos

Only works on Chrome.
http -> https?

### PR DESCRIPTION
**Pull request by limonte**
Fixes #542

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/545)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
I think it is a good idea to use actual external resource like StackOverflow for such demo :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-:-Kv1wVfZdOyNYG3r8MCv:b-cyaztn)*

**Comment by tomivirkki** [comment]
*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wwgqFUyRV2DOhxir:-Kv1wwgqFUyRV2DOhxis:b-zex1sm) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
> ```HTML
> 
> 
>     <h3>Remote Data Source, vaadin-combo-box questions from StackOverflow</h3>
> ```

Let's not change the title.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wBXfgZKNttTBpopx:-Kv1wBXfgZKNttTBpopy:b-gqlj70) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
> ```HTML
> 
> 
>     <h3>Remote Data Source, vaadin-combo-box questions from StackOverflow</h3>
> ```

You Broke Title Case in This Title.

Actually IMO the old title is still actual, no reasons to change. The particular API provider is irrelevant to demo purposes.

BTW I would prefer https://jsonplaceholder.typicode.com/ in this case. The real life APIs are nice, but not relevant...

---

*[demo/combo-box-filtering-demos.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1x0rHFxf2oAsD_rpm:-Kv1x0rHFxf2oAsD_rpn:b-vmamug) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L18)):*
> ```HTML
>             <iron-ajax url="https://api.stackexchange.com/2.2/search/advanced?order=desc&sort=activity&body=vaadin-combo-box&tagged=vaadin&title=[[filter]]&site=stackoverflow" last-response="{{response}}" auto></iron-ajax>
> 
>             <vaadin-combo-box filtered-items="[[response.items]]" filter="{{filter}}" item-value-path="title" item-label-path="title">
> ```

BTW Maybe we should use some technical data as `value`, like `"id"` or `"url"` something. Would be closer to real life IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545)*

**Comment by limonte** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wBXfgZKNttTBpopx:-Kv1yZWEG4SoCs5tjldq:bh8h86j) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
Revereted.

> BTW I would prefer https://jsonplaceholder.typicode.com/ in this case. 

Can't depend on unknown random resources, sorry. It will die any day, StackOverflow is 100% stable.

---

*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wwgqFUyRV2DOhxir:-Kv1yaQHftr7zjV-gAZ9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Let's not change the title.
</blockquote></details>

Done.

---

*[demo/combo-box-filtering-demos.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1x0rHFxf2oAsD_rpm:-Kv1yq4KE3h1yD79l-FM:bh179ko) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Maybe we should use some technical data as `value`, like `"id"` or `"url"` something. Would be closer to real life IMO.
</blockquote></details>

`title` works just fine and it's closer to the real-life cases IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-:-Kv1zC27EcXREl90bK5X:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wBXfgZKNttTBpopx:-Kv27xMrFaDrt3hF4DbB:btljtwt) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Revereted.

> BTW I would prefer https://jsonplaceholder.typicode.com/ in this case. 

Can't depend on unknown random resources, sorry. It will die any day, StackOverflow is 100% stable.
</blockquote></details>

OK Exactly same concern. This StackOverflow API endpoint has a fixed version in the URL though, and these things have limited lifespan usually.

Meanwhile, jsonplaceholder is high on google search for queries like “json example api” and 100% open-source:
APP: https://github.com/typicode/jsonplaceholder
DB: https://github.com/typicode/json-server

Not a blocker though.

---

*[demo/combo-box-filtering-demos.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1x0rHFxf2oAsD_rpm:-Kv26m3pna6xMwGSA5JL:b84f3t4) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L18)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`title` works just fine and it's closer to the real-life cases IMO
</blockquote></details>

OK So once user picked an item in the combo-box, would you store the users’s choice in some db using `title` or `id`? I assume `title` is not a reliable thing for storage, as users can probably rename their questions later. The real life practice here is to use stable technical `id` as stored values while `title` as visible ones. Not blocking though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545)*

**Comment by limonte** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/combo-box-filtering-demos.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1wBXfgZKNttTBpopx:-Kv2K-Jk0H3-ajSGM_Ad:b-yoqgj6) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L11)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK Exactly same concern. This StackOverflow API endpoint has a fixed version in the URL though, and these things have limited lifespan usually.

Meanwhile, jsonplaceholder is high on google search for queries like “json example api” and 100% open-source:
APP: https://github.com/typicode/jsonplaceholder
DB: https://github.com/typicode/json-server

Not a blocker though.
</blockquote></details>

StackOverflow API is the reliable thing, they are still supporting 1.x without any plans to deprecate it.

Open-source, on the other hand, is extremely unreliable and breaking changes could occur at any moment since  jsonplaceholder developers aren't smart enough to introduce the very basic and fundamental API functionality which is *versioning*.

---

*[demo/combo-box-filtering-demos.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-Kv1x0rHFxf2oAsD_rpm:-Kv2KX5xz3LT1TFH5S8V:bqoofm7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/0c736bb72fb70edd84bd4c8a62457e3d2a39b0fd/demo/combo-box-filtering-demos.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK So once user picked an item in the combo-box, would you store the users’s choice in some db using `title` or `id`? I assume `title` is not a reliable thing for storage, as users can probably rename their questions later. The real life practice here is to use stable technical `id` as stored values while `title` as visible ones. Not blocking though.
</blockquote></details>

Oh, sorry, I misunderstood you in previous comment, peplaced with `questions_id`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/545#-:-Kv2LV7yQ5GNe5WlyLtJ:bnfp4nl)*

**Pull request merged**
