### PR TITLE
Add items property

### PR DESCRIPTION
**Pull request by cwayfinder**
Connects to #12

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/17)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[vaadin-combo-box.html, line 26 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K184FYs7ohFnRTjk6mG)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L26)):</sup>
I think the list could benefit from a white background color - in some of the demo examples the `submit` button can be seen through the list.


---

<sup>**[vaadin-combo-box.html, line 30 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K184S1r6JtoSS6OgZXz)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L30)):</sup>
Could you add a :hover style with a blue background colour, I think we have something like that in the proto? At least vaadin-grid has that.


---

<sup>**[vaadin-combo-box.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K183urKHnChE_QzczIv)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L51)):</sup>
Do you know if there is some way to define the `class` without using a function? Something like `selected? 'selected' : ''`

Would be cleaner IMO. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by cwayfinder** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 26 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K184FYs7ohFnRTjk6mG)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L26)):</sup>
Done.


---

<sup>**[vaadin-combo-box.html, line 30 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K184S1r6JtoSS6OgZXz)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L30)):</sup>
Done.


---

<sup>**[vaadin-combo-box.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K183urKHnChE_QzczIv)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L51)):</sup>
No, I didn't find any way. We cannot use such expressions in markup.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 19 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18jpqNbHTbtgkAL4KV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/vaadin-combo-box.html#L19)):</sup>
No need to use flex here


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by Saulis** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K183urKHnChE_QzczIv)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L51)):</sup>
Actually what you could do is `<div selected$=[[selected]] class$="item">` and then use `.item[selected]` selector in the CSS. Would be cleaner, right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by tomivirkki** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[test/mutating-items.html, line 34 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18ln4uellCN87ye7A-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/test/mutating-items.html#L34)):</sup>
All these tests are currently testing if combobox.push etc api's work. That's not really our job. The tests should target the new functionality added by us.


---

<sup>**[vaadin-combo-box.html, line 23 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18nlWgT5oLP9-bIPbP)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8dff7c38fb879645c44d5ddd61c5e0324bc8de1a/vaadin-combo-box.html#L23)):</sup>
Still using flex here


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K183urKHnChE_QzczIv)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/79b00821e7fccec1ff2b396674b52bf42a4880ed/vaadin-combo-box.html#L51)):</sup>
Agree attributes could be easier to read, but also we should consider what happens if the attribute is changed by the user, should we select that item by code as well ?


---

<sup>**[vaadin-combo-box.html, line 98 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18md1GOjfT8N2LCitE)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/vaadin-combo-box.html#L98)):</sup>
why not take advantage of question mark operator so as JS is simpler and readable enough?

        return 'item' + isSelected ? ' selected' : '';


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by tomivirkki** [comment]
<sup>**[vaadin-combo-box.html, line 98 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18md1GOjfT8N2LCitE)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/vaadin-combo-box.html#L98)):</sup>
Seems to be copied from here: https://github.com/PolymerElements/iron-list/blob/master/demo/selection.html#L240
But anyway, this method can be removed once switched to using the attribute as Sauli suggested


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by cwayfinder** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 19 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18jpqNbHTbtgkAL4KV)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/vaadin-combo-box.html#L19)):</sup>
Done.


---

<sup>**[vaadin-combo-box.html, line 23 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18nlWgT5oLP9-bIPbP)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8dff7c38fb879645c44d5ddd61c5e0324bc8de1a/vaadin-combo-box.html#L23)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by cwayfinder** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[vaadin-combo-box.html, line 98 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18md1GOjfT8N2LCitE)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/vaadin-combo-box.html#L98)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by cwayfinder** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[test/mutating-items.html, line 34 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18ln4uellCN87ye7A-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/test/mutating-items.html#L34)):</sup>
They only test whether our bindings are correct. Shall we remove these tests?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by tomivirkki** [comment]
<sup>**[test/mutating-items.html, line 34 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18ln4uellCN87ye7A-)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/65d76e8bea9612defe1ba52e905aaa53a81979e5/test/mutating-items.html#L34)):</sup>
The last test seems to test the binding between combo-box and iron-list so that's ok. The first two however pass even if all the bindings are removed so maybe remove them.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[test/mutating-items.html, line 24 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18vuF1v1hr25Zh4RIM)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1f18867a6a93dd00e529b6fbfa38f4eb1307cd61/test/mutating-items.html#L24)):</sup>
Maybe call this test suite `setting items` ? and the file `setting-items.html` respectively?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[test/mutating-items.html, line 24 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K18vuF1v1hr25Zh4RIM)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1f18867a6a93dd00e529b6fbfa38f4eb1307cd61/test/mutating-items.html#L24)):</sup>
Or it could also be considered to move the test to the `properties` test suite?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Comment by tomivirkki** [comment]
<sup>**[test/mutating-items.html, line 37 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17#-K19-Us6_snnHNKC_9Wn)** ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1f18867a6a93dd00e529b6fbfa38f4eb1307cd61/test/mutating-items.html#L37)):</sup>
The test passes even if I change this to combobox.items.push('foo'); = they share the same array instance. But this doesn't guarantee that iron-list gets updated with the new value 'foo'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/17)

**Pull request merged**
