### PR TITLE
Fix infinite loop. Fixes #173

### LINKED ISSUE #173: Infinite loop when a shared bound value is set to null
This code fails when 'name' is undefined, see attached screenshot

```
 <vaadin-combo-box items="[[robots]]" value="{{name}}" label="Select a Robot"></vaadin-combo-box>

```
screen shot 2016-02-27 at 22 51 17

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/174)

### CODE REVIEW

**Comment by manolo** [comment]
Seems that it happens in non common cases, when data binding is composed by multiple actors, this is my failing example:
https://gist.github.com/manolo/aa8afdbfc0a63d5a6982

**Comment by Saulis** [comment]
Thanks, I can see the problem now. Unfortunately this PR doesn't seem to fix the issue, will investigate more.

**Comment by Saulis** [comment]
I'll close this PR as it looks like a fix needs to be filed to paper-input

**Comment by manolo** [comment]
I need this fix for my demo, otherwise it causes a loop in chrome and safari goes absolutly frozen and even the computer.
In my demo I had to return undefined which is Ok but breaks tests.
I don't thing we need to set value to '' but probably it could be discussed

**Comment by manolo** [comment]
Closing since this fix is not ideal.

**Pull request closed without merging**
