### PR TITLE
Fix loop when data-bound element sets values to null

### LINKED ISSUE #173: Infinite loop when a shared bound value is set to null
This code fails when 'name' is undefined, see attached screenshot

```
 <vaadin-combo-box items="[[robots]]" value="{{name}}" label="Select a Robot"></vaadin-combo-box>

```
screen shot 2016-02-27 at 22 51 17

### PR DESCRIPTION
**Pull request by manolo**
Fixes #173

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/212)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-combo-box.html, line 596 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8UucLLRKYMCCNiYC1:-KF8UucLLRKYMCCNiYC2:167967599) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/vaadin-combo-box.html#L596)):*
Redundant empty line.

---

*[test/data-binding.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8S7SmguXHkNPhCuuV:-KF8S7SnQffi1q3TsjAJ:-927196313) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L31)):*
Seems for me that you can remove the id attr and name binding here.

---

*[test/data-binding.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8V3cJm4JIqsK4PavV:-KF8V3cJm4JIqsK4PavW:-188204545) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L32)):*
Missing double quotes around ```{{name}}```.

---

*[test/data-binding.html, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8RmzESih2Ckh0ibbt:-KF8RmzESih2Ckh0ibbu:-1670556400) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L34)):*
Why is this input here?

---

*[test/data-binding.html, line 49 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8XX8gg3hyf3TJmhh4:-KF8XX8gg3hyf3TJmhh5:2055930756) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L49)):*
The checking code in the following tests are identical. Would it make sense to DRY this up by extracting the check into a function?

---

*[test/data-binding.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8X7Cqy_nrsgluIj5R:-KF8X7Cqy_nrsgluIj5S:-147942372) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L51)):*
I've quickly tried the same but by listening to “value-changed” instead of monkey-patching, and it worked for me. Why not?

---

*[test/data-binding.html, line 57 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8QxI32gAq7cKOkQRq:-KF8QxI4SJHu1jgtv7wW:634086844) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L57)):*
```comboBox.__valueChanged(value);``` is enough.

---

*[test/data-binding.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8R7xx1QD7DtHP0atG:-KF8R7xx1QD7DtHP0atH:634086844) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L75)):*
```comboBox.__valueChanged(value);``` is enough.

---

*[test/data-binding.html, line 42 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8YEkM_A01FYPd8i8Y:-KF8YEkM_A01FYPd8i8Z:-684195139) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/06be782fca7eb2f709f364b082e48599cfb89c3c/test/data-binding.html#L42)):*
Why test only in Chrome? What about a short comment for explanation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/data-binding.html, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8RmzESih2Ckh0ibbt:-KF95N9sWrQpBDi3rorz:1719450041) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L34)):*
This is actually which makes the loop happens, iron-localstorage sets the value=null and iron-input fires a bind-value-changed event which makes the loop start

---

*[test/data-binding.html, line 42 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8YEkM_A01FYPd8i8Y:-KF95m6EO0DGxNolsHMJ:-2114062679) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/06be782fca7eb2f709f364b082e48599cfb89c3c/test/data-binding.html#L42)):*
Loop only seems to happen with chrome. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/data-binding.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8X7Cqy_nrsgluIj5R:-KF99D5Belbw2Lp-jffL:-182197357) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L51)):*
I wanted to test the method not being enter in a loop, didn't want to test whether the event is fired.
But anyway in this case, event listener is enough to demonstrate that there is no loop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box.html, line 596 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8UucLLRKYMCCNiYC1:-KF9B8RbJ_0GLtVTU9i5:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/vaadin-combo-box.html#L596)):*
Done.

---

*[test/data-binding.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8S7SmguXHkNPhCuuV:-KF9BDR-BBBDCkdQ0OA4:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L31)):*
Done.

---

*[test/data-binding.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8V3cJm4JIqsK4PavV:-KF9BGUjDQRi8NkulRQV:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L32)):*
Done.

---

*[test/data-binding.html, line 49 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8XX8gg3hyf3TJmhh4:-KF9D9JEF_m8iHgWLCR-:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L49)):*
Done.

---

*[test/data-binding.html, line 57 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8QxI32gAq7cKOkQRq:-KF9Al-Mxf22gAtI-yOX:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L57)):*
Done.

---

*[test/data-binding.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8R7xx1QD7DtHP0atG:-KF9AljDo5nvFkdgUBm-:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L75)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/data-binding.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8S7SmguXHkNPhCuuV:-KF9IFWM04p3UB1Mfnid:-15987179) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L31)):*
The name is still bound here. Any reasons?

---

*[test/data-binding.html, line 47 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF9JM4eqXwvQLo4IOZE:-KF9JM4eqXwvQLo4IOZF:-15219532) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/fbcf8302f40872953b4c3fb526dc1f33139a3b05/test/data-binding.html#L47)):*
`to undefined or null` here, I suppose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/data-binding.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF8S7SmguXHkNPhCuuV:-KF9TyYhzf8VUoxXH6fI:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8f8fcabc72b31bc4de6aa86f2bed56398068c5b2/test/data-binding.html#L31)):*
Done.

---

*[test/data-binding.html, line 47 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-KF9JM4eqXwvQLo4IOZE:-KF9TzQBp6AYrFK65ovM:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/fbcf8302f40872953b4c3fb526dc1f33139a3b05/test/data-binding.html#L47)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/212#-:-KF9UKMx7MU1-FLa2UCI:1417088721)*

**Pull request merged**
