### PR TITLE
Fix appearance of item template demos

### LINKED ISSUE #593: Demo examples issues
### Description
I guess this look isn't intentional:

### Live Demo
https://cdn.vaadin.com/vaadin-combo-box/4.0.0-alpha3/demo/#combo-box-item-template-demos

### PR DESCRIPTION
**Pull request by platosha**
Fixes #593

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/604)

### CODE REVIEW

**Comment by web-padawan** [comment]
1. consider setting `width` to 240px on the "Focused and Selected Flags" demo as well so it looks aligned and the items content can fit in 2 rows.

2. missing closing `</paper-item-body>` tag in the "Item Template with Paper Item Elements" demo breaks Edge.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/604#-:-L3gUx0qd1diFA0BCTfX:b-y56346)*

**Comment by web-padawan** [comment]
Also, the "Item Template Demos" page is not rendered correctly in IE: the last demo does not show at all (event after adding closing tag mentioned above), and the combo-boxes from the other demos do not open.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/604#-:-L3g_DznhcgmErMRdNzA:b-jtu79m)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/604)*

**Comment by platosha** [comment]
Done.

Done.

Running `$ bower up` fixed IE11 for me.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/604#-:-L3heQMADcICl7Ajbge0:b-xrhzof)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/604#-:-L3hgYw6162zI-khcshU:bnfp4nl)*

**Pull request merged**
