### PR TITLE
Fix combo-box z-index in paper-dialog

### LINKED ISSUE #147: overlay is not visible in modals.
The overlay is not displayed when the component is in a paper-dialog modal component.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #147

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/149)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149#-KA_L6-NC4jsy6fUgmN7:-KA_L6-NC4jsy6fUgmN8:-98139348) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5f143c5ad88b18975a0c866daa5c5a749e463d95/vaadin-combo-box-overlay.html#L14)):*
Why 200 ? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149)*

**Comment by samiheikki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149#-KA_L6-NC4jsy6fUgmN7:-KA_LVRrweHW8vYiMddY:450005042) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5f143c5ad88b18975a0c866daa5c5a749e463d95/vaadin-combo-box-overlay.html#L14)):*
Big discussion with Sauli. iron-overlay-manager.html: Polymer.IronOverlayManagerClass.prototype._applyOverlayZ sets paper-dialog's z-index minimum z-index (101) + 2 for paper-dialog. We thought that setting it 200 would be safe number.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-combo-box-overlay.html, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149#-KA_L6-NC4jsy6fUgmN7:-KAanTHm2yuTw2OEdZW6:1367314832) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/5f143c5ad88b18975a0c866daa5c5a749e463d95/vaadin-combo-box-overlay.html#L14)):*
I think this needs a comment in the code with this reason

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149)*

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/149)*

**Pull request merged**
