### PR TITLE
Fix mouse selection on vaadin-combo-box-light

### LINKED ISSUE #302: Mouse selection is broken on vaadin-combo-box-light
This is a regression from https://github.com/vaadin/vaadin-combo-box/commit/fcf940dda080cfaf1ed5411fbbd2ec0ddd46272f.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #302

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/303)

### CODE REVIEW

**Comment by manolo** [comment]
Is it worth to add a test to this?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/303#-:-KRTh02zYxWN4wBLms38:b-xnqhc3)*

**Comment by tehapo** [comment]
I guess it would be. :smile:

I'll add a test later today.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/303#-:-KRX1cfwpdN-12Lfnt52:b83yvij)*

**Comment by tehapo** [comment]
Added tests and rebased the branch on top of latest master.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/303#-:-KRco_Ey7abFVM5lJg3B:b-nrv5am)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/303#-:-KRgu0GGabYfZhCdZlfU:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/303#-:-KRhciuEh9er5HQfIJQe:bnfp4nl)*

**Pull request merged**
