### PR TITLE
Fix selection in touch devices when in vaadin-dialog

### LINKED ISSUE #634: Cannot update a combobox in a dialog on tablet/phone
@jcgueriaud commented on [Tue Mar 27 2018](https://github.com/vaadin/flow/issues/3774)

Hello,

When I click on a combobox inside a dialog with my android tablet or my android phone (I use Google Chrome), I can't select a element.

The same combobox outside the dialog is working. I don't have any problem on computer.

See my example below.
Steps to reproduce:
- Click on OPEN button.
- Click inside the combobox (not on the arrow)
---> The keyboard is opened
- select an element
--> This element is not selected and the keyboard is closed

    /*** The main view contains a button and a template element.
     */
    @BodySize(height = "100vh", width = "100vw")
    @HtmlImport("styles/shared-styles.html")
    @Route("")
    @Theme(Lumo.class)
    public class MainView extends VerticalLayout {
    
    
        private ComboBox<String> comboBox;
    
        private Dialog editPopup;
        private Button openButton;
    
        public MainView() {
    
            comboBox = new ComboBox<>("Test");
            String[] data = {"Label 1","Label 2","Label 3","Label 4"};
            comboBox.setItems(data);
            editPopup = new Dialog();
            editPopup.add(comboBox);
            openButton = new Button("Open");
            openButton.addClickListener(event -> editPopup.open());
    
            add(openButton);
    
            setClassName("main-layout");
        }
    
    }

---

@pleku commented on [Wed Mar 28 2018](https://github.com/vaadin/flow/issues/3774#issuecomment-376768560)

Hello and thanks for the report. From looking at the code, I think the issue is with the web component and how it works inside a `vaadin-dialog`, thus I'm moving it to the web component repository.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #634

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/637)

### CODE REVIEW

**Comment by manolo** [comment]
Still a WIP. Discovered that the issue is reproducible when the combo-box is moved when opening the soft keyboard, for instance by focusing an element placed under the keyboard in the demo.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-:-L9JUQaq3j5lq6NPfSbu:b-bxms4x)*

**Comment by manolo** [comment]
Ready for review.
There is still an issue (overlay position update when scrolling) unrelated with this PR that will be covered in separated PR. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-:-L9KM8E52CqxEzCx179m:b-ilapr9)*

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-combo-box-dropdown.html, line 23 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-L9KaaXY0JEmhoEQnMq9:-L9KaaXY0JEmhoEQnMqA:b5qm0be) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ba0806e5cae98223e890329258ddfa3bedcbfe3f/src/vaadin-combo-box-dropdown.html#L23)):*
> ```HTML
>     </style>
>     <vaadin-combo-box-overlay id="overlay" hidden$="[[hidden]]" opened="[[opened]]" template="{{template}}"
>         style="align-items: stretch; margin: 0; pointer-events: auto;">
> ```

`auto` is a default value, normally should not be needed.

Are you sure we cannot fix it where `none` is set?

---

*[test/vaadin-combo-box.html, line 266 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-L9Kbr22CMFEWZybv1PZ:-L9Kbr22CMFEWZybv1P_:b-gqb6r) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ba0806e5cae98223e890329258ddfa3bedcbfe3f/test/vaadin-combo-box.html#L266)):*
> ```HTML
>           });
>         });
> ```

Note: there is existing (but incorrect and therefore meaningless) test for touchstart blur in the `test/scrolling.html`:

```javascript
      describeIf(touchDevice, 'touch devices', () => {
        it('should blur input on scroll', () => {
          combobox.open();

          fire('down', combobox.$.overlay);
          const focusedInput = combobox.root.querySelector('input:focus');

          expect(focusedInput).not.to.equal(combobox.inputElement);
        });
      });
```

That test does not work, I suppose, because there is no `down` gesture event anymore, and also there is no input element in combobox shadowRoot anymore.

Please do something about that test, either fix or remove.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637)*

**Comment by manolo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-combo-box-dropdown.html, line 23 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-L9KaaXY0JEmhoEQnMq9:-L9Km2JK4LOXPfUd3fj1:b-phrr09) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ba0806e5cae98223e890329258ddfa3bedcbfe3f/src/vaadin-combo-box-dropdown.html#L23)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I think the regression has been introduced in vaadin/vaadin-lumo-styles@31f23fe

The `overflow: auto` apparently needs to be moved to "menu-overlay-core" style module (which is included by combo-box) to get it working now.
</blockquote></details>

Actually the real overlay had the correct property, so this fix is not needed. Modified the test to verify that it's correct. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-combo-box-dropdown.html, line 23 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-L9KaaXY0JEmhoEQnMq9:-L9Kw1-_0XPC0-_2dut2:b-vzufdb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ba0806e5cae98223e890329258ddfa3bedcbfe3f/src/vaadin-combo-box-dropdown.html#L23)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Actually the real overlay had the correct property, so this fix is not needed. Modified the test to verify that it's correct. 
</blockquote></details>

LGTM :thumbsup: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/637#-:-L9KwEA70TBi_VzwozZ0:bnfp4nl)*

**Pull request merged**
