### PR TITLE
Use 2.0 preview hybrid dependencies in 1.x

### PR DESCRIPTION
**Pull request by manolo**
Connected to #413

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/442)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/form-input.html, line 79 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMva_Kt6wPMuyR2eyN:-KjMva_Kt6wPMuyR2eyO:b-5wmp1y) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L79)):*
> ```HTML
> 
>       it('should validate correctly when input value is invalid', function(done) {
>         window.parent.e = comboBox;
> ```

Is this some debug code?

---

*[test/form-input.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMvddV2axkvBgS3Jr4:-KjMvddV2axkvBgS3Jr5:b-gjhn2e) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L83)):*
> ```HTML
>         comboBox.required = true;
> 
>         // Timeout needed in 1.x with hybrid iron-input
> ```

Works for me without the timeout. Is this for some specific browser?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442)*

**Comment by manolo** [comment]
Reviewed 7 of 7 files at r1.
Review status: 3 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/form-input.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMvddV2axkvBgS3Jr4:-KjMwBoAgo4SWQD-liNJ:brwx8mq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L83)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Works for me without the timeout. Is this for some specific browser?
</blockquote></details>

IIRC think IE11 and Edge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442)*

**Comment by manolo** [comment]
Review status: 3 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/form-input.html, line 79 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMva_Kt6wPMuyR2eyN:-KjMwI5IEe9m_ttVTbhC:b2nign3) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L79)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this some debug code?
</blockquote></details>

yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442)*

**Comment by tomivirkki** [comment]
*[test/form-input.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMvddV2axkvBgS3Jr4:-KjMx97sEFa4KBCSAgrN:btgvgpv) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L83)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

IIRC think IE11 and Edge
</blockquote></details>

Nope, works fine on both without the timeout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442)*

**Comment by manolo** [comment]
Review status: 3 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 79 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMva_Kt6wPMuyR2eyN:-KjMyUN3ZQhcEVam41J1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L79)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

yep
</blockquote></details>

Done.

---

*[test/form-input.html, line 83 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-KjMvddV2axkvBgS3Jr4:-KjMyTMZkSAieXQebV3w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/75f8da4ae3020a817aa08421c021e6a5a0caa3bf/test/form-input.html#L83)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Nope, works fine on both without the timeout
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/442#-:-KjN-7bMzCBc746wQ1fy:bnfp4nl)*

**Pull request merged**
