### PR TITLE
Feature/ios scrollposition

### LINKED ISSUE #9: Enforce iOS viewport scroll position for fullscreen mode
Clean up the prototype code in the fullscreen-ios branch.

Remove code related to viewport resizing (when the keyboard is open)

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #9

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/53)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[test/adaptive-overlay.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nZ9kVWgLCw8hfGkX2:-K3nZ9kVWgLCw8hfGkX3:1208916818) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/adaptive-overlay.html#L55)):_
These lines (54 and 55) do not check the dropdown dimensions against the viewport dimensions. They are always true when the top left corner of the dropdown is aligned to the top left corner of the viewport.

Previously the dimensions check was there, looks like it's missing now.

---

_[test/adaptive-overlay.html, line 59 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nY8yK9js5RPzxTRRU:-K3nY8yK9js5RPzxTRRV:-1328949342) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/adaptive-overlay.html#L59)):_
Does this have to be a separate function? I can't see any other use inside the scope.

---

_[test/common.js, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3naFv54hF25PVeNugw:-K3naFv54hF25PVeNugx:327329480) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/common.js#L21)):_
In contrast to `describeSkipIf`, the `describeIf` wouldn't accept `function` conditions for the `bool` parameter. Passing a `function` would result as always `describe`. Might cause some confusion.

---

_[vaadin-adaptive-overlay.html, line 215 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nevino_0r28iF_FTE:-K3nevino_0r28iF_FTF:1539780826) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/vaadin-adaptive-overlay.html#L215)):_
Mentioning `this.fullScreen` here is unnecessary since `this._iOSOpened();` is called only in case when `this.fullScreen` is `true` (line 203).

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53)_

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53)_

**Comment by tomivirkki** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[test/adaptive-overlay.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nZ9kVWgLCw8hfGkX2:-K3nkKpPzFrA_07lfYte:-260594845) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/adaptive-overlay.html#L55)):_
Good catch, fixed

---

_[test/adaptive-overlay.html, line 59 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nY8yK9js5RPzxTRRU:-K3nj_AqfxyslSUsoaOF:-119616897) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/adaptive-overlay.html#L59)):_
Was planning on using the function in other dropdown size-related tests but didn't find a way to implement them. Fixed.

---

_[test/common.js, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3naFv54hF25PVeNugw:-K3njXQMihzK0uAYS31d:-260594845) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/test/common.js#L21)):_
Good catch, fixed

---

_[vaadin-adaptive-overlay.html, line 215 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-K3nevino_0r28iF_FTE:-K3nkjoj37tHIHqDpIln:250785083) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/3807c72324682ca7d850bdc020a05cc57ffbe328/vaadin-adaptive-overlay.html#L215)):_
The function needs to be called for non-fullscreen devices also (ipad should be handled here later) so this check is needed. Moved the invocation out of the "fullscreen" block in _opened.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53)_

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53)_

**Comment by tehapo** [comment]
LGTM.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/53#-:-K3o3MLe0ty4pMG3KSz0:-492975211)_

**Pull request merged**
