### PR TITLE
Make selectedItem writable and primary source of selection

### LINKED ISSUE #352: “Clear” button does not clear the visible input value when the internal value is empty
When the internal value of the combo box is empty, pressing the “clear” button does not empty the visible input value:

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #352 
Relates to #350

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/353)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 376 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuL7YDMml2QXONKnOF:-KXuL7YDMml2QXONKnOG:b-ynqyyg) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9938d7e7a432a859cfa8b0974135da9b8364c96a/vaadin-combo-box-behavior.html#L376)):*
> ```HTML
>             var customValue = this._inputElementValue;
>             this.selectedItem = null;
>             this.value = customValue;
> ```

Is the auxiliary variable `customValue` needed, or can it be inlined ?

---

*[docs/vaadin-combo-box-value.adoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuR0hwanWL5F6apiUJ:-KXuR0hxthJ3HdKy3upy:btspezq) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08138a97d9743cfc2e574d27739381b00b2c7b0f/docs/vaadin-combo-box-value.adoc#L13)):*
> ```AsciiDoc
> == Getting Started
> 
> You need to provide the set of items which the user can select with the [propertyname]#items# property.
> ```

I think we need the property word here still. 

---

*[docs/vaadin-combo-box-value.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuRJjMamTQ7pSkDO_z:-KXuRJjMamTQ7pSkDOa-:bhsyiky) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9938d7e7a432a859cfa8b0974135da9b8364c96a/docs/vaadin-combo-box-value.adoc#L15)):*
> ```AsciiDoc
> You need to provide the set of items which the user can select with the [propertyname]#items#.
> Current selection is indicated by the [propertyname]#value# and [propertyname]#selectedItem#.
> You can set or change the selection programmatically by setting the [propertyname]#value# or [propertyname]#selectedItem#.
> ```

here also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by Saulis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 376 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuL7YDMml2QXONKnOF:-KXybIoktUBbrgHz89rG:bfjn1qi) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9938d7e7a432a859cfa8b0974135da9b8364c96a/vaadin-combo-box-behavior.html#L376)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is the auxiliary variable `customValue` needed, or can it be inlined ?
</blockquote></details>

When `selectedItem` is set to `null`, I believe it clears out the `_inputElementValue`, so we need to store it before.

---

*[docs/vaadin-combo-box-value.adoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuR0hwanWL5F6apiUJ:-KXybac9-SCLeSyYFCgU:bu6jgm7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08138a97d9743cfc2e574d27739381b00b2c7b0f/docs/vaadin-combo-box-value.adoc#L13)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think we need the property word here still. 
</blockquote></details>

Remember Magi's teachings: you should add a caption "Picture of Sauli" under a picture of me, just "Sauli" – I think the same principle applies here: we don't want to repeat the word "property" every time we refer to a property since the reader can determine that from the context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by samiheikki** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 475 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXysC5qh1KiX2V-xM_w:-KXysC5qh1KiX2V-xM_x:b7qxe0o) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8dc12ed8078b21866ec9fbd3b06771da6037d85a/vaadin-combo-box-behavior.html#L475)):*
> ```HTML
>         this.selectedItem = item ? item : null;
> 
>         if (!item && this.allowCustomValue) {
> ```

Can you explain this? When there are no selectedItem then we update the input value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 475 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXysC5qh1KiX2V-xM_w:-KXz0azZkQlgsc1Y9w-p:bmztdin) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/8dc12ed8078b21866ec9fbd3b06771da6037d85a/vaadin-combo-box-behavior.html#L475)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you explain this? When there are no selectedItem then we update the input value?
</blockquote></details>

Basically when user sets `combobox.value` we want to update `combobox.selectedItem` to match that. In the case when an item matching the new `value` is found from the `filteredItems`, we assign it to `selectedItem` and the `_selectedItemChanged` will take care of assigning `inputElementValue` etc.

When an matching item is not found, assigning `null` to `selectedItem` will clear out the `_inputElementValue`, so in the case when custom values are allowed, we're going to override that behaviour by assigning the correct value manually here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-combo-box-value.adoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuR0hwanWL5F6apiUJ:-KXz2Yr51kzCZToYXjdZ:bfw0tj) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08138a97d9743cfc2e574d27739381b00b2c7b0f/docs/vaadin-combo-box-value.adoc#L13)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Remember Magi's teachings: you should add a caption "Picture of Sauli" under a picture of me, just "Sauli" – I think the same principle applies here: we don't want to repeat the word "property" every time we refer to a property since the reader can determine that from the context.
</blockquote></details>

I don't think it's a related thing. A picture has a visual meaning out of any comment, also when you style a `[vaadinelement]##` because it's enclosed between `<>` when it is displayed. 
But to me this case, at the very beginning of the article, when the user does not know anything about there is a existing `items` property  in the component, and also when in the same sentence the items word is used for two different concepts sounds very confusing.
I'm not an English speaker, so the problem might be when I translate it into Spanish in my mind. But, if I use the google translator, adding the property word, the output is meaningful vs something that makes not sense at all if the property word is not there.

https://goo.gl/Pmn8ZG
https://goo.gl/szjPJD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by Saulis** [comment]
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-combo-box-value.adoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuR0hwanWL5F6apiUJ:-KYE-IkHa48p8iSguRXf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/08138a97d9743cfc2e574d27739381b00b2c7b0f/docs/vaadin-combo-box-value.adoc#L13)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't think it's a related thing. A picture has a visual meaning out of any comment, also when you style a `[vaadinelement]##` because it's enclosed between `<>` when it is displayed. 
But to me this case, at the very beginning of the article, when the user does not know anything about there is a existing `items` property  in the component, and also when in the same sentence the items word is used for two different concepts sounds very confusing.
I'm not an English speaker, so the problem might be when I translate it into Spanish in my mind. But, if I use the google translator, adding the property word, the output is meaningful vs something that makes not sense at all if the property word is not there.

https://goo.gl/Pmn8ZG
https://goo.gl/szjPJD
</blockquote></details>

Done.

---

*[docs/vaadin-combo-box-value.adoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KXuRJjMamTQ7pSkDO_z:-KYE-K1W62T7b2x59jc4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/9938d7e7a432a859cfa8b0974135da9b8364c96a/docs/vaadin-combo-box-value.adoc#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

here also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-behavior.html, line 455 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KYSbzjw-glgWGRrw7w_:-KYSbzjxFOf5UmCy_4Hb:b-h6zxjw) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4965389cb88c3caae1f0bea35c149d871ca3bbd0/vaadin-combo-box-behavior.html#L455)):*
> ```HTML
>       }
> 
>       if (selectedItem === null) {
> ```

With custom values enabled you end here after setting the value to something that's not in items list = no clear button visible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by Saulis** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 455 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KYSbzjw-glgWGRrw7w_:-KYXg0PGNOFv8dmP88AP:b-udvkmz) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4965389cb88c3caae1f0bea35c149d871ca3bbd0/vaadin-combo-box-behavior.html#L455)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

With custom values enabled you end here after setting the value to something that's not in items list = no clear button visible
</blockquote></details>

You're right, and also `value` is cleared in this case. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by Saulis** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 455 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-KYSbzjw-glgWGRrw7w_:-KYnKvi4rxadgthvInBA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/4965389cb88c3caae1f0bea35c149d871ca3bbd0/vaadin-combo-box-behavior.html#L455)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

You're right, and also `value` is cleared in this case. Will fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 5 of 8 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-:-KYnMm1A372eMaveaJlE:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/353#-:-KYo3p9pf02zx0xgG8qa:bnfp4nl)*

**Pull request merged**
