### PR TITLE
Add item template support

### LINKED ISSUE #165: Custom item template support
Split from #96, where this was already researched.
### Research report

Exposing items template is one step beyond the scope of this task. Despite that, it was also prototyped to get the idea of its complexity level.

The prototype branch contains a draft but working implementation: https://github.com/vaadin/vaadin-combo-box/tree/proto/custom-item-template

Exposing an item template is a complex task as well (roughly at the sample level, I’d say). While possible per se, still it requires to introduce a separate `vaadin-combo-box-item` element and expose the `iron-list` in the light DOM of the overlay. Deep explanation of the problems below.
- To achieve that, the first idea was to set the entire `iron-list` item template with the template provided in the combo-box light DOM.
  - Turned out to be impractical: we still need to have an `.item` node defined inside the overlay, assigning model and state attributes (like `id` with index, `selected`, `focused`, ARIA `role` and `aria-selected`) and basic styles to it.
- The second idea was: instead of replacing the entire item template, try to compose the built-in item template with the one from the outside, inserting it manually inside the `.item` wrapper. 
  - Hard to implement. The puzzle is: when registering the overlay element, Polymer parses the contents of `<template>` nodes as well, extracting bindings into the annotations. After this parsing at the register time, it’s impossible to modify the contents of the item template.
    - Tried to disable parsing bindings on the overlay register by adding `<template preserve-content>` (undocumented Polymer feature) attribute to the `iron-list` item template. This makes it possible to modify the item template, but at the same time effectively prevents the `.item` bindings to the overlay methods from being parsed and working. Hence the `focused` indication and ARIA attributes don’t work.
- The working idea: instead of manually modifying the item template, change the `div.item` into a separate `vaadin-combo-box-item` element, that would support custom template in the `template` property. This is currently implemented in the prototype branch.
  - For the item element, we need to `templatize()` it with either a given template or a default item template, stamp a template instance and append it to the light DOM. The changes to the bound `item` model should be updated on the stamped template instance manually.
  - `iron-list` exposes the item nodes in the light DOM. But still the overlay also needs to expose the `iron-list` in the light DOM, in order to be targetable with global CSS.
### Related issues
- #106

### LINKED ISSUE #374: F-test: test/selecting-items.html » selecting a value » should fire `selection-changed` after the scrolling grace period
https://travis-ci.org/vaadin/vaadin-combo-box/builds/192486662

### PR DESCRIPTION
**Pull request by platosha**
Fixes #165
Fixes #374

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/376)

### CODE REVIEW

**Comment by limonte** [comment]
nice! :lgtm:

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-KauyLXaiROdVCq4FipA:bbixqh9)*

**Comment by Saulis** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: 7 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-overlay.html, line 111 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav5ajIt8rONqdVLwtp:-Kav5ajIt8rONqdVLwtq:b-m5zu0i) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L111)):*
> ```HTML
> 
>     behaviors: [
>       Polymer.Templatizer,
> ```

Like discussed, let's move `Polymer.Templatizer` to `vaadin-combo-box` to have correct binding scopes for the templates out-of-the-box. (applying functions and event listeners inside the template should work)

---

*[vaadin-combo-box-overlay.html, line 385 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav5ShIpyfNdWU7Rmig:-Kav5ShJNSijl9CnQocv:bawlh16) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L385)):*
> ```HTML
>     get _instanceProps() {
>       return {
>         item: true
> ```

Could be a good idea to add `index` variable.

---

*[vaadin-combo-box-overlay.html, line 396 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav51dqBmj2uxEsm1Uh:-Kav51dqBmj2uxEsm1Ui:b-4kg4p3) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L396)):*
> ```HTML
>     },
> 
>     _forwardInstanceProp: function(instance, prop, value) {
> ```

I'm not sure if need we need `_forwardInstanceProp` nor `_forwardInstancePath` functions at all at this point since we won't support two-way binding for `item`. Let's try if everything works without these functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376)*

**Comment by platosha** [comment]
Review status: 4 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-overlay.html, line 111 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav5ajIt8rONqdVLwtp:-KavjA2_HReWFKhSBN2k:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L111)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Like discussed, let's move `Polymer.Templatizer` to `vaadin-combo-box` to have correct binding scopes for the templates out-of-the-box. (applying functions and event listeners inside the template should work)
</blockquote></details>

Done.

---

*[vaadin-combo-box-overlay.html, line 385 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav5ShIpyfNdWU7Rmig:-KavpzLYCDBbDTAG61zx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L385)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Could be a good idea to add `index` variable.
</blockquote></details>

Done.

---

*[vaadin-combo-box-overlay.html, line 396 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kav51dqBmj2uxEsm1Uh:-KavjBL9bAsrjubnuSXp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/ad5631af1e897b5b577dc0b0f492333e315a0564/vaadin-combo-box-overlay.html#L396)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I'm not sure if need we need `_forwardInstanceProp` nor `_forwardInstancePath` functions at all at this point since we won't support two-way binding for `item`. Let's try if everything works without these functions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r4, 23 of 23 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[test/overlay-position.html, line 96 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kaw7u0TWGE4Hn3gsgZ2:-Kaw7u0TWGE4Hn3gsgZ3:bmif6tb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/test/overlay-position.html#L96)):*
> ```HTML
>       horiCenter = ww * 0.5;
>       vertTop = 0;
>       vertBottom = wh - 100;
> ```

Maybe a comment stating `100` adjustment here to make sure combobox is above the bottom of the viewport.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-Kaw8IAlY8xykohzSHmU:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-behavior.html, line 613 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kaw9r2EsKXTtG52ZXAD:-Kaw9r2JYuuGeohCztcK:b-k200wl) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/vaadin-combo-box-behavior.html#L613)):*
> ```HTML
>       return {
>         item: true,
>         index: true
> ```

Should we have an instance prop for "selected" also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376)*

**Comment by Saulis** [comment]
:lgtm_cancel: Let's add `[[selected]]` and `[[focused]]` to the item before merging.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-KawAtQGKA4rr2Sg3lfd:b-cwvkvg)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-item.html, line 3 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-KawAWlTX3KNRZE_QWor:-KawAWlU0W1r-uhsOJC-:b-qkjxnv) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/vaadin-combo-box-item.html#L3)):*
> ```HTML
>

**Comment by platosha** [comment]
@saulis done

---

Review status: 19 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 613 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kaw9r2EsKXTtG52ZXAD:-KawcyZOi8tUOdZXew1u:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/vaadin-combo-box-behavior.html#L613)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we have an instance prop for "selected" also?
</blockquote></details>

Done.

---

*[vaadin-combo-box-item.html, line 3 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-KawAWlTX3KNRZE_QWor:-KawdcgYqWvFIaK5lorC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/vaadin-combo-box-item.html#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

2015 -> 2017 :)
</blockquote></details>

Done.

---

*[test/overlay-position.html, line 96 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-Kaw7u0TWGE4Hn3gsgZ2:-Kawct9jUIgXIl-RNCpD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/63f99de641784c69087f1b24793e4adb6329f56d/test/overlay-position.html#L96)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Maybe a comment stating `100` adjustment here to make sure combobox is above the bottom of the viewport.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-KawcwBuDLncCBfqUDGi:b-bnz094)*

**Comment by Saulis** [comment]
:lgtm: As a comment, we might want to add a filter to `index.html` to hide API documentation for internal elements and behaviors like `<vaadin-combo-box-overlay>` and `<vaadin-combo-box-item>`. Let's do that separately – I'll add a ticket for it.

---

Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-Kb9DATyGapjTsblD0w_:bjbzi46)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/376#-:-Kb9HNeL7ysilHJ-AY9p:bnfp4nl)*

**Pull request merged**
