### PR TITLE
Align demos with other vaadin elements

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/328)

### CODE REVIEW

**Comment by platosha** [comment]
The alignment is incomplete without throwing the texts away.

Also, the previous topic-based grouping in files might have some naming issues, but had sense in general. I wouldn’t regroup the demos without a good reason for changing grouping.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGw_Opqkpgw07JGQRw:-KUGw_OqyJJAG30cPZvt:b-vg3oky) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/vaadin-combo-box-behavior.html#L67)):*
> ```HTML
>         type: String,
>         value: '',
>         notify: true
> ```

Accidental change?

---

*[demo/common.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH1b9dlF_h78jHCrat:-KUH1b9dlF_h78jHCrau:bnzrsur) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/common.html#L89)):*
> ```HTML
>         'Vanadium', 'Xenon', 'Ytterbium', 'Yttrium', 'Zinc', 'Zirconium'];
> 
>     var elementsJson = [
> ```

This was bundled with demos in the `object-items.html` for reasons. It is a bit heavy and completely useless for the other demos at the same time. Why moving to common.html?

---

*[demo/index.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGxTNjm0ieIU7hmlij:-KUGxTNjm0ieIU7hmlik:b-f7bjca) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/index.html#L51)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Selecting a value</h3>
> ```

Titlecase please:
```
<h3>Selecting a Value</h3>
```

---

*[demo/index.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGzcWMZKS9HOD27RGw:-KUGzcWMZKS9HOD27RGx:bowdam7) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/index.html#L75)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Using as a form field</h3>
> ```

Titlecase please:
```
<h3>Using as a Form Field</h3>
```

---

*[demo/objects.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH14A_mGmG1RznUp1E:-KUH14A_mGmG1RznUp1F:b-si4m42) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/objects.html#L9)):*
> ```HTML
>   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
> 
>   <title>vaadin-combo-box Object Items Examples</title>
> ```

Any reasons to rename “object-items.html” to “objects.html”? I personally prefer the previous name, it was more descriptive IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-:-KUH-32kpQcNBNZIBv5k:bnqhz6q)*

**Comment by manolo** [comment]
Well I thought that they are still good when demoing, But agree, it is duplicated in doc and here, so it's better not to double maintain the same texts.

Related with grouping the demos, to me, it makes perfect sense to have the grouping like it is now, it simplifies the number of tabs.  

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-combo-box-behavior.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGw_Opqkpgw07JGQRw:-KULPn0F4qaWj2jAwxiY:b-6afzju) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/vaadin-combo-box-behavior.html#L67)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Accidental change?
</details>
yes, comes for the other PR, will remov

---

*[demo/common.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH1b9dlF_h78jHCrat:-KULNp3MqdHfKMGSkA22:b-5kjpdb) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/common.html#L89)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> This was bundled with demos in the `object-items.html` for reasons. It is a bit heavy and completely useless for the other demos at the same time. Why moving to common.html?
</details>
It does not hit performance since it's a plain array, and it could be eventually used in other demos.
Including this in the demo itself makes that when the user takes a look to the demo source there is a lot of irrelevant code in it. I expect all auxiliary code for the demos to be in a separated file.

---

*[demo/objects.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH14A_mGmG1RznUp1E:-KULOYbuviSdstSE3OD8:b-u29c2c) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/objects.html#L9)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Any reasons to rename “object-items.html” to “objects.html”? I personally prefer the previous name, it was more descriptive IMO.
</details>
All other demos are one word files. To me objects is as meaningful than object-items. I expect in this demo file to find examples with objects for the combo-box items, if the file was called arrays, I would expect array items. But anyway is this a blocker ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-:-KULNZXfQVpkzG7jOT8l:b-au5xty)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/objects.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH14A_mGmG1RznUp1E:-KUMFpPejcWxgSEUQ2-N:bn15l83) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/objects.html#L9)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> All other demos are one word files. To me objects is as meaningful than object-items. I expect in this demo file to find examples with objects for the combo-box items, if the file was called arrays, I would expect array items. But anyway is this a blocker ?
</details>
OK. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-behavior.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGw_Opqkpgw07JGQRw:-KUvs95e0x66Cjj7qvu0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/vaadin-combo-box-behavior.html#L67)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> yes, comes for the other PR, will remov
</details>
Done.

---

*[demo/index.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGxTNjm0ieIU7hmlij:-KUvrvdwOGhxoXrSUeBC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/index.html#L51)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Titlecase please:
> ```
> <h3>Selecting a Value</h3>
> ```
</details>
Done.

---

*[demo/index.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUGzcWMZKS9HOD27RGw:-KUvrwB3XkbLLEXNAg6M:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/index.html#L75)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Titlecase please:
> ```
> <h3>Using as a Form Field</h3>
> ```
</details>
Done.

---

*[demo/objects.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUH14A_mGmG1RznUp1E:-KUvrxXxPJOF7MNke4BF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/73a5a0ca5c392a38d24405eadba14148404e79fa/demo/objects.html#L9)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> OK. Not a blocker.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328)*

**Comment by platosha** [comment]
:lgtm: overall. A few minor questions left, no blockers.

Needs rebase.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUvzzPr6X0EVXrPNQ8I:-KUvzzPr6X0EVXrPNQ8J:bre33qr) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/advanced.html#L70)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Customizing the Input with an &lt;iron-input></h3>
> ```

BTW: Would it be more exact to call it `Using with Iron Input`? My feeling is that customizing doesn’t represent the meaning completely here, it actually means replacing the builtin input, but not applying some customizations on it.

I would also mention `Input Element` here, in order to reduce confusion with the users’s text input data.

---

*[demo/advanced.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUw0kerx1Qe_hKSWBDr:-KUw0kerx1Qe_hKSWBDs:bqbmptx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/advanced.html#L85)):*
> ```HTML
> 
> 
>     <h3>Customizing Input with a &lt;paper-input></h3>
> ```

BTW: Same as above.

Also, it was `Customizing the Input` above, but `Customizing Input` here.

---

*[demo/objects.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUw2adLoOcnf8GkGzr4:-KUw2adMqjJmvGMfeUdx:bt1ya8f) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/objects.html#L30)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <vaadin-combo-box class="numbers-box" label="Number"></vaadin-combo-box>
> ```

BTW: The other demo files use `#id` selectors, this one uses `.class`. Should we use `#numbers-box` and `#elements-box` selectors here as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-:-KUw2uFbE6o3ADojUJBh:bx0d7dt)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUvzzPr6X0EVXrPNQ8I:-KUwImRN-wetRCmS5gkb:bav2lmz) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/advanced.html#L70)):*
> I would also mention Input Element here, 

How would do you rephrase the title to include it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUw0kerx1Qe_hKSWBDr:-KUwM1LJSs0-zuQYjXEF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/advanced.html#L85)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> BTW: Same as above.
> 
> Also, it was `Customizing the Input` above, but `Customizing Input` here.
</details>
Done.

---

*[demo/objects.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUw2adLoOcnf8GkGzr4:-KUwM43JuSXUfVX7ipv-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/objects.html#L30)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> BTW: The other demo files use `#id` selectors, this one uses `.class`. Should we use `#numbers-box` and `#elements-box` selectors here as well?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328#-KUvzzPr6X0EVXrPNQ8I:-KUwMUaXUKo8L6E5yCbc:b-vur969) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/7221a37fef38627f5a8d3d7ffdc478dcd52e4afc/demo/advanced.html#L70)):*
Oh, it’s already enough that we mention `<iron-input>`. OK now.

Was thinking of something like:

> Replacing the Input Element with `<iron-input>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/328)*

**Pull request merged**
