### PR TITLE
Update Lumo theme

### LINKED ISSUE #598: Overlay content theme padding inconsistent with vaadin-dropdown-menu
### Description

`vaadin-combo-box` does not have padding around the content, see [this line](https://github.com/vaadin/vaadin-combo-box/blob/master/theme/valo/vaadin-combo-box-dropdown.html#L10)
screen shot 2018-01-09 at 15 22 15

This causes the missing space around the first item at the top, and the last one at the bottom, which feels not so nice in comparison with `vaadin-dropdown-menu`:

screen shot 2018-01-09 at 15 22 25

Changing the padding to the following seems to fix this:
```css
[part="content"] {
  padding:  var(--valo-space-xs) 0;
}
```

### LINKED ISSUE #605: Dropdown list open speed regression
### Description
Hello there,
i upgrade from very old version 1.0 to v3.0.2, in order to support polymer 2, but i got performance regression: for 500 elements in combobox, it displayed dropdown list immediately, but with the v3.0.2, it takes 2 or 3 seconds.
or just wait the new v4.0 ?

another question, the new combobox increased its height, any idea to reuse old v1.0 like (paper-input like) style ?

### Expected outcome
drop down list should open quickly

### Actual outcome
now it takes 3s to show 500 elements

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### PR DESCRIPTION
**Pull request by jouni**
Depend on latest `vaadin-item` theme, and copy latest style changes from `vaadin-list-box` (e.g. separate hover and focus styles for items).

Fix overlay “padding” by using the undocumented (and unsupported) CSS mixin and setting a border on the internal iron-list items container.

Fixes #598 
Fixes #605

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/601)

### CODE REVIEW

**Comment by jouni** [comment]
*[theme/lumo/vaadin-combo-box-dropdown.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-L3YFes6hRIG1jFiYMu8:-L3YPQ54KmbiYkDocWf4:b-dy5klx) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/26ef3dbbadcdd99a8fec0d3647cb9575351688d6/theme/lumo/vaadin-combo-box-dropdown.html#L17)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Demos are broken with this change (open combo-box and scroll down to see blank space under the items).
</blockquote></details>

That’s true, I noticed that, and was supposed to write about that in the PR description, that hopefully, someone can pinpoint the problem. There’s a lot of messy legacy code in combo box, and my suspect for this issue is the out-of-sync max-height’s set for many of the elements in the overlay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-combo-box-dropdown.html, line 17 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/601#-L3YFes6hRIG1jFiYMu8:-L3bJGqgBQEsJIcTkEAU:b-62101n) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/26ef3dbbadcdd99a8fec0d3647cb9575351688d6/theme/lumo/vaadin-combo-box-dropdown.html#L17)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

That’s true, I noticed that, and was supposed to write about that in the PR description, that hopefully, someone can pinpoint the problem. There’s a lot of messy legacy code in combo box, and my suspect for this issue is the out-of-sync max-height’s set for many of the elements in the overlay.
</blockquote></details>

It looks like adding either `border`, `padding` or `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/601)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-combo-box-dropdown.html, line 17 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/601#-L3YFes6hRIG1jFiYMu8:-L3bJdi50WLDrZHwqTF6:b-b6dk3l) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/26ef3dbbadcdd99a8fec0d3647cb9575351688d6/theme/lumo/vaadin-combo-box-dropdown.html#L17)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

It looks like adding either `border`, `padding` or `
</blockquote></details>

It looks like adding either `border`, `padding` or `margin` on the top and / or bottom side breaks and the wrong count of items get rendered...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/601)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-combo-box-dropdown.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-L3YFes6hRIG1jFiYMu8:-L3bnV8FAGKvd-PlCzTU:b-4ibg69) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/26ef3dbbadcdd99a8fec0d3647cb9575351688d6/theme/lumo/vaadin-combo-box-dropdown.html#L17)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

It looks like adding either `border`, `padding` or `margin` on the top and / or bottom side breaks and the wrong count of items get rendered...
</blockquote></details>

Discussed in person and decided to remove this block of styles for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-:-L3bqFVEFofj35Bry0sl:bnfp4nl)*

**Comment by web-padawan** [comment]
Still some issues with scrollbar after my attempt to fix: the scrollbar is now inset, and there’s no space between the item and the scrollbar. Also, scrollbar disappears at all in Safari with the  “Always show scrollbars” setting.

:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-:-L3cEFtI5w0-ZFUbLhUr:b-i9xiia)*

**Comment by web-padawan** [comment]
@jouni so I ended up win another hack: setting zero `box-shadow` on the `--iron-list-items-container` restores disappearing scroll bar. Seems to be a Safari bug, because setting either `box-shadow` or `border-radius` (like it was before) on the `#scroller` element does the same trick.

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box/601#-:-L3dbekfCUyfaPmenO5G:b-pvkml0)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-:-L3gwNsm5LUtBuq4644n:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601)*

**Comment by tomivirkki** [comment]
:lgtm: Nice!

---

Reviewed 4 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/601#-:-L3mHIpVQfLc4lAhGyrk:b-8gk8uj)*

**Pull request merged**
