### PR TITLE
Remove the style scope of combo-box from overlay when using Shadow DOM

### LINKED ISSUE #118: Overlay inherits style scope of combo-box when using shady DOM
The overlay gets a style scope class of combo-box when using shady DOM, even when appended to body. This makes it hard and inconsistent with native shadow DOM to target the overlay with custom document styles.

Solution: use Polymer.dom(document.body) API when attaching the overlay, as mentioned in #117

### PR DESCRIPTION
**Pull request by platosha**
Fixes #118

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/211)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-overlay-behavior.html, line 58 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211#-KF3lqP1Hp0wXjmedcBn:-KF3lqP1Hp0wXjmedcBo:278263636) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1cf5ed6850614aa7ddaefacfb0065e3606c5d5e8/vaadin-overlay-behavior.html#L58)):*
The style scope is never restored so the overlay remains visible once returned back to local DOM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay-behavior.html, line 58 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211#-KF3lqP1Hp0wXjmedcBn:-KF3peOcUq6FjFyC-ezn:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/1cf5ed6850614aa7ddaefacfb0065e3606c5d5e8/vaadin-overlay-behavior.html#L58)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211)*

**Comment by tomivirkki** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/211#-:-KF3yGEqkfP9UxSjP9Ij:980077423)*

**Pull request merged**
