### PR TITLE
Fix a couple of flaky tests

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/210)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box-overlay.html, line 221 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210#-KF35YzlTRs0pVdGixD_:-KF35YzmFLbRqkdwHPlR:-2077277406) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a33e530d25d4b5b104eebed010c9704e5bbf43ff/vaadin-combo-box-overlay.html#L221)):*
I'd leave out the last sentence. If you want to include the information, commit message would be more suitable. Having this in the core element source as a comment feels out-of-place.

---

*[test/overlay-position.html, line 89 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210#-KF34ka8-mVWZI5dHLXI:-KF34ka95mzmnoGP4Y-6:-2118939212) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a33e530d25d4b5b104eebed010c9704e5bbf43ff/test/overlay-position.html#L89)):*
"Use floor values so that zooming in Chrome doesn't make the test fail"

Could you also squash the commits in this pr into one? There's currently separate commits for minor text fixes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-combo-box-overlay.html, line 221 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210#-KF35YzlTRs0pVdGixD_:-KF3yGuFk6toE0_-CVKy:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a33e530d25d4b5b104eebed010c9704e5bbf43ff/vaadin-combo-box-overlay.html#L221)):*
Done.

---

*[test/overlay-position.html, line 89 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210#-KF34ka8-mVWZI5dHLXI:-KF3yHSQFxWnYrf1lXLq:-499146009) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/a33e530d25d4b5b104eebed010c9704e5bbf43ff/test/overlay-position.html#L89)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/210)*

**Pull request merged**
