### PR TITLE
Language corrections

### PR DESCRIPTION
**Pull request by jojule**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/172)

### CODE REVIEW

**Comment by jounik** [comment]
@magi42, please review the second change (adding "The" in front of vaadin-combo-box).

For the "selection value", to me it seems misleading. There are two properties, "value" and "selectedItem", but only the value fires an event when it changes. Not sure if we should mix them in the documentation.

**Comment by magi42** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-combo-box-basic.adoc, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/172#-KBRgEjI1EsbedV7ZF-t:-KBRgEjJ34YbI_YkRQZV:2050350839) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/af7dcfc28b2eb2e08a3de98680a803440ea5b833/docs/vaadin-combo-box-basic.adoc#L66)):*
The "vaadin-combo-box" tag name is, well, a name, hence it can't have article, but as it's a lower-case name, can't use it in the beginning of sentence either. Hence the convention is to always write: "The <name> element", or in this case, "The [vaadinelement]#vaadin-combo-box# element..."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/172)*

**Comment by magi42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-combo-box-basic.adoc, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/172#-KBRgEjI1EsbedV7ZF-t:-KBRhpHMm2Oyv7KPe55h:-1133888479) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/af7dcfc28b2eb2e08a3de98680a803440ea5b833/docs/vaadin-combo-box-basic.adoc#L66)):*
Oh Reviewable ate my formatting, it was supposed to read: "`The <name> element`"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/172)*

**Comment by jounik** [comment]
> For the "selection value", to me it seems misleading. There are two properties, "value" and "selectedItem", but only the value fires an event when it changes. Not sure if we should mix them in the documentation.

Actually that was wrong. There are two events fired for this. @jojule, can you elaborate what you think was misleading in the original description about "value changes", and why it would need to be more specifically "selection value changes"?

**Comment by jounik** [comment]
Fixed the latter change, I rephrased it in 5145bff8c461e5aeda9318008ba1e59719065367

For the former change (about "selection value change"), any unclear issues regarding it should be handled in https://github.com/vaadin/components-team-tasks/issues/91

**Pull request closed without merging**
