### PR TITLE
Unify height with paper-input. Fixes #91

### LINKED ISSUE #91: Unify sizing with paper-inputs
Currently `vaadin-combo-box` looks a bit out of place in a form with other paper-inputs as it is sized or aligned differently.

screen shot 2015-12-14 at 8 54 33 am

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/95)

### CODE REVIEW

**Comment by tehapo** [comment]
I would fix the commit message (`peper-input` should be `paper-input`). Otherwise LGTM.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/95#-:-K5jffXd5MfyN9ScCUPI:-1741949170)*

**Comment by tehapo** [comment]
After looking at this again, I noticed that the label is still not perfectly aligned with `paper-input` (see the attached screenshot).

Looks like removing the lines 137–140 would fix the alignment.
```
paper-input-container label {
  top: auto;
  bottom: 3px;
}
```

screen shot 2015-12-21 at 08 46 59

**Comment by manolo** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/95#-:-K6Ahf6zG0ODTATGk0WP:1706342915)*

**Comment by tehapo** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/95#-:-K7AxSbHXnkRx2f3vkR0:980077423)*

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/95)*

**Comment by tehapo** [comment]
Pushed a rebased version of this branch to see if it makes all tests pass.

**Pull request merged**
