### PR TITLE
use slots instead of content

### PR DESCRIPTION
**Pull request by manolo**
Connected to #413

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box/419)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[vaadin-combo-box-overlay.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBc2EeGtn9FyvPUrV:-KfkBc2EeGtn9FyvPUrW:bqz50mn) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-overlay.html#L34)):*
> ```HTML
>       #scroller {
>         overflow: auto;
>         max-height: var(--vaadin-combo-box-overlay-max-height, var(65vh));
> ```

Why is the "65vh" wrapped in var?

---

*[vaadin-combo-box-shared-styles.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-Kfk9rZZGDBi-Gj7618d:-Kfk9rZZGDBi-Gj7618e:bn0xat1) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-shared-styles.html#L30)):*
> ```HTML
>       }
> 
>       :host(:not([has-value])) ::content [slot=clear-button],
> ```

`::slotted` is already polyfilled (since https://www.polymer-project.org/blog/2016-10-03-1.7-release) so `::content` isn't needed anymore

---

*[vaadin-combo-box.html, line 220 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkA4p8IphG5iJyfVuM:-KfkA4p8IphG5iJyfVuN:b95oeqd) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box.html#L220)):*
> ```HTML
>       </slot>
> 
>       <dom-if>
> ```

This is only required in non Polymer-managed templates https://www.polymer-project.org/2.0/docs/devguide/templates#dom-if

---

*[vaadin-spinner.html, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkB5Pp1lopZFM-X4rG:-KfkB5Pp1lopZFM-X4rH:b-33pd05) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-spinner.html#L14)):*
> ```HTML
>         display: block;
>         box-sizing: border-box;
>         border: 2px solid var(--primary-color, var(#03A9F4));
> ```

What's this? Doesn't look right: `var(#03A9F4)`

---

*[test/selecting-items.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBB0rrygbpoELTf1H:-KfkBB0rrygbpoELTf1I:b28zz80) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/test/selecting-items.html#L25)):*
> ```HTML
>   <template>
>     <vaadin-combo-box>
>       <div slot="clear-button" class="clear-button">CLEAR</div>
> ```

class="clear-button" can be removed at the same time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419)*

**Comment by limonte** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[vaadin-combo-box-overlay.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBc2EeGtn9FyvPUrV:-KfkE33dXdG2rpCil9d6:b7o5dve) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-overlay.html#L34)):*
https://github.com/Polymer/polymer#css-custom-property-shim

> `var(--a, --b)` should be `var(--a, var(--b))`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419)*

**Comment by tomivirkki** [comment]
*[vaadin-combo-box-overlay.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBc2EeGtn9FyvPUrV:-KfkFZ3-VFqhmbPxVasz:bd97sct) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-overlay.html#L34)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

https://github.com/Polymer/polymer#css-custom-property-shim

> `var(--a, --b)` should be `var(--a, var(--b))`
</blockquote></details>

`--b` is a variable name but `65vh` is a literal. `var(65vh)` is invalid and doesn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419)*

**Comment by manolo** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-combo-box-overlay.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBc2EeGtn9FyvPUrV:-KfzcbNaFZ8Vvt59U4RI:bfii31b) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-overlay.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`--b` is a variable name but `65vh` is a literal. `var(65vh)` is invalid and doesn't work.
</blockquote></details>

Regexp used to change ocurrences changed this as well, fixed
Done.

---

*[vaadin-combo-box-shared-styles.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-Kfk9rZZGDBi-Gj7618d:-KfzkX1iSV4FHIHE-i6O:b-ymbbon) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box-shared-styles.html#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`::slotted` is already polyfilled (since https://www.polymer-project.org/blog/2016-10-03-1.7-release) so `::content` isn't needed anymore
</blockquote></details>

We need that when we have some custom content in shady dom. Already discussed with @platosha. Try this:

```
      :host(:not([has-value])) ::content [slot=clear-button],
      :host(:not([has-value])) ::slotted([slot=clear-button]),
      :host(:not([has-value])) .clear-button {
        background: red;
      }

```
```
  <vaadin-combo-box  items='[1,2,3,4]' label="AAA" >
    <div slot="clear-button" >CLEAR</div>
    <div slot="toggle-button" class="toggle-button">TOGGLE</div>
  </vaadin-combo-box>

  <vaadin-combo-box  items='[1,2,3,4]' >
  </vaadin-combo-box>
```

If you remove the `::content` line the custom clear div in the first example is not red in shady dom polymer 1.7+

---

*[vaadin-combo-box.html, line 220 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkA4p8IphG5iJyfVuM:-KfzdY7jW9fgU6R24KcF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-combo-box.html#L220)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is only required in non Polymer-managed templates https://www.polymer-project.org/2.0/docs/devguide/templates#dom-if
</blockquote></details>

Done.

---

*[vaadin-spinner.html, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkB5Pp1lopZFM-X4rG:-Kfzd-03H_mLznH6hWeM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/vaadin-spinner.html#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What's this? Doesn't look right: `var(#03A9F4)`
</blockquote></details>

Done.

---

*[test/selecting-items.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-KfkBB0rrygbpoELTf1H:-Kfzd7r31OYBEgL7gtYE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box/blob/438aeead89b8bd278b7cfa28d085801b053eecef/test/selecting-items.html#L25)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

class="clear-button" can be removed at the same time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-:-Kg-nsPukMvfWr62wxnu:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box/419#-:-KgXrwUqYd6cE1vNNyup:bnfp4nl)*

**Pull request merged**
